create materialized view chew_performance
tablespace ts_report
as
select
    TO_CHAR(d."date"::date, 'YYYY-MM-DD') as Day_reported,
    TO_CHAR(d.reported::date, 'MM') AS Reported_month,
    TO_CHAR(d.reported::date, 'Month') AS Reported_monthname,
    TO_CHAR(d.reported::date, 'YYYY') AS Reported_year,
    TO_CHAR(d.reported::date, 'YYYY-MM') AS Reported_month_year,
    TO_CHAR(d.reported::date, 'YYYY-"Q"Q') AS Reported_quarter,
    mh.district,
    mh.region,
    
    --COUNT(DISTINCT CASE WHEN d.supervisor_name is not NULL and d.contact_id is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as supervisors_total,
    --COUNT(DISTINCT CASE WHEN d.supervisor_name is NULL and d.contact_id is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as chw_nosuperviors,
    --COUNT(DISTINCT CASE WHEN d.supervisor_name is not NULL and d.contact_id is null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as superviors_nochw,
    COUNT(DISTINCT CASE WHEN d.form_name is not NULL and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as chw_worked,
    COUNT(DISTINCT CASE WHEN mc.facility_id is not NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as chw_tagged_facility,
    COUNT(DISTINCT CASE WHEN mc.facility_id is NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as chw_nottagged_facility,
    
    COUNT(DISTINCT CASE WHEN mc.role = 'VHT' THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS role_vht,
	COUNT(DISTINCT CASE WHEN mc.role = 'OTHER' THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS role_other,
	COUNT(DISTINCT CASE WHEN mc.role = 'CHEW' THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS role_chew,
	COUNT(DISTINCT CASE WHEN mc.role = 'SUPER CHEW' THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS role_superchew,
	
	COUNT(DISTINCT CASE WHEN d.form_name = 'screening' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_screening,
	COUNT(DISTINCT CASE WHEN d.form_name = 'wash_report' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_wash_report,
	COUNT(DISTINCT CASE WHEN d.form_name = 'assessment' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_assessment,
	COUNT(DISTINCT CASE WHEN d.form_name = 'prescription_summary' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as prescription_summary,
	COUNT(DISTINCT CASE WHEN d.form_name = 'referral_follow_up' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_referral_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'anc_visit_follow_up' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_anc_visit_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'treatment_follow_up' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_treatment_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'household_model_follow_up' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_household_model_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'fp_registration' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_fp_registration,
	COUNT(DISTINCT CASE WHEN d.form_name = 'anc_referral_follow_up' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_anc_referral_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'maternal_nutrition_follow_up' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_maternal_nutrition_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'mute' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_mute,
	COUNT(DISTINCT CASE WHEN d.form_name = 'unmute' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_unmute,
	COUNT(DISTINCT CASE WHEN d.form_name = 'fp_referral_follow_up' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_fp_referral_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'pnc_baby_follow_up' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_pnc_baby_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'vht_consumption_log' and d.reported is not null THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) as recoded_vht_consumption_log,
	COUNT(DISTINCT CASE WHEN d.form_name = 'household_model_notification' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_household_model_notification,
	COUNT(DISTINCT CASE WHEN d.form_name = 'vht_supervision' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_vht_supervision,
	COUNT(DISTINCT CASE WHEN d.form_name = 'death_report' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_death_report,
	COUNT(DISTINCT CASE WHEN d.form_name = 'stockout' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_stockout,
	COUNT(DISTINCT CASE WHEN d.form_name = 'delivery_check' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_delivery_check,
	COUNT(DISTINCT CASE WHEN d.form_name = 'copy_of_danger_signs_follow_up_report' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_copy_of_danger_signs_follow_up_report,
	COUNT(DISTINCT CASE WHEN d.form_name = 'maternal_health_education' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_maternal_health_education,
	COUNT(DISTINCT CASE WHEN d.form_name = 'pregnancy' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_pregnancy,
	COUNT(DISTINCT CASE WHEN d.form_name = 'pnc_danger_sign' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_pnc_danger_sign,
	COUNT(DISTINCT CASE WHEN d.form_name = 'stock_count' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_stock_count,
	COUNT(DISTINCT CASE WHEN d.form_name = 'fp_follow_up' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_fp_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'anc_danger_sign' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_anc_danger_sign,
	COUNT(DISTINCT CASE WHEN d.form_name = 'pnc_follow_up' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_pnc_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'delivery' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_delivery,
	COUNT(DISTINCT CASE WHEN d.form_name = 'death_notification' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_death_notification,
	COUNT(DISTINCT CASE WHEN d.form_name = 'drowning_workflow' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_drowning_workflow,
	COUNT(DISTINCT CASE WHEN d.form_name = 'copy_of_danger_signs_report' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_copy_of_danger_signs_report,
	COUNT(DISTINCT CASE WHEN d.form_name = 'copy_of_ha_danger_signs_follow_up_report' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_copy_of_ha_danger_signs_follow_up_report,
	COUNT(DISTINCT CASE WHEN d.form_name = 'health_education' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_health_education,
	COUNT(DISTINCT CASE WHEN d.form_name = 'newborn_danger_sign_follow_up' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_newborn_danger_sign_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'tb_screening' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_tb_screening,
	COUNT(DISTINCT CASE WHEN d.form_name = 'training_evaluation' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_training_evaluation,
	COUNT(DISTINCT CASE WHEN d.form_name = 'ncd_screening' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_ncd_screening,
	COUNT(DISTINCT CASE WHEN d.form_name = 'ha_danger_signs_follow_up' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_ha_danger_signs_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'child_health_escalation' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_child_health_escalation,
	COUNT(DISTINCT CASE WHEN d.form_name = 'vht_home_location' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_vht_home_location,
	COUNT(DISTINCT CASE WHEN d.form_name = 'support_supervision' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_support_supervision,
	COUNT(DISTINCT CASE WHEN d.form_name = 'tb_results_notification' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_tb_results_notification,
	COUNT(DISTINCT CASE WHEN d.form_name = 'pregnancy_danger_sign_follow_up' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_pregnancy_danger_sign_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'sputum_collection' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_sputum_collection,
	COUNT(DISTINCT CASE WHEN d.form_name = 'tb_referral_follow_up' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_tb_referral_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'sdx_results' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_sdx_results,
	COUNT(DISTINCT CASE WHEN d.form_name = 'uncompleted_referral' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_uncompleted_referral,
	COUNT(DISTINCT CASE WHEN d.form_name = 'undo_death_report' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_undo_death_report,
	COUNT(DISTINCT CASE WHEN d.form_name = 'child_health_notification' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_child_health_notification,
	COUNT(DISTINCT CASE WHEN d.form_name = 'child_nutrition_follow_up' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_child_nutrition_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'tb_follow_up' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_tb_follow_up,
	COUNT(DISTINCT CASE WHEN d.form_name = 'community_death_notification' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_community_death_notification,
	COUNT(DISTINCT CASE WHEN d.form_name = 'pregnancy_facility_visit_reminder' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_pregnancy_facility_visit_reminder,
	COUNT(DISTINCT CASE WHEN d.form_name = 'pnc_danger_sign_follow_up_mother' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_pnc_danger_sign_follow_up_mother,
	COUNT(DISTINCT CASE WHEN d.form_name = 'anc_danger_sign_escalation' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_anc_danger_sign_escalation,
	COUNT(DISTINCT CASE WHEN d.form_name = 'sdx_trigger' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_sdx_trigger,
	COUNT(DISTINCT CASE WHEN d.form_name = 'child_nutrition_referral_follow_up' AND d.reported IS NOT NULL THEN CONCAT_WS('-', mc.contact_id, mc.facility_id) END) AS recoded_child_nutrition_referral_follow_up

	
    from cht.mv_form_meta d
    LEFT JOIN cht.mv_cht_users AS mc ON d.contact_id = mc.contact_id
    LEFT JOIN cht.mv_chw_hierarchy AS mh ON d.contact_id = mh.chw_id
    where d.contact_id is not NULL
    GROUP by
    d."date",
    d.reported,
    mh.district,
    mh.region
    with data;