GRANT DELETE, TRIGGER, REFERENCES, TRUNCATE, UPDATE, INSERT, SELECT ON TABLE cht.mv_chew_hierarchy_2 TO baker;
GRANT DELETE, TRIGGER, REFERENCES, TRUNCATE, UPDATE, INSERT, SELECT ON TABLE cht.mv_chew_hierarchy_2 TO bkronnie;
GRANT DELETE, TRIGGER, REFERENCES, TRUNCATE, UPDATE, INSERT, SELECT ON TABLE cht.mv_chew_hierarchy_2 TO etl_user;
GRANT DELETE, TRIGGER, REFERENCES, TRUNCATE, UPDATE, INSERT, SELECT ON TABLE cht.mv_chew_hierarchy_2 TO jasper_user;
GRANT DELETE, TRIGGER, REFERENCES, TRUNCATE, UPDATE, INSERT, SELECT ON TABLE cht.mv_chew_hierarchy_2 TO mkizito;
GRANT DELETE, TRIGGER, REFERENCES, TRUNCATE, UPDATE, INSERT, SELECT ON TABLE cht.mv_chew_hierarchy_2 TO mpaul;
GRANT DELETE, TRIGGER, REFERENCES, TRUNCATE, UPDATE, INSERT, SELECT ON TABLE cht.mv_chew_hierarchy_2 TO nmadrine;
GRANT DELETE, TRIGGER, REFERENCES, TRUNCATE, UPDATE, INSERT, SELECT ON TABLE cht.mv_chew_hierarchy_2 TO rutayisire;
GRANT DELETE, TRIGGER, REFERENCES, TRUNCATE, UPDATE, INSERT, SELECT ON TABLE cht.mv_chew_hierarchy_2 TO senos;
--cht.mv_chew_hierarchy_2