-- Clear previous results (optional)
DELETE FROM deps_saved_ddl;

-- Save DDL for your specific list
SELECT cht.deps_save_ddl_for_objects_2(ARRAY[
    'cht.contactview_vht',
    'cht.mv_afp_notification',
    'cht.mv_anc_danger_sign',
    'cht.mv_anc_danger_sign_escalation',
    'cht.mv_anc_danger_sign_follow_up',
    'cht.mv_anc_danger_sign_notification',
    'cht.mv_anc_referral_follow_up',
    'cht.mv_anc_referral_follow_up_new',
    'cht.mv_anc_visit_follow_up',
    'cht.mv_areas',
    'cht.mv_assessment',
    'cht.mv_assessment_new',
    'cht.mv_cebs_signal_report_chew',
    'cht.mv_cebs_signal_report_vht',
    'cht.mv_cebs_signal_verification',
    'cht.mv_cebs_signal_verification_notification',
    'cht.mv_chew_hierarchy_2',
    'cht.mv_chew_hierarchy_3',
    'cht.mv_chew_performance',
    'cht.mv_child_health_escalation',
    'cht.mv_child_health_notification',
    'cht.mv_child_nutrition_follow_up',
    'cht.mv_child_nutrition_follow_up_new',
    'cht.mv_child_nutrition_referral_follow_up',
    'cht.mv_cht_users',
    'cht.mv_chw_hierarchy',
    'cht.mv_clinic',
    'cht.mv_community_death_notification_new',
    'cht.mv_community_death_notification_revised',
    'cht.mv_copy_of_danger_signs_follow_up_report',
    'cht.mv_death_notification',
    'cht.mv_death_report',
    'cht.mv_death_report_new',
    'cht.mv_delivery',
    'cht.mv_delivery_check',
    'cht.mv_delivery_report',
    'cht.mv_drowning_workflow',
    'cht.mv_facilities',
    'cht.mv_form_meta',
    'cht.mv_fp_follow_up',
    'cht.mv_fp_follow_ups',
    'cht.mv_fp_referral_follow_up',
    'cht.mv_fp_registration',
    'cht.mv_gbv_community_form',
    'cht.mv_ha_danger_signs_follow_up',
    'cht.mv_ha_danger_signs_follow_up_new',
    'cht.mv_health_education',
    'cht.mv_health_education_new',
    'cht.mv_household_model_follow_up',
    'cht.mv_household_model_follow_up_new',
    'cht.mv_household_model_notification',
    'cht.mv_households',
    'cht.mv_integrated_echis_performance',
    'cht.mv_maternal_health_education',
    'cht.mv_maternal_health_education_new',
    'cht.mv_maternal_nutrition_follow_up',
    'cht.mv_mute',
    'cht.mv_newborn_danger_sign_follow_up',
    'cht.mv_orgunit',
    'cht.mv_person',
    'cht.mv_pnc_baby_follow_up',
    'cht.mv_pnc_danger_sign',
    'cht.mv_pnc_follow_up',
    'cht.mv_population_demographics',
    'cht.mv_pregnancy',
    'cht.mv_pregnancy_danger_sign_follow_up',
    'cht.mv_pregnancy_new',
    'cht.mv_referral_follow_up',
    'cht.mv_screening',
    'cht.mv_sdx_follow_up',
    'cht.mv_sdx_notify',
    'cht.mv_sdx_trigger',
    'cht.mv_sputum_collection',
    'cht.mv_sputum_collection_refusal',
    'cht.mv_stock_count',
    'cht.mv_stockout',
    'cht.mv_support_supervision',
    'cht.mv_tb_follow_up',
    'cht.mv_tb_referral_follow_up',
    'cht.mv_tb_results_notification',
    'cht.mv_tb_screening',
    'cht.mv_training_evaluation',
    'cht.mv_treatment_follow_up_new',
    'cht.mv_uncompleted_referral',
    'cht.mv_unmute',
    'cht.mv_useview_fp_follow_ups',
    'cht.mv_vht_consumption_log',
    'cht.mv_vht_home_location',
    'cht.mv_vht_immunization',
    'cht.mv_vht_supervision',
    'cht.mv_wash',
    'cht.mv_wash_report',
    'cht.useview_death_notification'
]);

-- View results
SELECT deps_view_schema, deps_view_name, deps_ddl_to_run 
FROM deps_saved_ddl 
ORDER BY deps_view_schema, deps_view_name;