--CREATE TABLE report.mv_communicable_diseases_district (
    region text,
    district text,
    tperiod text,
    year integer,
    month integer,
    monthname text,
    month_year text,
    date date,
    "Persistent (Cases)" numeric,
    "Persistent (Deaths)" numeric,
    "Acute (Cases)" numeric,
    "Acute (Deaths)" numeric,
    "Acute" numeric,
    "Persistent" numeric,
    "Dysentery" numeric,
    "Dysentery (Cases)" numeric,
    "Dysentery (Deaths)" numeric,
    "Cholera" numeric,
    "Cholera (Cases)" numeric,
    "Cholera (Deaths)" numeric,
    "Typhoid Fever" numeric,
    "Typhoid Fever (Cases)" numeric,
    "Typhoid Fever (Deaths)" numeric,
    "Genital Ulcers (Cases)" numeric,
    "Septicemia (Cases)" numeric,
    "Peritonitis (Cases)" numeric,
    "Pneumonia (Cases)" numeric,
    "No Pneumonia - Cough and cold (Cases)" numeric,
    "Pyrexia of unknown origin (PUO) (Cases)" numeric,
    "TB (Cases)" numeric,
    "Tetanus (over 28 days age) (Cases)" numeric,
    "Sleeping sickness (Cases)" numeric,
    "Malaria Total (Cases)" numeric,
    "Malaria Confirmed (Microscopic &RDT) (Cases)" numeric,
    "Acute Flaccid Paralysis (Cases)" numeric,
    "Guinea Worm (Cases)" numeric,
    "Measles (Cases)" numeric,
    "Neonatal tetanus (Cases)" numeric,
    "Plague (Cases)" numeric,
    "Yellow Fever (Cases)" numeric,
    "Ebola (Cases)" numeric,
    "Marburg (Cases)" numeric,
    "Crimean-Cong Haemorrhagic Fever (Cases)" numeric,
    "Other Viral Hemorrhagic Fevers (Specify) (Cases)" numeric,
    "Severe Acute Respiratory Infection (SARI) (Cases)" numeric,
    "Presumptive MDR TB Cases (Cases)" numeric,
    "Other Emerging infectious Diseases, specify (Cases)" numeric,
    "Leishmaniasis (Cases)" numeric,
    "Lymphatic Filariasis (hydrocele) (Cases)" numeric,
    "Lymphatic Filariasis (Lympoedema) (Cases)" numeric,
    "Urinary Schistosomiasis (Cases)" numeric,
    "Intestinal Schistosomiasis (Cases)" numeric,
    "Onchocerciasis (Cases)" numeric,
    "Nodding Syndrome (Cases)" numeric,
    "Neonatal Sepsis 0-7days (Cases)" numeric,
    "Neonatal Sepsis 8-28days (Cases)" numeric,
    "Neonatal Pneumonia (Cases)" numeric,
    "Neonatal Meningitis (Cases)" numeric,
    "Neonatal Jaundice (Cases)" numeric,
    "Premature baby (as condition that requires mgt) (Cases)" numeric,
    "Other Neonatal Conditions (Cases)" numeric,
    "New attendance" numeric,
    "Re-attendance" numeric,
    "No. of admissions" numeric,
    "Total Deaths Reported" numeric,
    "Total" numeric
);

--CREATE TABLE report.mv_eidsr_weekly_enrollment_pivot (
    year integer,
    period integer,
    week text,
    total_enrolled numeric,
    adilang_enrolled numeric,
    kawaala_enrolled numeric,
    kibuli_enrolled numeric,
    kiswa_enrolled numeric,
    kitebi_enrolled numeric,
    nsambya_enrolled numeric,
    mukono_general_enrolled numeric,
    entebbe_regional_enrolled numeric
);

--CREATE TABLE report.mv_eidsr_event_data_summary_flat (
    event_date timestamp with time zone,
    year text,
    period numeric,
    region_name text,
    district_name text,
    subcounty_name text,
    facility_name text,
    is_sentimental boolean,
    org_level text,
    enrollment_status text,
    event_status text,
    entity_type text,
    program_short_name text,
    program_stage_name text,
    dim_eidsr_event_key text,
    dim_org_hierarchy_key text,
    dim_eidsr_program_key text,
    dim_eidsr_tracked_entity_instance_key text,
    dim_eidsr_program_stage_key text,
    enrolled integer,
    has_any_result integer,
    sample_received integer,
    covid_test_recorded integer,
    influenza_result_recorded integer,
    rsv_result_recorded integer,
    rsv_not_performed integer
);

--CREATE TABLE malaria.mv_malaria_deaths (
    year text,
    period text,
    tperiod text,
    month integer,
    quarter integer,
    region text,
    district text,
    facility text,
    age_group text,
    gender text,
    malaria_deaths numeric,
    malaria_confirmed_deaths numeric,
    malaria_pregnancy_deaths numeric,
    total_deaths_indicator numeric
);


--CREATE TABLE malaria.mv_iccm_dataset (
    region text,
    district text,
    period text,
    year text,
    quarter integer,
    iccm_partner text,
    iccm text,
    vhts_implementing_iccm numeric,
    vhts_expected_to_report numeric,
    villages_reporting numeric,
    children_seen_by_vht numeric,
    fever_cases_seen numeric,
    fever_cases_tested_rdt numeric,
    confirmed_malaria_cases numeric,
    act_treated_cases numeric,
    danger_sign_cases numeric,
    danger_sign_cases_given_ras numeric,
    referred_sick_children numeric,
    u5_deaths_lt_1_month numeric,
    u5_deaths_1_11_months numeric,
    u5_deaths_1_5_years numeric,
    u5_malaria_reported_deaths numeric,
    u5_malaria_admissions numeric
);


--CREATE TABLE report.mv_tb_case_notification (
    year text,
    quarter text,
    region text,
    district text,
    facility text,
    "Total" numeric,
    ptb_bc_cases integer,
    ptb_cd_cases integer,
    eptb_cases integer,
    total_tb_all_cases integer,
    total_tb_cases integer,
    estimated_tb_cases_raw numeric,
    health_workers integer,
    tb_contacts integer,
    refugees integer,
    prisoners integer,
    uniformed_personnel integer,
    fisher_folk integer,
    diabetic_patients integer,
    miners integer,
    tobacco_users integer,
    mentally_ill integer,
    incident_tb_cases_notified integer,
    estimated_tb_cases numeric,
    previously_treated_cases_excl_relapse numeric,
    pct_prev_treated_excl_relapse numeric,
    tb_case_detection_rate numeric,
    tb_case_notification_rate numeric,
    tb_treatment_coverage numeric,
    total_risk_groups integer,
    pct_refugees numeric,
    pct_prisoners numeric,
    pct_tb_contacts numeric,
    pct_uniformed_personnel numeric,
    pct_fisher_folk numeric,
    pct_diabetic_patients numeric,
    pct_miners numeric,
    pct_tobacco_users numeric,
    pct_mentally_ill numeric
);

--CREATE TABLE report.mv_dr_tb (
    year text,
    quarter text,
    month text,
    week text,
    region text,
    district text,
    tperiod text,
    "Estimated RR Cases" numeric,
    "RR TB Identified" integer,
    "TB Registered P-BC" integer,
    "TB Registered P-CD" integer,
    "TB Registered EPTB" integer,
    "Started 2nd Line Confirmed" integer,
    "Started 2nd Line Presumed" integer,
    "DR TB Started Female Confirmed" integer,
    "DR TB Started Female Presumed" integer,
    "DR TB Started Male Confirmed" integer,
    "DR TB Started Male Presumed" integer,
    "Started 2nd Line 0-14 Confirmed" integer,
    "Started 2nd Line 0-14 Presumed" integer,
    "Started 2nd Line 15+ Confirmed" integer,
    "Started 2nd Line 15+ Presumed" integer,
    "24mo Presumptive MDR-TB" integer,
    "24mo Confirmed RR" integer,
    "24mo XDR" integer,
    "Number of TB/HIV Co-infected RR/MDR TB cases registered 24 mont" integer,
    "24mo RR/MDR 0-14" integer,
    "24mo RR Cured Completed" integer,
    "24mo Presumptive Cured Completed" integer,
    "Number of X-DR TB cases registered 24 months ago that cured or " integer,
    "TB/HIV Co-infected RR/MDR TB cases 24mnths that cured/completed" integer,
    "24mo RR 0-14 Cured Completed" integer,
    "RR/MDR Detection Rate" numeric,
    "RR/MDR Started Second-line Treatment" integer,
    "Percent RR/MDR identified out of all notified" numeric,
    "RR/MDR Started second-line treatment Female" integer,
    "RR/MDR Started second-line treatment Male" integer,
    "RR_MDR_Started_second-line_treatment_0-14" integer,
    "RR_MDR_Started_second-line_treatment_15" integer,
    "No of RR/MDR Registered 24 months ago" integer,
    "No of RR/MDR Registered 24 months ago that Cured Completed" integer,
    "Percentage Treatment success rate for all RR/MDR-TB cases" numeric,
    "Number of X-DR TB cases registered 24 months ago" integer,
    "Percentage Treatment success rate for all confirmed X-DR TB cas" numeric,
    "24mo RR HIV+ Cured Completed Total" integer,
    "Percent RR/HIV+ Treatment Success" numeric,
    "24mo RR 0-14 Cured Completed Total" integer,
    "Percent RR/MDR children 0-14 Treatment Success" numeric,
    "24mo Presumptive Cured Completed Total" integer,
    "Percent Presumptive MDR Treatment Success" numeric,
    "Percent Lab Confirmed Starting Treatment" numeric,
    "Percent RR/MDR Treatment Success 2" numeric,
    last_refresh_date timestamp
);

--CREATE TABLE report.mv_ppm (
    year text,
    week text,
    month text,
    quarter text,
    district text,
    region text,
    facility text,
    ownership text,
    tperiod text,
    total_facility_attendance numeric,
    screened_total numeric,
    pct_screened numeric,
    presumptive_total numeric,
    pct_presumptive numeric,
    tb_diagnosed numeric,
    tb_yield_pct numeric,
    incident_tb_cases numeric,
    tb_case_detection_rate numeric,
    treatment_success_rate_all_ds_tb numeric,
    cure_rate_new_pbc_tb numeric,
    last_refresh_date timestamp
);


--CREATE TABLE report.mv_tb_screening (
    year text,
    quarter text,
    month text,
    week text,
    region text,
    district text,
    facility text,
    tperiod text,
    anc_total_contacts integer,
    art_1st_line integer,
    art_2nd_line integer,
    art_3rd_line integer,
    ipd_admissions integer,
    opd_new_monthly integer,
    opd_new_attendance integer,
    anc_screened integer,
    opd_screened integer,
    art_screened integer,
    ipd_screened integer,
    opd_presumptive integer,
    ipd_presumptive integer,
    anc_presumptive integer,
    art_presumptive integer,
    opd_diagnosed integer,
    ipd_diagnosed integer,
    anc_diagnosed integer,
    art_diagnosed integer,
    tb_treated_pbc integer,
    tb_treated_pcd integer,
    tb_treated_eptb integer,
    total_hf_attendance bigint,
    total_screened_for_tb integer,
    percent_total_screened numeric,
    total_presumptive_cases integer,
    total_tb_cases_diagnosed integer,
    percent_tb_yield_total numeric,
    total_started_treatment integer,
    percent_diagnosed_started_treatment numeric,
    opd_total_attendance bigint,
    percent_opd_screened numeric,
    percent_opd_presumptive numeric,
    percent_opd_tb_yield numeric,
    art_total_attendance bigint,
    percent_art_screened numeric,
    percent_art_presumptive numeric,
    percent_art_tb_yield numeric,
    percent_ipd_screened numeric,
    percent_ipd_presumptive numeric,
    percent_ipd_tb_yield numeric,
    percent_anc_screened numeric,
    percent_anc_presumptive numeric,
    percent_anc_tb_yield numeric,
    percent_presumptive_of_screened numeric,
    last_refresh_date timestamp
);

--CREATE TABLE report.mv_tb_elements_new (
    year text,
    week text,
    month text,
    quarter text,
    category_combo text,
    district text,
    region text,
    facility text,
    tperiod text,
    popn_est_total numeric,
    popn_est_male numeric,
    popn_est_female numeric,
    opd_new integer,
    screened integer,
    diagnosed integer,
    presumed integer,
    rr_tb_cases integer,
    rr_tb_deaths integer,
    leprosy_cases integer,
    leprosy_deaths integer,
    genxpert integer,
    dst_denominator integer,
    new_and_relapse integer,
    opd_new_monthly integer,
    screened_opd integer,
    pre_diagnosed_tb_opd integer,
    presumed_opd integer,
    screened_art integer,
    diagnosed_art integer,
    presumed_art integer,
    screened_outreaches integer,
    diagnosed_outreaches integer,
    presumed_outreaches integer,
    screened_leprosy integer,
    diagnosed_leprosy integer,
    presumed_leprosy integer,
    mortality integer,
    admissions integer,
    g2d_cases integer,
    new_and_relapse_tb integer,
    new_and_relapse_leprosy_pb integer,
    new_and_relapse_leprosy_mb integer,
    specialized_opd_re_attendance integer,
    opd_re_attendance integer,
    opd_new_attendance integer,
    total_opd integer,
    presumptive_tb_quarterly integer,
    tested_with_genexpert integer,
    accessed_genexpert_quarter integer,
    bacteriologically_confirmed_quarter integer,
    presumed_contacts integer,
    diagnosed_contacts integer,
    contacts_screened integer,
    contacts_linelisted integer,
    dr_tb_notifications integer,
    paediatric_incident_cases numeric,
    estimated_paediatric_cases numeric,
    new_relapse_leprosy integer,
    childhood_leprosy_cases numeric,
    eligible_art_clients integer,
    art_clients_started_on_tpt integer,
    under_5_contacts_eligible_tpt integer,
    over_5_contacts_eligible_tpt integer,
    over_5_contacts_started_tpt integer,
    case_not_per_100k_quarter numeric,
    last_refresh_date timestamp
);



--CREATE TABLE report.mv_tb_elements_wide (
    year text,
    week text,
    month text,
    quarter text,
    category_combo text,
    district text,
    region text,
    facility text,
    tperiod text,
    popn_est_total numeric,
    popn_est_male numeric,
    popn_est_female numeric,
    opd_new integer,
    screened integer,
    diagnosed integer,
    presumed integer,
    rr_tb_cases integer,
    rr_tb_deaths integer,
    leprosy_cases integer,
    leprosy_deaths integer,
    genxpert integer,
    dst_denominator integer,
    new_and_relapse integer,
    opd_new_monthly integer,
    screened_opd integer,
    pre_diagnosed_tb_opd integer,
    presumed_opd integer,
    screened_art integer,
    diagnosed_art integer,
    presumed_art integer,
    screened_outreaches integer,
    diagnosed_outreaches integer,
    presumed_outreaches integer,
    screened_leprosy integer,
    diagnosed_leprosy integer,
    presumed_leprosy integer,
    mortality integer,
    admissions integer,
    g2d_cases integer,
    new_and_relapse_tb integer,
    new_and_relapse_leprosy_pb integer,
    new_and_relapse_leprosy_mb integer,
    specialized_opd_re_attendance integer,
    opd_re_attendance integer,
    opd_new_attendance integer,
    total_opd integer,
    presumptive_tb_quarterly integer,
    tested_with_genexpert integer,
    accessed_genexpert_quarter integer,
    bacteriologically_confirmed_quarter integer,
    presumed_contacts integer,
    diagnosed_contacts integer,
    contacts_screened integer,
    contacts_linelisted integer,
    dr_tb_notifications integer,
    paediatric_incident_cases numeric,
    estimated_paediatric_cases numeric,
    new_relapse_leprosy integer,
    childhood_leprosy_cases numeric,
    eligible_art_clients integer,
    art_clients_started_on_tpt integer,
    under_5_contacts_eligible_tpt integer,
    over_5_contacts_eligible_tpt integer,
    over_5_contacts_started_tpt integer,
    case_not_per_100k_quarter numeric,
    last_refresh_date timestamp
);

--CREATE TABLE report.mv_tb_treatment_outcomes (
    year text,
    quarter text,
    month text,
    week text,
    region text,
    district text,
    facility text,
    tperiod text,
    category_combo text,
    pbc_patients_reported integer,
    pcd_patients_reported integer,
    eptb_patients_reported integer,
    after_lfu_patients_reported integer,
    history_unknown_patients_reported integer,
    pbc_transferred_2nd_line integer,
    pcd_transferred_2nd_line integer,
    eptb_transferred_2nd_line integer,
    after_lfu_transferred_2nd_line integer,
    history_unknown_transferred_2nd_line integer,
    pbc_cured integer,
    pbc_completed integer,
    pbc_ltfp integer,
    pbc_failed integer,
    pbc_died integer,
    total_pbc_tested_end_intensive_phase integer,
    pcd_cured integer,
    pcd_completed integer,
    pcd_ltfp integer,
    pcd_failed integer,
    pcd_died integer,
    eptb_cured integer,
    eptb_completed integer,
    eptb_ltfp integer,
    eptb_failed integer,
    eptb_died integer,
    after_lfu_cured integer,
    after_lfu_completed integer,
    after_lfu_ltfp integer,
    after_lfu_failed integer,
    after_lfu_died integer,
    unknown_cured integer,
    unknown_completed integer,
    unknown_ltfp integer,
    unknown_failed integer,
    unknown_died integer,
    hiv_positive_cured integer,
    hiv_positive_completed integer,
    hiv_positive_patients_reported integer,
    hiv_positive_transferred_2nd_line integer,
    children_cured integer,
    children_completed integer,
    children_patients_reported integer,
    children_transferred_2nd_line integer,
    hiv_children_cured integer,
    hiv_children_completed integer,
    hiv_children_patients_reported integer,
    hiv_children_transferred_2nd_line integer,
    sputum_negative integer,
    sputum_total_tested integer,
    bacteriologically_confirmed_previous_quarter integer,
    total_cohort integer,
    ds_tb_successful_outcomes integer,
    pbc_total_cohort integer,
    ltfp_outcomes integer,
    failed_outcomes integer,
    died_outcomes integer,
    transferred_2nd_line_total integer,
    hiv_positive_total_cohort integer,
    hiv_positive_successful_outcomes integer,
    children_total_cohort integer,
    children_successful_outcomes integer,
    hiv_children_total_cohort integer,
    hiv_children_successful_outcomes integer,
    ds_tb_treatment_success_rate numeric,
    pbc_cure_rate numeric,
    pct_lost_to_follow_up numeric,
    pct_failed numeric,
    pct_died numeric,
    pct_transferred_2nd_line numeric,
    hiv_positive_treatment_success_rate numeric,
    children_treatment_success_rate numeric,
    hiv_children_treatment_success_rate numeric,
    pct_tested_end_intensive numeric,
    sputum_conversion_rate numeric,
    last_refresh_date timestamp
);

--CREATE TABLE report.mv_tb_weekly_status (
    year text,
    week text,
    month text,
    quarter text,
    region text,
    district text,
    facility text,
    tperiod text,
    total_opd integer,
    clients_screened_tb integer,
    pct_screened numeric,
    presumptive_tb integer,
    pct_presumptive numeric,
    new_relapse_diagnosed integer,
    bacteriologically_confirmed integer,
    bc_tested_genexpert integer,
    pct_bc_tested_genexpert numeric,
    rr_tb_detected integer,
    contacts_traced_screened integer,
    leprosy_cases integer,
    genexpert_samples integer,
    mtb_detected integer,
    pct_mtb_detected numeric,
    pct_rr_detected numeric,
    genexpert_errors integer,
    pct_errors numeric,
    samples_rejected integer,
    last_refresh_date timestamp
);

--CREATE TABLE report.mv_tb_lab (
    year text,
    quarter text,
    region text,
    district text,
    "presumptive tb case finding" integer,
    "presumptive tb identified" integer,
    "presumptive microscopy" integer,
    "bacteriologically confirmed tb" integer,
    "bacteriologically confirmed ptb" integer,
    wrd_tests_conducted integer,
    mtb_total integer,
    rr_wrd_tests integer,
    "Smear microscopy tests conducted" integer,
    "Sputum culture tests" integer,
    "WRD tests conducted (GeneXpert + Truenat)" integer,
    "GeneXpert tests referred" integer,
    "Percentage of presumptive TB cases that accessed genexpert" numeric,
    "Percentage of presumptive TB cases that accessed a microscopy t" numeric,
    "Percentage of P-BCs tested using GeneXpert" numeric,
    "Percentage of GeneXpert tests referred" numeric,
    last_refresh_date timestamp
);

--CREATE TABLE report.mv_tb_paediatrics (
    year text,
    region text,
    district text,
    quarter text,
    pediatric_incident_cases integer,
    pediatric_estimated_cases integer,
    treatment_success_count integer,
    total_registered_patients integer,
    treatment_coverage_percent numeric,
    treatment_success_rate_percent numeric
);


--CREATE TABLE report.mv_leprosy (
    year text,
    week text,
    month text,
    quarter text,
    category_combo text,
    district text,
    region text,
    facility text,
    tperiod text,
    popn_est_total numeric,
    popn_est_male numeric,
    popn_est_female numeric,
    "New leprosy cases registered" integer,
    "Relapse cases registered" integer,
    "Child leprosy cases" integer,
    "Female leprosy cases" integer,
    "Grade 2 disability cases" integer,
    "Proportion of child new cases (%)" numeric,
    "Proportion of female new cases (%)" numeric,
    "Total MB cases" integer,
    "Proportion of grade 2 cases (%)" numeric,
    last_refresh_date timestamp
);


--CREATE TABLE report.mv_palliative_care (
    year text,
    month text,
    monthname text,
    district text,
    region text,
    facility text,
    "Cancer" integer,
    "HIV" integer,
    "Other" integer,
    "Patients Needing" integer,
    "New Received" integer,
    "Total Received" integer,
    "Died" integer,
    "Working (Adults)" integer,
    "Playing (Children)" integer,
    "Ambulant" integer,
    "Bedridden" integer,
    "No pain (0/10)" integer,
    "Mild pain (1/10-2/10)" integer,
    "Moderate pain (3/10-4/10)" integer,
    "Severe pain (5/10-6/10)" integer,
    "Very Severe pain (7/10-8/10)" integer,
    "Worst pain possible (9/10-10/10)" integer
);

--CREATE TABLE report.mv_tbh_coinfection (
    year text,
    quarter text,
    month text,
    week text,
    region text,
    district text,
    facility text,
    tperiod text,
    tb_reg_pbc integer,
    tb_reg_pcd integer,
    tb_reg_eptb integer,
    tb_new_relapse_tested_hiv integer,
    tb_known_hiv_positive integer,
    tb_newly_diagnosed_hiv integer,
    tb_new_hiv_started_art integer,
    tb_known_hiv_on_art integer,
    tb_total_tested_hiv integer,
    art_1st_line integer,
    art_2nd_line integer,
    art_3rd_line integer,
    art_screened_for_tb integer,
    art_presumptive_tb integer,
    art_diagnosed_tb integer,
    art_started_tb_treatment integer,
    presumptive_tb_cases integer,
    presumptive_tested_hiv integer,
    "Percent TB cases tested for HIV" numeric,
    "Percent HIV positive TB cases registered" numeric,
    "Percent HIV positive TB cases on ART" numeric,
    "ART attendance" integer,
    "ART clients screened TB" integer,
    "TB/HIV started TB treatment" integer,
    "Percent TB/HIV started TB treatment" numeric,
    "Percent new relapse TB tested HIV" numeric,
    "Percent new relapse HIV positive" numeric,
    "Percent presumptive tested HIV" numeric,
    "Percent ART clients screened TB" numeric,
    "Percent ART presumptive TB" numeric,
    "Percent ART TB yield" numeric,
    last_refresh_date timestamp
);



--CREATE TABLE report.mv_acf (
    year text,
    quarter text,
    month text,
    week text,
    region text,
    district text,
    facility text,
    tperiod text,
    opd_attendance integer,
    clients_screened_tb integer,
    total_opd_attendance integer,
    presumptive_tb integer,
    new_relapse_tb integer,
    rr_tb integer,
    bacteriologically_confirmed_genexpert integer,
    bacteriologically_confirmed_cases integer,
    "Percent weekly attendance screened for TB" numeric,
    "Percent of presumptives identified" numeric,
    "Percent of bacteriologically confirmed cases tested with genexp" numeric,
    last_refresh_date timestamp
);

--CREATE TABLE report.mv_tpt_weekly (
    year text,
    week text,
    quarter text,
    month text,
    region text,
    district text,
    facility text,
    children_0_4_contacts_tpt integer,
    adults_art_clients_tpt integer,
    children_adolescents_tpt integer,
    last_refresh_date timestamp
);

--CREATE TABLE report.mv_tb_data_elements (
    year text,
    week text,
    month text,
    quarter text,
    category_combo text,
    district text,
    region text,
    facility text,
    tperiod text,
    popn_est_total numeric,
    popn_est_male numeric,
    popn_est_female numeric,
    opd_new integer,
    screened integer,
    diagnosed integer,
    presumed integer,
    rr_tb_cases integer,
    rr_tb_deaths integer,
    leprosy_cases integer,
    leprosy_deaths integer,
    genxpert integer,
    dst_denominator integer,
    new_and_relapse integer,
    opd_new_monthly integer,
    screened_opd integer,
    pre_diagnosed_tb_opd integer,
    presumed_opd integer,
    screened_art integer,
    diagnosed_art integer,
    presumed_art integer,
    screened_outreaches integer,
    diagnosed_outreaches integer,
    presumed_outreaches integer,
    screened_leprosy integer,
    diagnosed_leprosy integer,
    presumed_leprosy integer,
    mortality integer,
    admissions integer,
    g2d_cases integer,
    new_and_relapse_tb integer,
    new_and_relapse_leprosy_pb integer,
    new_and_relapse_leprosy_mb integer,
    specialized_opd_re_attendance integer,
    opd_re_attendance integer,
    opd_new_attendance integer,
    total_opd integer,
    presumptive_tb_quarterly integer,
    tested_with_genexpert integer,
    accessed_genexpert_quarter integer,
    bacteriologically_confirmed_quarter integer,
    presumed_contacts integer,
    diagnosed_contacts integer,
    contacts_screened integer,
    contacts_linelisted integer,
    dr_tb_notifications integer,
    paediatric_incident_cases numeric,
    estimated_paediatric_cases numeric,
    new_relapse_leprosy integer,
    childhood_leprosy_cases numeric,
    eligible_art_clients integer,
    art_clients_started_on_tpt integer,
    under_5_contacts_eligible_tpt integer,
    over_5_contacts_eligible_tpt integer,
    over_5_contacts_started_tpt integer,
    percent_screened numeric,
    percent_diagnosed numeric,
    percent_presumed numeric,
    cases_per_100k numeric,
    last_refresh_date timestamp
);

--CREATE TABLE report.mv_epi_dataelements (
    year integer,
    month integer,
    monthname text,
    quarter integer,
    district text,
    region text,
    bcg numeric,
    bcg_coverage numeric,
    hep0 numeric,
    hep0_coverage numeric,
    td_pab numeric,
    td_pad_coverage numeric,
    polio0 numeric,
    polio0_coverage numeric,
    polio1 numeric,
    polio1_coverage numeric,
    polio2 numeric,
    polio2_coverage numeric,
    polio3 numeric,
    polio3_coverage numeric,
    ipv1 numeric,
    ipv1_coverage numeric,
    ipv2 numeric,
    ipv2_coverage numeric,
    dpt1 numeric,
    dpt1_coverage numeric,
    dpt2 numeric,
    dpt2_coverage numeric,
    dpt3 numeric,
    dpt3_coverage numeric,
    pcv1 numeric,
    pcv1_coverage numeric,
    pcv2 numeric,
    pcv2_coverage numeric,
    pcv3 numeric,
    pcv3_coverage numeric,
    rota1 numeric,
    rota1_coverage numeric,
    rota2 numeric,
    rota2_coverage numeric,
    rota3 numeric,
    rota3_coverage numeric,
    mr1 numeric,
    mr1_coverage numeric,
    mr2 numeric,
    mr2_coverage numeric,
    fully_immunized numeric,
    fully_immunized_coverage numeric,
    hpv1 numeric,
    hpv2 numeric,
    bcg_mr1_dropout numeric,
    dpt1_dpt3_dropout numeric,
    mr1_mr2_droput numeric,
    dpt3_mr1_dropout numeric,
    hpv1_hpv2_dropout numeric,
    pcv1_pcv3_dropout numeric,
    rv1_rv2_dropout numeric
);


--CREATE TABLE report.mv_clinical_services_combo (
    record_id text,
    record_sync_date timestamp,
    facility text,
    level text,
    region text,
    district text,
    sub_county text,
    org_unit_id text,
    dataset_id text,
    data_element_id text,
    dataset text,
    dataelement text,
    value text,
    period text,
    year integer,
    month integer,
    monthname text,
    quarter integer,
    week integer,
    tperiod text,
    category_combo text,
    dim_org_hierarchy_key text,
    dim_org_hierarchy_current_key text,
    dataset_key text,
    dim_data_element_map_key text,
    dim_data_element_map_current_key text,
    dim_category_attribute_option_key text,
    last_updated_date timestamp
);


--CREATE TABLE report.mv_clinical_services (
    year integer,
    month integer,
    monthname text,
    district text,
    region text,
    "Un Operable Cataract (>6/60)" integer,
    "Operable Cataract (<6/60)" integer,
    "Cataracts  - Cases" integer,
    total_cases integer,
    total_fistul_cases numeric,
    fistula_cases_coverage_per_10000 numeric,
    cataracts_coverage_per_10000 numeric,
    dental_cases integer,
    dental_deaths integer,
    dental_cases_per_100000 numeric,
    "Tooth extractions" integer,
    "Dental Fillings" integer,
    "Other Minor Operations" integer,
    total_eye_conditions integer,
    eye_cases_coverage_per_10000 numeric,
    "Sickle Cell Tests - Done" integer,
    "Sickle Cell Tests - Positive" integer,
    "Sickle Cell Disease" integer,
    "Number of Sickle Cell patients that need palliative care" integer,
    "Number of new Sickle Cell patients that received palliative car" integer,
    "Number of Sickle Cell patients that received palliative care" integer,
    "Sickle Cell Disease Confirmation - Samples Referred" integer,
    "Sickle Cell Disease Confirmation - Pending Results/Feedback" integer,
    "Sickle cell disease  - Cases" integer,
    "Sickle cell disease  - Deaths" integer,
    sickle_cell_cases_per_100000 numeric,
    sickle_cell_disease_per_100000 numeric
);



--CREATE TABLE report.mv_surgeries (
    year integer,
    month integer,
    monthname text,
    district text,
    region text,
    total_surgical_cases integer,
    coverage_per_10000 numeric,
    csections_per_10000 numeric
);


--CREATE TABLE report.mv_monthly_stock_analysis_raw (
    "national" text,
    region text,
    district text,
    subcounty text,
    facility text,
    facilityid text,
    period text,
    period_display text,
    commodities text,
    consumed numeric,
    days_out_of_stock numeric,
    stock_available integer,
    out_of_stock integer,
    stock_on_hand numeric,
    expired numeric,
    expired_commodity_cost numeric,
    expired_emhs1_cost numeric,
    expired_emhs2_cost numeric,
    expired_arv_cost numeric,
    expired_tb_cost numeric,
    expired_rmncah_cost numeric,
    expired_lab_cost numeric,
    expired_unknown_basket_cost numeric,
    date date,
    daysinmonth integer,
    region_uid text,
    district_uid text,
    subcounty_uid text,
    facility_type text,
    hflevel text,
    ownership text,
    facility_status text,
    basket text,
    programme text,
    commodity_code text,
    basket_order integer,
    year integer,
    month integer,
    unit text,
    unit_cost numeric,
    availability numeric,
    emhs1_availability numeric,
    emhs2_availability numeric,
    arv_availability numeric,
    tb_availability numeric,
    rmncah_availability numeric,
    lab_availability numeric,
    unknown_basket_availability numeric,
    availability_percent numeric,
    emhs1_availability_percent numeric,
    emhs2_availability_percent numeric,
    arv_availability_percent numeric,
    tb_availability_percent numeric,
    rmncah_availability_percent numeric,
    lab_availability_percent numeric,
    unknown_basket_availability_percent numeric,
    adjusted_days_out_of_stock numeric,
    amc numeric,
    months_of_stock numeric,
    mos_order integer,
    stock_status text,
    status_out_of_stock integer,
    status_under_stocked integer,
    status_appropriately_stocked integer,
    status_over_stocked integer
);

--CREATE TABLE report.mv_monthly_stock_analysis_aggregate (
    facilityid text,
    facility text,
    region text,
    region_uid text,
    ownership text,
    district text,
    district_uid text,
    hflevel text,
    availability numeric,
    total_commodities integer,
    submission_completeness integer,
    total_submissions bigint,
    has_submitted integer,
    basket text,
    period text,
    year integer,
    month integer
);

--CREATE TABLE report.mv_amr_rx_audit_visit (
    key_uuid text,
    submission_date date,
    date_of_audit date,
    prescription_date date,
    audit_year integer,
    audit_month integer,
    audit_day integer,
    audit_quarter integer,
    region text,
    district text,
    subcounty text,
    facility text,
    ownership text,
    level_of_care text,
    sex text,
    age_in_years numeric,
    age_in_months numeric,
    infant_or_not text,
    antibiotics_count integer,
    antibiotics_distinct_count integer,
    antimicrobials_count integer,
    by_generic_name_count integer,
    adherent_to_guideline integer,
    oral_count integer,
    injectable_count integer,
    watch_count integer,
    access_count integer,
    reserve_count integer,
    unclassified_count integer,
    male_flag integer,
    female_flag integer,
    patient_on_antimicrobial_flag boolean,
    adherent_any_flag boolean,
    adherent_all_flag boolean,
    biomarker_records integer
);



CREATE MATERIALIZED VIEW report.mv_amr_prescription_audit_clean AS  SELECT key_uuid,
    sex,
    edits,
    status,
    regexp_replace(COALESCE(region, ''::text), '_+'::text, ' '::text, 'g'::text) AS region,
    device_id,
    regexp_replace(COALESCE(district, ''::text), '_+'::text, ' '::text, 'g'::text) AS district,
    regexp_replace(COALESCE(facility, ''::text), '_+'::text, ' '::text, 'g'::text) AS facility,
    rand_num,
    ownership,
    show_code,
    regexp_replace(COALESCE(subcounty, ''::text), '_+'::text, ' '::text, 'g'::text) AS subcounty,
    form_version,
    review_state,
    submitter_id,
    age_in_years,
    patient_code,
    date_of_audit,
    (date_part('year'::text, to_date(date_of_audit, 'YYYY-MM-DD'::text)))::integer AS audit_year,
    (date_part('month'::text, to_date(date_of_audit, 'YYYY-MM-DD'::text)))::integer AS audit_month,
    (date_part('day'::text, to_date(date_of_audit, 'YYYY-MM-DD'::text)))::integer AS audit_day,
    (date_part('quarter'::text, to_date(date_of_audit, 'YYYY-MM-DD'::text)))::integer AS audit_quarter,
    submitter_name,
    age_in_months,
    infant_or_not,
    level_of_care,
    submission_date,
    patient_initials,
    prescription_date,
    attachments_present,
    attachments_expected,
    medicines_prescribed,
    specify_other_medicines,
    patient_on_antimicrobial,
    antibiotic,
    other_antibiotics,
    antibiotic_class,
    antibiotic_aware_classification,
    atc_code,
    antimicrobial,
    route,
    frequency_per_day,
    dose_duration_days,
    single_unit_strength,
    single_unit_dose_unit,
    total_daily_dose,
    adherent_to_guideline,
    by_generic_name,
    which_biomarker,
    biological_sample_type,
    treatment_based_on_biomarker,
    diagnosis,
    category_of_diagnosis
   FROM report.amr_prescription_audit a
  WHERE (NULLIF(btrim(antimicrobial), ''::text) IS NOT NULL);


--CREATE TABLE report.mv_nutrition_hmis_elements_v3 (
    composite_group_id text,
    region text,
    district text,
    period text,
    year integer,
    quarter integer,
    month integer,
    monthname text,
    qtr integer,
    month_year text,
    week integer,
    tperiod text,
    category_combo text,
    total_assessed_nutrition_status integer,
    nut_assnt_muac_2019 integer,
    total_assessed_nutrition_status_male integer);



--CREATE TABLE report.mv_disability_elements_data_2 (
    -- Location and Metadata
    region TEXT,
    district TEXT,
    subcounty TEXT,
    facility TEXT,
    category TEXT,
    year INTEGER,
    month INTEGER,
    period TEXT,
    monthname TEXT,
    month_year TEXT,
    quarter TEXT,
    quarter_year TEXT,
    report_date DATE,
    facility_type TEXT,

    -- Individual Disability Elements (Pivoted)
    "105-DF01. Intellectual lmpairment" INTEGER DEFAULT 0,
    "105-DF02. Cognitive Impairement" INTEGER DEFAULT 0,
    "105-DF03. Visual Impairment" INTEGER DEFAULT 0,
    "105-DF04. Hearing Impairment" INTEGER DEFAULT 0,
    "105-DF05. Vestibular Impairment" INTEGER DEFAULT 0,
    "105-DF06. Speech Impairment" INTEGER DEFAULT 0,
    "105-DF07. Phonation Impairment" INTEGER DEFAULT 0,
    "105-DF08. Articulation Impairment" INTEGER DEFAULT 0,
    "105-DF09. Alternative Vocalisation Impairment" INTEGER DEFAULT 0,
    "105-DF10. Chewing Impairment" INTEGER DEFAULT 0,
    "105-DF11. Swallowing Impairment" INTEGER DEFAULT 0,
    "105-DF12. Defecation Impairment" INTEGER DEFAULT 0,
    "105-DF13. Diffculty in Urination" INTEGER DEFAULT 0,
    "105-DF14. Impaired Joint Mobility" INTEGER DEFAULT 0,
    "105-DF15. Impaired Muscle power" INTEGER DEFAULT 0,
    "105-DF16. Impaired Muscle tone" INTEGER DEFAULT 0,
    "105-DF17. Involuntary body movements" INTEGER DEFAULT 0,
    "105-DF18. Impaired Protective function of the skin" INTEGER DEFAULT 0,
    "105-DF19. Difficulty in Lifting and carrying objects" INTEGER DEFAULT 0,
    "105-DF20. Impaired fine hand use (picking up, grasping)" INTEGER DEFAULT 0,
    "105-DF21. Posture (changing body basic position) difficulties" INTEGER DEFAULT 0,
    "105-DF22. Difficulty in Walking" INTEGER DEFAULT 0,

    -- Assistive Products & Conditions
    "105-AP01. Mobility" INTEGER DEFAULT 0,
    "105-AP02. Hearing" INTEGER DEFAULT 0,
    "105-AP03. Vision" INTEGER DEFAULT 0,
    "105-AP04. Communication" INTEGER DEFAULT 0,
    "105-AP05. Cognition" INTEGER DEFAULT 0,
    "105-AP06. Self-care" INTEGER DEFAULT 0,
    "105-AP07. Other APs" INTEGER DEFAULT 0,
    "105-RE01: Cancers" INTEGER DEFAULT 0,
    "105-RE02: Cardiovascular" INTEGER DEFAULT 0,
    "105-RE03: Mental" INTEGER DEFAULT 0,
    "105-RE04: Musculoskeletal" INTEGER DEFAULT 0,
    "105-RE05: Neurological" INTEGER DEFAULT 0,
    "105-RE06: Respiratory" INTEGER DEFAULT 0,
    "105-RE07: Sensory" INTEGER DEFAULT 0,
    "105-RE08: Other conditions" INTEGER DEFAULT 0,

    -- Referrals & Rehabilitation
    "105-RR01. Rehabilitation Referral" INTEGER DEFAULT 0,
    "105-RR02. Referral for AP" INTEGER DEFAULT 0,
    "105-RR03. Referral for rehabilitation services" INTEGER DEFAULT 0,
    "105-RU01: Cancers" INTEGER DEFAULT 0,
    "105-RU02: Cardiovascular" INTEGER DEFAULT 0,
    "105-RU03: Mental" INTEGER DEFAULT 0,
    "105-RU04: Musculoskeletal" INTEGER DEFAULT 0,
    "105-RU05: Neurological" INTEGER DEFAULT 0,
    "105-RU06: Respiratory" INTEGER DEFAULT 0,
    "105-RU07: Sensory" INTEGER DEFAULT 0,
    "105-RU08: Other conditions" INTEGER DEFAULT 0,

    -- HMIS 108 Elements
    "108-AC05. Stroke" INTEGER DEFAULT 0,
    "108-AC01. Spinal Cord Injury (SCI)" INTEGER DEFAULT 0,
    "108-AC02. Traumatic Brain Injury (TBI)" INTEGER DEFAULT 0,
    "108-AC03. Amputation" INTEGER DEFAULT 0,
    "108-AC04. Burns" INTEGER DEFAULT 0,
    
    -- Calculated Totals
    "Disability" INTEGER,
    "Rehabilitation Uptake" INTEGER,
    "Rehabilitation Utilization" INTEGER,
    "Assistive Products" INTEGER,
    "Rehabilitation Referrals" INTEGER,
    "OPD Rehab Utilization" INTEGER,
    
    -- Constraint (Optional but recommended)
    PRIMARY KEY (facility, year, month, category)
);

--CREATE TABLE cht.mv_community_death_notification (
    uuid TEXT,
    form TEXT,
    submitter TEXT,
    reported TIMESTAMP,
    date DATE,
    year INTEGER,
    month INTEGER,
    monthname TEXT,
    instanceid TEXT,
    deprecatedid TEXT,
    location_lat TEXT,
    location_long TEXT,
    location_error TEXT,
    location_message TEXT,
    geolocation_code TEXT,
    geolocation_message TEXT,
    chw_id TEXT,
    chw_name TEXT,
    phone TEXT,
    role TEXT,
    contact_chw_area_id TEXT,
    facility_id TEXT,
    district TEXT,
    region TEXT,
    source TEXT,
    source_id TEXT,
    contact_id TEXT,
    contact_name TEXT,
    contact_date_of_birth TEXT,
    head_household_name TEXT,
    head_household_contact TEXT,
    mother_name TEXT,
    mother_dob TEXT,
    mother_age TEXT,
    mother_pregnanies TEXT,
    mother_village TEXT,
    woman_parish TEXT,
    woman_subcounty TEXT,
    woman_district TEXT,
    woman_usual_residence TEXT,
    woman_temporary_village TEXT,
    woman_temporary_parish TEXT,
    woman_temporary_subcounty TEXT,
    woman_temporary_district TEXT,
    informer_name TEXT,
    informer_contact TEXT,
    death_category TEXT,
    mother_death_timing TEXT,
    woman_nationality TEXT,
    mother_date_of_death TEXT,
    mother_time_of_death TEXT,
    maternal_death_weeks TEXT,
    mother_days_after_delivery TEXT,
    mother_place_of_death TEXT,
    maternal_death_place TEXT,
    mother_cause_of_death TEXT,
    carer_for_mother_before_death TEXT,
    carer_relationship_to_mother TEXT,
    carer_contact TEXT,
    baby_place_of_birth TEXT,
    baby_sex TEXT,
    baby_birth_date TEXT,
    baby_birth_time TEXT,
    baby_death_date TEXT,
    baby_death_time TEXT,
    neonatal_death_24 TEXT,
    neonatal_age_hours TEXT,
    neonatal_death_age_days TEXT,
    baby_place_of_death TEXT,
    neonatal_death_place TEXT,
    neonatal_death_cause TEXT,
    neonate_with_mother TEXT,
    neonate_with_carer TEXT,
    neonate_with_carer_contact TEXT,
    baby_multiple_pregnancy TEXT,
    baby_multiple_howmany TEXT,
    neonatal_other_death TEXT,
    other_babies_alive TEXT,
    still_birth_date TEXT,
    still_birth_time TEXT,
    still_birth_sex TEXT,
    still_birth_place TEXT,
    still_birth_place_spec TEXT,
    comment TEXT,
    last_refresh_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--CREATE TABLE report.mv_performance_indicators_v2 (
    reporting_period TEXT,
    year INTEGER,
    quarter INTEGER,
    org_unit_id TEXT,
    org_unit_name TEXT,
    region TEXT,
    district TEXT,
    facility_name TEXT,
    indicator_no INTEGER,
    indicator_name TEXT,
    numerator NUMERIC,
    denominator NUMERIC,
    performance NUMERIC,
    achieved_payment_scale INTEGER,
    achieved_payment_amount NUMERIC,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--CREATE TABLE report.mv_performance_raw (
    fact_hmis_key BIGINT, -- Adjust to MATCH your dwh.fact_hmis primary key type
    data_value NUMERIC,
    time_period TEXT,
    is_current BOOLEAN,
    org_unit_id TEXT,
    org_unit_name TEXT,
    region TEXT,
    district TEXT,
    facility_name TEXT,
    data_element_id TEXT,
    data_element_long_name TEXT,
    category_option_combo TEXT,
    year INTEGER,
    period_raw TEXT,
    quarter INTEGER,
    reporting_period TEXT,
    year2 INTEGER,
    quarter_prev2 INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--CREATE TABLE report.mv_097b_data_updated (
    -- Location & Metadata
    region TEXT,
    district TEXT,
    district_norm TEXT,
    subcounty TEXT,
    "Health Facility" TEXT,
    category TEXT,
    period TEXT,
    year INTEGER,
    month INTEGER,
    monthname TEXT,
    month_year TEXT,
    date DATE,
    facility_type TEXT,

    -- Community Health Indicators (Pivoted)
    "097b-IC01_Sick_children_seen" INTEGER,
    "097b-IC02_Diarrhoea" INTEGER,
    "097b-IC03_ORS_Zinc" INTEGER,
    "097b-IC04_Diarrhoea_24hrs" INTEGER,
    "097b-IC04_Fever" INTEGER,
    "097b-IC05_Fever_RDT" INTEGER,
    "097b-IC06_Malaria_confirmed" INTEGER,
    "097b-IC07_ACT_given" INTEGER,
    "097b-IC08_Fever_danger_signs" INTEGER,
    "097b-IC09_Rectal_artesunate" INTEGER,
    "097b-IC10_Pneumonia" INTEGER,
    "097b-IC11_Fever_24hrs" INTEGER,
    "097b-IC11_Pneumonia_Amox" INTEGER,
    "097b-IC12_Newborn_visited" INTEGER,
    "097b-IC13_Referred" INTEGER,
    "097b-IC14_Pneumonia_24hrs" INTEGER,
    "097b-IC15_Recovered" INTEGER,
    "097b-IC16_HIV_exposed" INTEGER,
    "097b-IC17_Suspected_TB" INTEGER,
    "097b-IC20_Malnutrition_assessed" INTEGER,
    "097b-IC22_PLW_Undernutrition" INTEGER,
    "097b-IC24_Oedema_assessed" INTEGER,

    -- VHT Stockouts
    "097b-SS01_VHT_ACT_stockout" INTEGER,
    "097b-SS02_VHT_Amox_stockout" INTEGER,
    "097b-SS03_VHT_ORS_Zinc_stockout" INTEGER,
    "097b-SS04_VHT_DMPA_stockout" INTEGER,
    "097b-SS05_VHT_COC_stockout" INTEGER,
    "097b-SS06_VHT_POP_stockout" INTEGER,
    "097b-SS07_VHT_Condom_stockout" INTEGER,
    "097b-SS08_VHT_RDT_stockout" INTEGER,
    "097b-SS09_VHT_Other_stockout" INTEGER,
    "097b-SS10_VHT_RA_stockout" INTEGER,
    "097b-SS01_2019_Village_ACT_stockout" INTEGER,
    "097b-SS02_2019_Village_Amox_stockout" INTEGER,
    "097b-SS03_2019_Village_ORS_Zinc_stockout" INTEGER,
    "097b-SS04_2019_Village_Misoprostol_stockout" INTEGER,
    "097b-SS05_2019_Village_DMPA_stockout" INTEGER,
    "097b-SS06_2019_Village_COC_stockout" INTEGER,
    "097b-SS07_2019_Village_POP_stockout" INTEGER,
    "097b-SS08_2019_Village_Condom_stockout" INTEGER,
    "097b-SS09_2019_Village_RDT_stockout" INTEGER,
    "097b-SS10_2019_Village_EC_stockout" INTEGER,
    "097b-SS11_2019_Village_Other_stockout" INTEGER,

    -- Village Health Team (VHT) metrics
    "097b-VH01_Children_lt1m" INTEGER,
    "097b-VH01a_Total_people" INTEGER,
    "097b-VH01b_Deaths" INTEGER,
    "097b-VH02_screened_MUAC" INTEGER,
    "097b-VH03a_Yellow_MUAC" INTEGER,
    "097b-VH03b_Red_MUAC" INTEGER,
    "097b-VH03c_Oedema" INTEGER,
    "097b-VH04_Referred_MUAC_Oedema" INTEGER,
    "097b-VH05_2019_children_1_5y" INTEGER,
    "097b-VH05_PLW_screened_MUAC" INTEGER,
    "097b-VH06_2019_children_died_1_5y" INTEGER,
    "097b-VH06a_PLW_Yellow_MUAC" INTEGER,
    "097b-VH06b_PLW_Red_MUAC" INTEGER,
    "097b-VH07_2019_children_under5" INTEGER,
    "097b-VH07_PLW_linked_to_care" INTEGER,
    "097b-VH08_2019_VitA" INTEGER,
    "097b-VH09_2019_Dewormed" INTEGER,
    "097b-VH09_Caregroups_visited" INTEGER,
    "097b-VH10_HH_3_foodgroups" INTEGER,
    "097b-VH10_2019_U5_screened_MUAC" INTEGER,
    "097b-VH11_U5_deworming_UTD" INTEGER,
    "097b-VH11b_2019_Yellow_MUAC" INTEGER,
    "097b-VH11a_2019_Red_MUAC" INTEGER,
    "097b-VH11c_2019_Oedema" INTEGER,
    "097b-VH12_home_delivery" INTEGER,
    "097b-VH12_U5_VitA_UTD" INTEGER,
    "097b-VH13_DPT1" INTEGER,
    "097b-VH13_2019_followup_linked" INTEGER,
    "097b-VH14_2019_PLW_screened" INTEGER,
    "097b-VH14_DPT3" INTEGER,
    "097b-VH15b_2019_Yellow_MUAC_PLW" INTEGER,
    "097b-VH15a_2019_Red_MUAC_PLW" INTEGER,
    "097b-VH15_Disability" INTEGER,
    "097b-VH16_Presumed_TB" INTEGER,
    "097b-VH16_2019_PLW_referred" INTEGER,
    "097b-VH17_FP_clients_referred" INTEGER,
    "097b-VH17_2019_PLW_followed_linked" INTEGER,
    "097b-VH18_2019_U5_UTD_immun" INTEGER,
    "097b-VH18_FP_referrals_effective" INTEGER,
    "097b-VH19_Pregnant_women" INTEGER,
    "097b-VH20_2019_HIV_positive_seen" INTEGER,
    "097b-VH21_Maternal_deaths" INTEGER,
    "097b-VH21_2019_HIV_not_on_ART" INTEGER,
    "097b-VH22_2019_TB_identified" INTEGER,
    "097b-VH22_ANC4" INTEGER,
    "097b-VH23_BF_support_lt1m" INTEGER,
    "097b-VH23_2019_TB_not_on_treatment" INTEGER,
    "097b-VH24_EBF_lt6m" INTEGER,
    "097b-VH24_2019_FP_services" INTEGER,
    "097b-VH28_2019_ANC8" INTEGER,
    "097b-VH29_2019_Adolescents" INTEGER,
    "097b-VH30_2019_HPV_vaccine" INTEGER,
    "097b-VH32_2019_LLINS" INTEGER,

    -- Village/Household Statistics
    "097b-VS01_Households" INTEGER,
    "097b-VS02_VHTs_ICCM" INTEGER,
    "097b-VS03_VHTs_FP" INTEGER,
    "097b-VS04_VHTs_reporting_all" INTEGER,
    "097b-VS05_VHTs_expected_report" INTEGER,
    "097b-VS06_Villages_reporting" INTEGER,

    -- WASH Indicators
    "097b-WS01_Latrines" INTEGER,
    "097b-WS02_Improved_latrines" INTEGER,
    "097b-WS03_Handwashing" INTEGER,
    "097b-WS04_Safe_drinking_water" INTEGER,
    "097b-WS05_ODF" INTEGER,
    "097b-WS06_Community_dialogues" INTEGER,
    "097b-WS07_Community_action_days" INTEGER,
    "097b-WS08_Water" INTEGER,
    "097b-WS09_Sanitation" INTEGER,
    "097b-WS10_Hygiene" INTEGER,
    "097b-WS11_Healthcare_waste_mgmt" INTEGER,
    "097b-WS12_Environmental_cleaning" INTEGER,
    "097b-WS13_General_observations" INTEGER,
    
    -- Housekeeping
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--CREATE TABLE report.mv_non_communicable_diseases (
    -- Metadata
    year INTEGER,
    month INTEGER,
    monthname TEXT,
    district TEXT,
    region TEXT,
    facility TEXT,

    -- Cancer Indicators
    "Sickle cell anaemia (Cases)" INTEGER,
    "Cervical Cancer (Cases)" INTEGER,
    "Prostate Cancer (Cases)" INTEGER,
    "Breast Cancer (Cases)" INTEGER,
    "Lung Cancer (Cases)" INTEGER,
    "Liver Cancer (Cases)" INTEGER,
    "Multiple Myeloma (Cases)" INTEGER,
    "Colorectal Cancer (Cases)" INTEGER,
    "Kaposi Sarcoma (Cases)" INTEGER,
    "Skin Cancers (Cases)" INTEGER,
    "Leukemia (Cases)" INTEGER,
    "Burkitt Lymphoma (Cases)" INTEGER,
    "Other forms of lymphomas (Cases)" INTEGER,
    "Oesophageal Cancer (Cases)" INTEGER,
    "Urogenital Cancers (Cases)" INTEGER,
    "Benign Prostate Hyperplasia (Cases)" INTEGER,
    "Oral Cancers (Cases)" INTEGER,
    "Pharyngeal Cancers (Cases)" INTEGER,
    "Stomach Cancers (Cases)" INTEGER,
    "Ovarian Cancer (Cases)" INTEGER,
    "Penile Cancer (Cases)" INTEGER,
    "Kidney Cancer (Cases)" INTEGER,
    "Rhabdomyosarcoma Cancer (Cases)" INTEGER,
    "Retinoblastoma Cancer (Cases)" INTEGER,
    "Bone Tumors Cancer (Cases)" INTEGER,
    "Other Benign Tumours (Cases)" INTEGER,
    "Other Malignant Tumours (Cases)" INTEGER,
    "Other Cancers (Cases)" INTEGER,

    -- Metabolic & Endocrine
    "Diabetes mellitus (Cases)" INTEGER,
    "Thyroid Disease (Cases)" INTEGER,
    "Other Endocrine and Metabolic Diseases (Cases)" INTEGER,

    -- Mental Health & Neurological
    "Intellectual disability (Cases)" INTEGER,
    "Anxiety Disorders (Cases)" INTEGER,
    "Autism spectrum disorders (Cases)" INTEGER,
    "Anxiety Disorder due to gender based violence (Cases)" INTEGER,
    "ADHD (Cases)" INTEGER,
    "Unipolar Depressive Disorder (Cases)" INTEGER,
    "Specific Learning Disorders (Cases)" INTEGER,
    "Bipolar disorder (Cases)" INTEGER,
    "Brief Psychotic Disorder (Cases)" INTEGER,
    "Schizophreniform Disorder (Cases)" INTEGER,
    "Post-Traumatic Stress Disorder (Cases)" INTEGER,
    "Schizophrenia (Cases)" INTEGER,
    "Bipolar Affective Disorder (Cases)" INTEGER,
    "Major Depressive Disorder (Cases)" INTEGER,
    "Anxiety - Phobic Disorders (Cases)" INTEGER,
    "Anxiety - Social anxiety Disorders (Cases)" INTEGER,
    "Anxiety - Panic Disorder (Cases)" INTEGER,
    "Anxiety - Generalized anxiety Disorder (Cases)" INTEGER,
    "Obsessive-Compulsive Disorder (Cases)" INTEGER,
    "Acute Stress Disorder (Cases)" INTEGER,
    "Internet addiction (Cases)" INTEGER,
    "Adjustment Disorder (Cases)" INTEGER,
    "Substance (Drug) use Disorder (Cases)" INTEGER,
    "Somatic Symptom Disorder (Cases)" INTEGER,
    "Illness Anxiety Disorder (Cases)" INTEGER,
    "Eating Disorder (Cases)" INTEGER,
    "Enuresis/Encopresis (Cases)" INTEGER,
    "Insomnia Disorder (Cases)" INTEGER,
    "Other Sleeping Disorders (Cases)" INTEGER,
    "Erectile Disorder (Cases)" INTEGER,
    "Conduct Disorder (Cases)" INTEGER,

    -- Substance Use
    "Alcohol Use Disorders (Cases)" INTEGER,
    "Alcohol Intoxication (Cases)" INTEGER,
    "Cannabis Use Disorder (Cases)" INTEGER,
    "Tobacco Use Disorders (Cases)" INTEGER,
    "Khat Use Disorder (Cases)" INTEGER,
    "Other Substance Use Disorders (Cases)" INTEGER,

    -- Neurological & Dementia
    "Delirium (Cases)" INTEGER,
    "Epilepsy (Cases)" INTEGER,
    "Alzheimer’s disease (Cases)" INTEGER,
    "HIV related psychosis (Cases)" INTEGER,
    "HIV related dementia (Cases)" INTEGER,
    "Alcohol related Dementia (Cases)" INTEGER,
    "Dementia due to stroke (Diabetes, Hypertension) (Cases)" INTEGER,
    "Other forms of Dementia (Cases)" INTEGER,
    "Personality Disorder (Cases)" INTEGER,
    "Conversion disorder (Cases)" INTEGER,
    "Gambling Disorder (Cases)" INTEGER,
    "Gaming Disorder (Cases)" INTEGER,
    "Attempted Suicide/Self-harm (Cases)" INTEGER,

    -- Cardiovascular
    "Stroke/CVA (Cases)" INTEGER,
    "Hypertension (Cases)" INTEGER,
    "Heart failure (Cases)" INTEGER,
    "Ischemic Heart Diseases (Cases)" INTEGER,
    "Rheumatic Heart Diseases (Cases)" INTEGER,
    "Congenital Heart Diseases (Cases)" INTEGER,
    "Chronic Heart Diseases (Cases)" INTEGER,
    "Deep Vein Thrombosis(DVT)(Cases)" INTEGER,
    "Other Cardiovascular Diseases (Cases)" INTEGER,

    -- Respiratory
    "Asthma (Cases)" INTEGER,
    "Pulmonary Fibrosis (Cases)" INTEGER,
    "Chronic Obstructive Pulmonary Disease (COPD) (Cases)" INTEGER,
    "Other Chronic Respiratory diseases (Cases)" INTEGER,

    -- Tracking
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--CREATE TABLE cht.mv_vht_supervision (
    uuid TEXT,
    form TEXT,
    submitter TEXT,
    reported TIMESTAMP,
    date DATE,
    year INTEGER,
    month INTEGER,
    monthname TEXT,
    instanceid TEXT,
    deprecatedid TEXT,
    location_lat TEXT,
    location_long TEXT,
    location_error TEXT,
    location_message TEXT,
    geolocation_code TEXT,
    geolocation_message TEXT,
    vht_supervisor_id TEXT,
    supervisor_name TEXT,
    vht_name TEXT,
    facility_id TEXT,
    facility_name TEXT,
    district_check TEXT,
    district TEXT,
    region TEXT,
    inputs_source TEXT,
    vht_area_uuid TEXT,
    vht_name_encrypted TEXT,
    inputs_contact_contact_name TEXT,
    private TEXT,
    place_name TEXT,
    vht_supervised TEXT,
    vht_supervision_status TEXT,
    last_refresh_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--CREATE TABLE cht.mv_chew_hierarchy_2 (
    chw_id TEXT,
    username TEXT,
    chw_name TEXT,
    phone TEXT,
    email TEXT,
    role TEXT,
    vht_area_id TEXT,
    vht_area_name TEXT,
    county TEXT,
    sub_county TEXT,
    village TEXT,
    parish_id TEXT,
    parish TEXT,
    facility_id TEXT,
    facility_name TEXT,
    dhis2_facility_id TEXT,
    district_id TEXT,
    district TEXT,
    region_id TEXT,
    region TEXT,
    last_refresh_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--CREATE TABLE cht.mv_chew_performance (
    region TEXT,
    district TEXT,
    year INTEGER,
    reported_quarter TEXT,
    reported_month_year TEXT,
    reported_monthname TEXT,
    month INTEGER,
    quarter INTEGER,
    chw_worked BIGINT,
    chw_tagged_facility BIGINT,
    chw_nottagged_facility BIGINT,
    role_chew_active BIGINT,
    role_superchew_active BIGINT,
    total_forms_completed BIGINT,
    forms_list TEXT,
    total_chews_registered BIGINT,
    total_superchews_registered BIGINT,
    total_capacity BIGINT,
    patients_seen_with_id BIGINT,
    patients_seen_no_id BIGINT,
    -- Clinical Aggregates
    recoded_screening BIGINT,
    recoded_wash_report BIGINT,
    recoded_assessment BIGINT,
    prescription_summary BIGINT,
    recoded_referral_follow_up BIGINT,
    recoded_anc_visit_follow_up BIGINT,
    recoded_treatment_follow_up BIGINT,
    recoded_household_model_follow_up BIGINT,
    recoded_fp_registration BIGINT,
    recoded_anc_referral_follow_up BIGINT,
    recoded_maternal_nutrition_follow_up BIGINT,
    recoded_mute BIGINT,
    recoded_unmute BIGINT,
    recoded_fp_referral_follow_up BIGINT,
    recoded_pnc_baby_follow_up BIGINT,
    recoded_vht_consumption_log BIGINT,
    recoded_household_model_notification BIGINT,
    recoded_vht_supervision BIGINT,
    recoded_death_report BIGINT,
    recoded_stockout BIGINT,
    recoded_delivery_check BIGINT,
    recoded_copy_of_danger_signs_follow_up_report BIGINT,
    recoded_maternal_health_education BIGINT,
    recoded_pregnancy BIGINT,
    recoded_pnc_danger_sign BIGINT,
    recoded_stock_count BIGINT,
    recoded_fp_follow_up BIGINT,
    recoded_anc_danger_sign BIGINT,
    recoded_pnc_follow_up BIGINT,
    recoded_delivery BIGINT,
    recoded_death_notification BIGINT,
    recoded_drowning_workflow BIGINT,
    recoded_copy_of_danger_signs_report BIGINT,
    recoded_copy_of_ha_danger_signs_follow_up_report BIGINT,
    recoded_health_education BIGINT,
    recoded_newborn_danger_sign_follow_up BIGINT,
    recoded_tb_screening BIGINT,
    recoded_training_evaluation BIGINT,
    recoded_ncd_screening BIGINT,
    recoded_ha_danger_signs_follow_up BIGINT,
    recoded_child_health_escalation BIGINT,
    recoded_vht_home_location BIGINT,
    recoded_support_supervision BIGINT,
    recoded_tb_results_notification BIGINT,
    recoded_pregnancy_danger_sign_follow_up BIGINT,
    recoded_sputum_collection BIGINT,
    recoded_tb_referral_follow_up BIGINT,
    recoded_sdx_results BIGINT,
    recoded_uncompleted_referral BIGINT,
    recoded_undo_death_report BIGINT,
    recoded_child_health_notification BIGINT,
    recoded_child_nutrition_follow_up BIGINT,
    recoded_tb_follow_up BIGINT,
    recoded_community_death_notification BIGINT,
    recoded_pregnancy_facility_visit_reminder BIGINT,
    recoded_pnc_danger_sign_follow_up_mother BIGINT,
    recoded_anc_danger_sign_escalation BIGINT,
    recoded_sdx_trigger BIGINT,
    recoded_child_nutrition_referral_follow_up BIGINT,
    last_refresh_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--CREATE TABLE cht.mv_form_meta (
    form_uuid TEXT PRIMARY KEY,
    form_name TEXT,
    patient_id TEXT,
    reported TIMESTAMP WITH TIME ZONE,
    date DATE,
    year INTEGER,
    month INTEGER,
    monthname TEXT,
    contact_id TEXT,
    username TEXT,
    chw_name TEXT,
    phone TEXT,
    email TEXT,
    role TEXT,
    vht_area_name TEXT,
    village TEXT,
    parish TEXT,
    facility_name TEXT,
    dhis2_facility_id TEXT,
    district TEXT,
    region TEXT,
    last_refresh_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--CREATE TABLE cht.mv_assessment (
    uuid TEXT,
    form TEXT,
    submitter TEXT,
    reported TIMESTAMP,
    date DATE,
    year INTEGER,
    month INTEGER,
    monthname TEXT,
    instanceid TEXT,
    deprecatedid TEXT,
    location_lat TEXT,
    location_long TEXT,
    location_error TEXT,
    location_message TEXT,
    geolocation_code TEXT,
    geolocation_message TEXT,
    contact_chw_id TEXT,
    contact_chw_area_id TEXT,
    contact_facility_id TEXT,
    parish_id TEXT,
    district_id TEXT,
    region_id TEXT,
    inputs_source TEXT,
    inputs_source_id TEXT,
    inputs_user_contact_id TEXT,
    inputs_user_facility_id TEXT,
    inputs_contact_id TEXT,
    inputs_contact_name TEXT,
    inputs_contact_date_of_birth TEXT,
    inputs_contact_sex TEXT,
    inputs_contact_parent_id TEXT,
    inputs_contact_parent_name TEXT,
    inputs_contact_parent_parent_id TEXT,
    inputs_contact_parent_parent_name TEXT,
    inputs_contact_parent_parent_supervisor TEXT,
    inputs_contact_parent_parent_phone TEXT,
    inputs_contact_parent_parent_village TEXT,
    inputs_contact_parent_parent_contact_id TEXT,
    inputs_contact_parent_parent_contact_phone TEXT,
    inputs_contact_parent_parent_contact_name TEXT,
    inputs_contact_parent_parent_parent_id TEXT,
    vaccines_received TEXT,
    vaccination_expected TEXT,
    date_of_birth_local TEXT,
    visited_contact_uuid TEXT,
    patient_age_in_years TEXT,
    patient_age_in_months TEXT,
    patient_age_in_days TEXT,
    patient_age_display TEXT,
    patient_id TEXT,
    patient_name TEXT,
    patient_gender TEXT,
    recently_assessed TEXT,
    is_hiv_positive TEXT,
    lastdoseofvitaminadate TEXT,
    symptom_cough TEXT,
    symptom_indrawn_chest TEXT,
    symptom_fast_breathing TEXT,
    symptom_diarrhoea TEXT,
    symptom_fever TEXT,
    num_of_mrdt_tests TEXT,
    symptom_malaria_test TEXT,
    referral_follow_up TEXT,
    give_prereferral_treatment TEXT,
    given_prereferral_treatment TEXT,
    diagnosis_cough TEXT,
    chw_area_id TEXT,
    chw_area_name TEXT,
    chw_name TEXT,
    chw_phone TEXT,
    chw_village TEXT,
    supervisor_id TEXT,
    branch_id TEXT,
    fever_treatment TEXT,
    cough_treatment TEXT,
    diarrhoea_treatment TEXT,
    act_prereferral_treatment_quantity TEXT,
    act_treatment_quantity TEXT,
    act_given TEXT,
    zinc_given TEXT,
    amoxicillin_prereferral_treatment_quantity TEXT,
    amoxicillin_treatment_quantity TEXT,
    amoxicillin_given TEXT,
    mrdt_given TEXT,
    rectal_given TEXT,
    gloves_given TEXT,
    diagnosis_diarrhoea TEXT,
    diagnosis_fever TEXT,
    treat_child_for_diagnosis TEXT,
    hiv_exposure_label TEXT,
    tb_exposure_label TEXT,
    needs_signoff TEXT,
    should_escalate_nutrtion_referral_follow_up TEXT,
    should_escalate_to_chew TEXT,
    vht_vht_assessment_date TEXT,
    vht_note_date_of_birth TEXT,
    vht_is_date_of_birth_correct TEXT,
    vht_note_update_correct_date_of_birth TEXT,
    gany_danger_signs TEXT,
    gchild_has_danger_signs TEXT,
    grefer_urgent_to_health_facility TEXT,
    g_has_cough TEXT,
    g_cough_duration TEXT,
    g_has_chest_indrawing TEXT,
    g_note_check_fast_breathing TEXT,
    g_cough_danger_sign TEXT,
    g_note_press_timer TEXT,
    g_note_fast_breathing_depends_on TEXT,
    g_breath_count TEXT,
    g_fast_breathing TEXT,
    g_fast_breathing_note_true TEXT,
    g_fast_breathing_note_false TEXT,
    g_has_diarrhoea TEXT,
    g_diarrhoea_duration TEXT,
    g_blood_in_stool TEXT,
    g_diarrhoea_danger_sign TEXT,
    g_has_fever TEXT,
    g_has_thermometer TEXT,
    g_patient_temperature TEXT,
    g_fever_duration TEXT,
    g_has_mrdt TEXT,
    g_mrdt_repeat_count TEXT,
    g_mrdt_repeat_note_do_mrdt TEXT,
    g_mrdt_repeat_mrdt_used_repeat TEXT,
    g_mrdt_repeat_after_blood_note_carestat TEXT,
    g_mrdt_repeat_after_blood_note_bioline TEXT,
    g_mrdt_repeat_mrdt_result_repeat TEXT,
    g_mrdt_repeat_why_mrdt_not_done_repeat TEXT,
    g_mrdt_repeat_note_mrdt_positive_repeat TEXT,
    g_mrdt_repeat_note_mrdt_negative TEXT,
    g_mrdt_repeat_note_mrdt_no_results TEXT,
    g_mrdt_repeat_note_encourage_client_to_take_mrdt TEXT,
    g_want_to_repeat_mrdt TEXT,
    g_mrdt_result TEXT,
    g_mrdt_used TEXT,
    g_why_mrdt_not_done TEXT,
    g_note_mrdt_positive TEXT,
    g_fever_danger_sign TEXT,
    g_has_hiv_exposure TEXT,
    g_has_tb_exposure TEXT,
    g_acute_malnutrition_signs TEXT,
    g_note_use_muac_tape TEXT,
    g_muac_colour TEXT,
    g_child_sam TEXT,
    g_child_mam TEXT,
    g_refer_to_health_facility TEXT,
    mal_referred_to_health_facility TEXT,
    g_assess_for_exclusive_breastfeeding TEXT,
    g_encourage_to_give_balanced_diet TEXT,
    g_appears_too_small TEXT,
    g_malnutrition_danger_sign TEXT,
    g_has_chc TEXT,
    g_note_vaccines_received TEXT,
    g_immunization_received TEXT,
    g_immunization_uptodate TEXT,
    g_note_uptodate TEXT,
    g_note_not_uptodate TEXT,
    g_refer_immunization_ack TEXT,
    g_note_encourage_imm TEXT,
    g_afp_vpd TEXT,
    g_refer_afp_ack TEXT,
    g_exclusive_breast_feeding TEXT,
    g_reason_child_not_breastfeeding TEXT,
    g_not_breastfeeding_reason_other TEXT,
    other_referred_to_health_facility TEXT,
    g_still_breastfeeding TEXT,
    g_note_counsel_and_educate TEXT,
    g_note_educate_mother TEXT,
    g_walking_or_crawling TEXT,
    g_note_educate_caregiver TEXT,
    g_child_been_dewormed TEXT,
    g_note_vitamin_a TEXT,
    g_received_vitamin_a TEXT,
    g_last_vitamin_a_date TEXT,
    g_refer_to_health_facility_no_vitamin_a TEXT,
    g_note_vitamin_a_advice TEXT,
    g_wrap_baby_warm TEXT,
    g_skin_cord_care TEXT,
    g_breastfeeding_exclusively TEXT,
    g_wash_hands_before_handling_baby TEXT,
    g_bathe_baby_clean_water TEXT,
    g_do_not_apply_anything_on_cord TEXT,
    g_start_breastfeeding_immediately TEXT,
    g_feed_the_baby TEXT,
    g_ensure_baby_well_positioned TEXT,
    chw_id TEXT,
    facility_name TEXT,
    village TEXT,
    district TEXT,
    region TEXT,
    last_refresh_date TIMESTAMP
);

--CREATE TABLE cht.mv_screening (
    uuid TEXT,
    form TEXT,
    submitter TEXT,
    reported TIMESTAMP,
    date DATE,
    year INTEGER,
    month TEXT,
    instanceid TEXT,
    deprecatedid TEXT,
    location_lat TEXT,
    location_long TEXT,
    location_error TEXT,
    location_message TEXT,
    geolocation_code TEXT,
    geolocation_message TEXT,
    chw_id TEXT,
    contact_chw_area_id TEXT,
    contact_facility_id TEXT,
    parish_id TEXT,
    district_id TEXT,
    region_id TEXT,
    inputs_source TEXT,
    inputs_source_id TEXT,
    inputs_contact_id TEXT,
    inputs_contact_name TEXT,
    inputs_contact_date_of_birth TEXT,
    inputs_contact_sex TEXT,
    inputs_contact_parent_id TEXT,
    visited_contact_uuid TEXT,
    patient_age_in_years TEXT,
    patient_age_in_months TEXT,
    patient_age_in_days TEXT,
    patient_age_display TEXT,
    patient_id TEXT,
    patient_name TEXT,
    patient_gender TEXT,
    patient_name_with_s TEXT,
    today_date TEXT,
    is_of_child_bearing_age TEXT,
    fp_registration_method TEXT,
    p_is_pregnant TEXT,
    p_has_started_anc TEXT,
    p_note_refer_to_health_facility_anc TEXT,
    p_referred_to_health_facility_anc TEXT,
    p_note_register_pregnancy TEXT,
    note_fp_registration TEXT,
    on_fp_method TEXT,
    fp_method TEXT,
    fp_method_label TEXT,
    experiencing_fp_side_effects TEXT,
    note_refer_counsel_and_refer TEXT,
    change_fp_method TEXT,
    note_counsel_on_all_fp_methods TEXT,
    counseled_on_fp_methods TEXT,
    referred_for_fp_services TEXT,
    follow_up_date_fp_services TEXT,
    note_register_using_fp_registration_form TEXT,
    knows_lmp TEXT,
    lmp_start_date TEXT,
    days_elapsed_since_lmp TEXT,
    lmp_approximate_date TEXT,
    note_refer_for_pregnancy_test TEXT,
    note_educate_on_available_fp_services TEXT,
    referred_for_pregnancy_test TEXT,
    follow_up_date_pregnancy_test TEXT,
    hiv_test_for_hiv_last3months TEXT,
    hiv_hiv_test_result TEXT,
    hiv_tested_hiv TEXT,
    hiv_not_tested_hiv TEXT,
    hiv_on_art_treatment TEXT,
    hiv_note_attend_art_clinic TEXT,
    hiv_taking_medication TEXT,
    hiv_note_explain_importance_taking_med TEXT,
    hiv_note_encourage_to_continue_taking_med TEXT,
    hiv_note_encourage_client TEXT,
    hiv_note_advise_client_check_status TEXT,
    hiv_note_advise_client_check_status2 TEXT,
    has_tb TEXT,
    on_tb_treatment TEXT,
    note_refer_not_on_tb_treatment TEXT,
    other_hpv_card TEXT,
    other_received_hpv TEXT,
    other_check_hpv_note TEXT,
    other_educate_hpv_note TEXT,
    other_afp_vpd TEXT,
    other_refer_afp TEXT,
    other_received_tt_vaccine TEXT,
    other_has_hypertension TEXT,
    other_has_sickle_cell TEXT,
    other_uses_tobacco TEXT,
    other_sleep_under_llin TEXT,
    other_why_not_using_llin TEXT,
    other_why_not_using_llin_other TEXT,
    other_note_vht_assist_how_to_get_llin TEXT,
    other_note_vht_demonstrate_on_llin_use TEXT,
    other_hiv_test_summary TEXT,
    other_s_note_patient_details TEXT,
    other_s_note_patient_details_values TEXT,
    other_s_note_findings TEXT,
    other_s_note_referred_for_pregnancy_confirmation TEXT,
    other_s_note_referred_for_fp_services TEXT,
    other_s_note_findings_fp TEXT,
    other_s_note_hiv TEXT,
    other_s_note_has_tb TEXT,
    other_s_note_has_no_tb TEXT,
    other_s_note_follow_up TEXT,
    other_s_note_follow_up_value TEXT,
    other_s_note_thank_you TEXT,
    last_refresh_date TIMESTAMP
);




--CREATE TABLE cht.mv_health_education (
    uuid TEXT,
    form TEXT,
    submitter TEXT,
    reported TIMESTAMP,
    date DATE,
    year INTEGER,
    month TEXT,
    instanceid TEXT,
    deprecatedid TEXT,
    location_lat TEXT,
    location_long TEXT,
    location_error TEXT,
    location_message TEXT,
    geolocation_code TEXT,
    geolocation_message TEXT,
    chw_id TEXT,
    contact_chw_area_id TEXT,
    contact_facility_id TEXT,
    parish_id TEXT,
    district_id TEXT,
    region_id TEXT,
    inputs_source TEXT,
    inputs_source_id TEXT,
    inputs_user_contact_id TEXT,
    inputs_user_facility_id TEXT,
    inputs_contact_id TEXT,
    inputs_contact_name TEXT,
    inputs_contact_contact_id TEXT,
    inputs_contact_contact_name TEXT,
    inputs_contact_contact_date_of_birth TEXT,
    patient_id TEXT,
    place_id TEXT,
    chew_name TEXT,
    chew_date_of_birth TEXT,
    chew_age_display TEXT,
    village_id TEXT,
    village_name TEXT,
    needs_signoff TEXT,
    chosen_venue TEXT,
    selected_village_venue TEXT,
    selected_village_village_id TEXT,
    selected_village_name TEXT,
    fields_geolocation_n_geolocation TEXT,
    fields_geolocation_want_to_capture_gps TEXT,
    fields_geolocation_gps_capture_checklist TEXT,
    fields_geolocation_gps TEXT,
    fields_geolocation_gps_capture_checklist_completed TEXT,
    fields_geolocation_latitude TEXT,
    fields_geolocation_longitude TEXT,
    fields_geolocation_altitude TEXT,
    fields_geolocation_accuracy TEXT,
    fields_geolocation_gps_location_picked_display TEXT,
    fields_geolocation_additional_comments TEXT,
    he_session_date TEXT,
    he_topics_covered TEXT,
    he_specify_other_topic TEXT,
    g_wash_topic_wash_priorities TEXT,
    g_wash_topic_nb_attendee_wash INTEGER,
    g_wash_topic_additional_notes_wash TEXT,
    g_nutrition_promotion_topic_nutrition_practices TEXT,
    g_nutrition_promotion_topic_nb_attendee_food_promotion INTEGER,
    g_nutrition_promotion_topic_additional_notes_promotion TEXT,
    g_non_communicable_diseases_topic_non_communicable_diseases_fac TEXT,
    g_non_communicable_diseases_topic_nb_attendee_commun_diseases INTEGER,
    g_non_communicable_diseases_topic_additional_notes_commun_disea TEXT,
    g_leprosy_topic_leprosy_facts TEXT,
    g_leprosy_topic_nb_attendee_leprosy INTEGER,
    g_leprosy_topic_additional_notes_leprosy TEXT,
    g_malaria_topic_malaria_facts TEXT,
    g_malaria_topic_nb_attendee_malaria INTEGER,
    g_malaria_topic_additional_notes_malaria TEXT,
    g_hiv_aids_topic_hiv_aids_facts TEXT,
    g_hiv_aids_topic_nb_attendee_hiv INTEGER,
    g_hiv_aids_topic_additional_notes_hiv TEXT,
    g_tb_topic_tb_facts TEXT,
    g_tb_topic_nb_attendee_tb INTEGER,
    g_tb_topic_additional_notes_tb TEXT,
    g_maternal_health_topic_maternal_health_facts TEXT,
    g_maternal_health_topic_nb_attendee_maternal_health INTEGER,
    g_maternal_health_topic_additional_notes_maternal_health TEXT,
    g_child_health_topic_child_health_facts TEXT,
    g_child_health_topic_nb_attendee_child_health INTEGER,
    g_child_health_topic_additional_notes_child_health TEXT,
    g_other_topic_nb_attendee_other_topic INTEGER,
    g_other_topic_additional_notes_other_topic TEXT,
    s_note_chew_area_details TEXT,
    s_note_chew_area_details_values TEXT,
    s_note_findings_title TEXT,
    s_note_topics_covered TEXT,
    s_note_wash_topic_covered TEXT,
    s_note_nb_attendee_wash TEXT,
    s_note_nutrition_promotion_topic_covered TEXT,
    s_note_nb_attendee_food_promotion TEXT,
    s_note_non_communicable_diseases_topic_covered TEXT,
    s_note_nb_attendee_commun_diseases TEXT,
    s_note_leprosy_topic_covered TEXT,
    s_note_nb_attendee_leprosy TEXT,
    s_note_malaria_topic_covered TEXT,
    s_note_nb_attendee_malaria TEXT,
    s_note_hiv_aids_topic_covered TEXT,
    s_note_nb_attendee_hiv TEXT,
    s_note_tb_topic_covered TEXT,
    s_note_nb_attendee_tb TEXT,
    s_note_maternal_health_topic_covered TEXT,
    s_note_nb_attendee_maternal_health TEXT,
    s_note_child_health_topic_covered TEXT,
    s_note_nb_attendee_child_health TEXT,
    s_note_others_topic_covered TEXT,
    s_note_nb_attendee_other_topic TEXT,
    s_note_instruction TEXT,
    s_note_instruction_detail TEXT,
    last_refresh_date TIMESTAMP
);

--CREATE TABLE cht.mv_pregnancy (
    doc_id TEXT,
    rev TEXT,
    reported TIMESTAMP,
    date DATE,
    year INTEGER,
    month INTEGER,
    monthname TEXT,
    instanceid TEXT,
    deprecatedid TEXT,
    location_lat TEXT,
    location_long TEXT,
    location_error TEXT,
    location_message TEXT,
    geolocation_code TEXT,
    geolocation_message TEXT,
    "from" TEXT,
    source TEXT,
    source_id TEXT,
    user_contact_id TEXT,
    user_facility_id TEXT,
    contact_id TEXT,
    contact_name TEXT,
    contact_date_of_birth TEXT,
    contact_sex TEXT,
    parent_id TEXT,
    parent_name TEXT,
    is_of_child_bearing_age TEXT,
    visited_contact_uuid TEXT,
    patient_age_in_years TEXT,
    patient_age_in_months TEXT,
    patient_age_in_days TEXT,
    patient_age_display TEXT,
    patient_id TEXT,
    patient_name TEXT,
    patient_gender TEXT,
    edd_std TEXT,
    edd_local TEXT,
    lmp TEXT,
    nutrition_follow_up_date TEXT,
    referred_for_nutrition_follow_up TEXT,
    chw_area_name TEXT,
    chw_name TEXT,
    chw_phone TEXT,
    chw_village TEXT,
    needs_signoff TEXT,
    follow_up_date TEXT,
    client_age_in_years TEXT,
    client_age_in_months TEXT,
    client_age_in_days TEXT,
    client_age_display TEXT,
    client_sex TEXT,
    client_id TEXT,
    client_uuid TEXT,
    client_name TEXT,
    place_id TEXT,
    place_name TEXT,
    vht_name TEXT,
    vht_phone TEXT,
    using_llin TEXT,
    note_llin_prevents_malaria TEXT,
    refer_client_to_health_facility TEXT,
    has_tt_card TEXT,
    tt_immunizations TEXT,
    note_tt_protects_newborn_and_mother TEXT,
    note_two_tt_vaccines_per_pregnancy TEXT,
    tt_refer_ack TEXT,
    received_tt_immunizations TEXT,
    note_provide_nutrition_education TEXT,
    note_encourage_micro_nutrient_supplementation TEXT,
    note_encourage_sleep_under_itns TEXT,
    note_encourage_men_to_participate TEXT,
    note_encourage_to_go_for_anc TEXT,
    note_nutrition_status TEXT,
    taken_muac TEXT,
    muac_measurement TEXT,
    encourage_client_to_consume_sufficient_diet TEXT,
    note_has_sam TEXT,
    note_has_mam TEXT,
    note_refer_to_health_facility TEXT,
    referred_to_health_facility_nutrition TEXT,
    micro_nutrient_supplementation_received TEXT,
    note_encourage_micro_nutrients TEXT,
    refer_to_health_facility_no_micro_nutrients TEXT,
    on_nutrition_follow_up TEXT,
    completed_last_nutrition_follow_up TEXT,
    schedule_follow_up_visit TEXT,
    next_nutrition_follow_up_date TEXT,
    note_thank_you_nutrition_follow_up TEXT,
    note_refer_did_not_complete_follow_up TEXT,
    referred_to_health_facility_missed_nutrition_follow_up TEXT,
    ds_note_danger_signs TEXT,
    ds_vaginal_bleeding TEXT,
    ds_lower_abdomen_pain TEXT,
    ds_severe_headache TEXT,
    ds_very_pale TEXT,
    ds_fever TEXT,
    ds_reduced_or_no_feotal_movements TEXT,
    ds_blurred_vision TEXT,
    ds_swelling TEXT,
    ds_breathlessness TEXT,
    ds_has_danger_signs TEXT,
    ds_has_no_danger_signs TEXT,
    ds_note_has_no_danger_signs TEXT,
    ds_note_has_danger_signs TEXT,
    ds_referred_to_health_facility_danger_signs TEXT,
    ds_note_complete_follow_up_task TEXT,
    note_check_for_upcoming_anc_visits TEXT,
    has_upcoming_anc_visits TEXT,
    anc_appointment_date TEXT,
    number_of_anc_visits TEXT,
    anc_visits TEXT,
    hiv_test_done TEXT,
    hiv_test_result TEXT,
    note_reduce_risk_of_hiv TEXT,
    on_art_treatment TEXT,
    taking_medication TEXT,
    explain_the_mportance_of_taking_medication TEXT,
    note_encourage_client_to_take_medication TEXT,
    note_pregnancy_registration_introduction TEXT,
    pregnancy_report_method TEXT,
    lmp_start_date TEXT,
    lmp_start_date_local TEXT,
    estimated_edd_std TEXT,
    estimated_edd_local TEXT,
    note_entered_lmp TEXT,
    note_estimated_edd TEXT,
    entered_edd TEXT,
    entered_edd_local TEXT,
    pregnancy_age_in_weeks TEXT,
    note_pregnancy_age TEXT,
    note_no_information TEXT,
    vaginal_bleeding TEXT,
    lower_abdomen_pain TEXT,
    severe_headache TEXT,
    very_pale TEXT,
    fever TEXT,
    reduced_or_no_feotal_movements TEXT,
    blurred_vision TEXT,
    swelling TEXT,
    breathlessness TEXT,
    chw_id TEXT,
    facility_name TEXT,
    village TEXT,
    district TEXT,
    region TEXT,
    last_refresh_date TIMESTAMP
);


--CREATE TABLE cht.mv_referral_follow_up (
    doc_id TEXT,
    rev TEXT,
    reported TIMESTAMP,
    date DATE,
    year INTEGER,
    month TEXT,
    instanceid TEXT,
    deprecatedid TEXT,
    location_lat TEXT,
    location_long TEXT,
    location_error TEXT,
    location_message TEXT,
    geolocation_code TEXT,
    geolocation_message TEXT,
    form TEXT,
    "from" TEXT,
    source TEXT,
    source_id TEXT,
    follow_up_type TEXT,
    t_place_name TEXT,
    t_vht_name TEXT,
    t_vht_phone TEXT,
    contact_id TEXT,
    contact_name TEXT,
    contact_date_of_birth TEXT,
    contact_sex TEXT,
    parent_id TEXT,
    parent_name TEXT,
    supervisor TEXT,
    phone TEXT,
    patient_age_in_years TEXT,
    patient_age_in_months TEXT,
    patient_age_in_days TEXT,
    patient_age_display TEXT,
    patient_id TEXT,
    patient_name TEXT,
    patient_gender TEXT,
    referral_follow_up_again TEXT,
    chw_name TEXT,
    chw_phone TEXT,
    chw_village TEXT,
    needs_signoff TEXT,
    follow_up_date TEXT,
    follow_up_method TEXT,
    patient_condition TEXT,
    went_to_health_facility TEXT,
    interact_with_healthcare TEXT,
    note_encourage_to_visit_health_facility TEXT,
    hc_visit_date TEXT,
    hc_attendant TEXT,
    hc_attendant_other TEXT,
    hc_name TEXT,
    action_taken TEXT,
    instructions_for_vht TEXT,
    s_note_referral_follow_up_report TEXT,
    s_note_before_submit TEXT,
    s_note_patient_details TEXT,
    s_note_patient_details_values TEXT,
    s_note_referral_follow_up_info TEXT,
    s_note_referral_completed TEXT,
    s_note_referral_not_completed TEXT,
    s_note_comments_treatment_given TEXT,
    s_note_referral_not_improved TEXT,
    s_note_key_instruction TEXT,
    s_note_key_instruction_accompany_client TEXT,
    s_note_followup TEXT,
    s_note_followup_instructions1 TEXT,
    chw_id TEXT,
    chw_area_id TEXT,
    facility_id TEXT,
    parish_id TEXT,
    district TEXT,
    region TEXT
);


--CREATE TABLE cht.mv_household_model_notification (
    uuid TEXT,
    form TEXT,
    submitter TEXT,
    reported TIMESTAMP,
    date DATE,
    year INTEGER,
    month TEXT,
    instanceid TEXT,
    deprecatedid TEXT,
    location_lat TEXT,
    location_long TEXT,
    location_error TEXT,
    location_message TEXT,
    geolocation_code TEXT,
    geolocation_message TEXT,
    chw_id TEXT,
    contact_chw_area_id TEXT,
    contact_facility_id TEXT,
    parish_id TEXT,
    district_id TEXT,
    region_id TEXT,
    inputs_source TEXT,
    inputs_source_id TEXT,
    t_sanitary_dwelling_house TEXT,
    t_sanitary_kitchen TEXT,
    t_drying_rack TEXT,
    t_bath_shelter_with_soak_pit TEXT,
    t_sanitation_facility TEXT,
    t_hh_latrine_fly_proof TEXT,
    t_hh_is_odf TEXT,
    t_handwashing_facility_running_water TEXT,
    t_rubbish_pit TEXT,
    t_access_to_safe_water TEXT,
    t_adequate_drying_lines TEXT,
    t_animal_house TEXT,
    t_food_storage TEXT,
    t_well_maintained_compound TEXT,
    t_vector_and_vermin_control TEXT,
    t_hh_head_name TEXT,
    t_place_name TEXT,
    inputs_contact_id TEXT,
    inputs_contact_name TEXT,
    inputs_contact_parent_village TEXT,
    inputs_contact_contact_name TEXT,
    visited_contact_uuid TEXT,
    place_id TEXT,
    place_name TEXT,
    hh_head_name TEXT,
    chw_village TEXT,
    header_notification TEXT,
    note_sanaitary_dwelling_house TEXT,
    note_sanitary_kitchen TEXT,
    note_drying_rack TEXT,
    note_bath_shelter_with_soak_pit TEXT,
    note_sanitation_facility TEXT,
    note_handwashing_facility_running_water TEXT,
    note_rubbish_pit TEXT,
    note_access_to_safe_water TEXT,
    note_adequate_drying_lines TEXT,
    note_animal_house TEXT,
    note_food_storage TEXT,
    note_well_maintained_compound TEXT,
    note_vector_and_vermin_control TEXT,
    household_follow_up_date TEXT,
    s_note_household_details TEXT,
    s_note_patient_details_values TEXT,
    household_findings TEXT,
    household_model TEXT,
    s_note_followup TEXT,
    note_follow_date TEXT,
    last_refresh_date TIMESTAMP
);

--CREATE TABLE cht.mv_cebs_signal_report_vht (
    uuid TEXT,
    form TEXT,
    reported TIMESTAMP,
    date DATE,
    year INTEGER,
    month INTEGER,
    monthname TEXT,
    instanceid TEXT,
    deprecatedid TEXT,
    location_lat TEXT,
    location_long TEXT,
    location_error TEXT,
    location_message TEXT,
    geolocation_code TEXT,
    geolocation_message TEXT,
    source TEXT,
    source_id TEXT,
    user_contact_id TEXT,
    user_facility_id TEXT,
    contact_id TEXT,
    contact_name TEXT,
    contact_village TEXT,
    cont_contact_id TEXT,
    cont_contact_name TEXT,
    cont_contact_date_of_birth TEXT,
    cont_contact_phone TEXT,
    needs_signoff TEXT,
    chw_name TEXT,
    chw_phone TEXT,
    place_id TEXT,
    place_name TEXT,
    chw_village TEXT,
    experienced_unusual_health_event TEXT,
    signal_reported TEXT,
    additional_information TEXT,
    person_under_vht_area TEXT,
    brief_description TEXT,
    s_note_signal_report_summary_page TEXT,
    s_note_be_sure_to_submit TEXT,
    s_note_signal_details TEXT,
    no_signal_reported TEXT,
    s_note_fever_and_bleeding TEXT,
    s_note_unexplained_rash TEXT,
    s_note_sudden_or_unexplained_death TEXT,
    s_note_bitten_by_dog_or_animal TEXT,
    s_note_abnormal_change_in_drinking_water TEXT,
    s_note_public_health_threat TEXT,
    s_note_key_instruction TEXT,
    switch_on_data TEXT,
    chw_id TEXT,
    facility_name TEXT,
    village TEXT,
    district TEXT,
    region TEXT,
    last_refresh_date TIMESTAMP
);

--CREATE TABLE cht.mv_cebs_signal_verification (
    uuid TEXT,
    form TEXT,
    reported TIMESTAMP,
    date DATE,
    year INTEGER,
    month INTEGER,
    monthname TEXT,
    instanceid TEXT,
    deprecatedid TEXT,
    location_lat TEXT,
    location_long TEXT,
    location_error TEXT,
    location_message TEXT,
    geolocation_code TEXT,
    geolocation_message TEXT,
    t_patient_condition TEXT,
    source TEXT,
    source_id TEXT,
    vht_or_chew_name TEXT,
    vht_or_chew_phone TEXT,
    vht_or_chew_area TEXT,
    contact_id TEXT,
    contact_name TEXT,
    cont_contact_id TEXT,
    cont_contact_name TEXT,
    date_of_birth TEXT,
    user_name TEXT,
    user_contact_id TEXT,
    place_id TEXT,
    place_name TEXT,
    supervisor_name TEXT,
    supervisor_phone TEXT,
    signal_name TEXT,
    needs_signoff TEXT,
    current_user_id TEXT,
    current_user_name TEXT,
    current_user_phone TEXT,
    vht_or_chew_info TEXT,
    mode_of_verification TEXT,
    description_of_signal TEXT,
    information_match_signal_type TEXT,
    matching_signal TEXT,
    signal_reported_before TEXT,
    not_new_signal TEXT,
    health_threat_start TEXT,
    approximate_number_ill TEXT,
    approximate_number_dead TEXT,
    signal_involve_animals TEXT,
    animals_involved TEXT,
    specify_animal_involved TEXT,
    approximate_animals_affected TEXT,
    approximate_animals_dead TEXT,
    source_of_information TEXT,
    additional_information TEXT,
    date_health_threat_verified TEXT,
    reported_threat_exists TEXT,
    note_reported_threat_does_not_exist TEXT,
    date_facility_informed TEXT,
    signal_been_referred TEXT,
    chw_id TEXT,
    facility_name TEXT,
    village TEXT,
    district TEXT,
    region TEXT,
    last_refresh_date TIMESTAMP
);

--CREATE TABLE cht.mv_cebs_signal_verification_notification (
    uuid TEXT,
    form TEXT,
    reported TIMESTAMP,
    date DATE,
    year INTEGER,
    month INTEGER,
    monthname TEXT,
    deprecatedid TEXT,
    location_lat TEXT,
    location_long TEXT,
    location_error TEXT,
    location_message TEXT,
    geolocation_code TEXT,
    geolocation_message TEXT,
    source TEXT,
    source_id TEXT,
    t_place_name TEXT,
    t_place_id TEXT,
    t_vht_or_chew_name TEXT,
    t_vht_or_chew_phone TEXT,
    t_signal_name TEXT,
    t_does_not_match_signal TEXT,
    t_duplicate_signal TEXT,
    t_threat_exists TEXT,
    t_supervisor_name TEXT,
    t_supervisor_phone TEXT,
    user_contact_id TEXT,
    user_facility_id TEXT,
    contact_id TEXT,
    contact_name TEXT,
    date_of_birth TEXT,
    sex TEXT,
    supervisor TEXT,
    supervisor_phone TEXT,
    vht_or_chew_name TEXT,
    vht_or_chew_phone TEXT,
    signal_name TEXT,
    does_not_match_signal TEXT,
    is_duplicate_signal TEXT,
    threat_exists TEXT,
    needs_signoff TEXT,
    supervisor_verified_signal TEXT,
    findings TEXT,
    informatio_does_not_match_a_signal TEXT,
    notification_duplicate_signal TEXT,
    threat_still_exists TEXT,
    threat_no_longer_exists TEXT,
    chw_id TEXT,
    facility_name TEXT,
    village TEXT,
    district TEXT,
    region TEXT,
    last_refresh_date TIMESTAMP
);




--CREATE TABLE cht.mv_vht_immunization (
    last_refresh_date TIMESTAMP,
    district TEXT,
    sub_district TEXT,
    sub_county TEXT,
    parish TEXT,
    facility TEXT,
    village TEXT,
    uuid TEXT,
    username TEXT,
    name TEXT,
    period_date DATE,
    year NUMERIC,
    month NUMERIC,
    monthname TEXT,
    total_patients BIGINT,
    dpt1 BIGINT,
    dpt3 BIGINT,
    mr1 BIGINT,
    mr2 BIGINT,
    "none" BIGINT,
    immunizations_upto_date BIGINT,
    immunizations_not_upto_date BIGINT
);


--CREATE TABLE cht.mv_delivery (
    uuid TEXT,
    rev TEXT,
    reported TIMESTAMP,
    date DATE,
    year INTEGER,
    month INTEGER,
    monthname TEXT,
    instanceid TEXT,
    deprecatedid TEXT,
    location_lat TEXT,
    location_long TEXT,
    location_error TEXT,
    location_message TEXT,
    geolocation_code TEXT,
    geolocation_message TEXT,
    source_id TEXT,
    source TEXT,
    form TEXT,
    contact_id TEXT,
    contact_sex TEXT,
    contact_name TEXT,
    contat_date_of_birth TEXT,
    is_of_child_bearing_age TEXT,
    visited_contact_uuid TEXT,
    family_id TEXT,
    area_id TEXT,
    facility_id TEXT,
    patient_age_in_years TEXT,
    patient_age_in_months TEXT,
    patient_age_in_days TEXT,
    patient_age_display TEXT,
    patient_id TEXT,
    patient_name TEXT,
    patient_gender TEXT,
    today_date TEXT,
    days_since_delivery_date TEXT,
    referred_for_nutrition_follow_up TEXT,
    delivery_place_label TEXT,
    pregnancy_hiv_test_result TEXT,
    woman_outcome TEXT,
    number_of_babies_delivered TEXT,
    number_of_babies_alive TEXT,
    note_title_danger_sign TEXT,
    note_has_any_danger_signs_woman TEXT,
    woman_danger_sign_fever TEXT,
    woman_danger_sign_severe_headache TEXT,
    woman_danger_sign_vaginal_bleeding TEXT,
    woman_danger_sign_foul_vaginal_discharge TEXT,
    woman_danger_sign_convulsions TEXT,
    has_danger_signs_woman TEXT,
    note_refer_woman_danger_signs TEXT,
    referred_woman_danger_signs TEXT,
    woman_date_of_death TEXT,
    woman_place_of_death TEXT,
    woman_place_of_death_other TEXT,
    delivered_babies_before_dying TEXT,
    woman_dead_additional_notes TEXT,
    note_woman_dead_notes_detailed TEXT,
    note_encourage_kangaroo_fathers TEXT,
    name TEXT,
    sex TEXT,
    type TEXT,
    house_hold_id TEXT,
    baby_name TEXT,
    mother_id TEXT,
    date_of_birth TEXT,
    baby_condition TEXT,
    created_by_doc TEXT,
    has_danger_signs_baby TEXT,
    baby_danger_sign_body TEXT,
    baby_danger_sign_fever TEXT,
    baby_danger_sign_drowsy TEXT,
    breastfed_within_one_hour TEXT,
    baby_danger_sign_blue_skin TEXT,
    note_any_baby_danger_signs TEXT,
    baby_danger_sign_yellow_skin TEXT,
    is_exclusively_breast_feeding TEXT,
    baby_danger_sign_body_stiffness TEXT,
    baby_danger_sign_vomits_everything TEXT,
    baby_danger_sign_infected_convulsions TEXT,
    baby_danger_sign_infected_umbilical_cord TEXT,
    baby_danger_sign_infected_feeding_difficulty TEXT,
    delivery_date TEXT,
    delivery_date_local TEXT,
    delivery_place TEXT,
    delivery_place_other TEXT,
    delivery_method TEXT,
    who_conducted_delivery TEXT,
    who_conducted_delivery_other TEXT,
    note_referred_to_health_facility_danger_signs TEXT,
    referred_to_health_facility_home_delivery TEXT,
    agreed_health_facility_visit_date TEXT,
    baby_date_of_death TEXT,
    baby_place_of_death TEXT,
    baby_place_of_death_other TEXT,
    still_birth TEXT,
    baby_death_additional_notes TEXT,
    note_nutrition_status TEXT,
    taken_muac TEXT,
    muac_measurement TEXT,
    encourage_client_to_consume_sufficient_diet TEXT,
    note_has_sam TEXT,
    note_has_mam TEXT,
    note_refer_to_health_facility TEXT,
    referred_to_health_facility_nutrition TEXT,
    micro_nutrient_supplementation_received TEXT,
    note_encourage_micro_nutrients TEXT,
    counsel_mother TEXT,
    referred_to_health_facility_no_micro_nutrient_supplementation TEXT,
    note_eat_well TEXT,
    note_exclusive_breastfeeding_counsel TEXT,
    note_positioning_and_attachment TEXT,
    note_how_to_keep_baby_warm TEXT,
    note_sleep_under_llin TEXT,
    note_keep_umbilical_cord_clean TEXT,
    note_introduce_age_appropiate_foods TEXT,
    note_infants_receive_vitamin_a TEXT,
    note_micro_nutrient_supplements TEXT,
    note_promote_early_childhood_stimulation TEXT,
    note_counsel_women_living_with_hiv TEXT,
    note_hiv_exposed_infants TEXT,
    note_hiv_infected_infants TEXT,
    who_recommendation TEXT,
    pnc_visits TEXT,
    chw_id TEXT,
    facility_name TEXT,
    village TEXT,
    district TEXT,
    region TEXT,
    last_refresh_date TIMESTAMP
);