-- ============================================================================
-- check_parish_mvs.sql
-- Verifies every tier_1 parish MV was (re)created in schema cht.
--   status  = MISSING  -> CREATE did not succeed (check the run log for errors)
--   populated = f       -> expected (created WITH NO DATA; refresh separately)
-- ============================================================================

WITH expected(mv, tier) AS (VALUES
    ('mv_afp_notification','1a'),
    ('mv_anc_danger_sign','1a'),
    ('mv_anc_danger_sign_escalation','1a'),
    ('mv_anc_danger_sign_follow_up','1a'),
    ('mv_anc_danger_sign_notification','1a'),
    ('mv_anc_referral_follow_up','1a'),
    ('mv_anc_visit_follow_up','1a'),
    ('mv_assessment','1a'),
    ('mv_cebs_signal_report_chew','1a'),
    ('mv_cebs_signal_report_vht','1a'),
    ('mv_cebs_signal_verification','1a'),
    ('mv_cebs_signal_verification_notification','1a'),
    ('mv_child_health_escalation','1a'),
    ('mv_child_health_notification','1a'),
    ('mv_child_nutrition_follow_up','1a'),
    ('mv_child_nutrition_referral_follow_up','1a'),
    ('mv_clinic','1a'),
    ('mv_community_death_notification','1a'),
    ('mv_copy_of_danger_signs_follow_up_report','1a'),
    ('mv_death_notification','1a'),
    ('mv_death_report','1a'),
    ('mv_delivery','1b'),
    ('mv_delivery_check','1a'),
    ('mv_drowning_workflow','1a'),
    ('mv_fp_follow_up','1a'),
    ('mv_fp_referral_follow_up','1a'),
    ('mv_fp_registration','1a'),
    ('mv_gbv_community_form','1a'),
    ('mv_ha_danger_signs_follow_up','1a'),
    ('mv_health_education','1a'),
    ('mv_household_model_follow_up','1a'),
    ('mv_household_model_notification','1a'),
    ('mv_maternal_health_education','1a'),
    ('mv_maternal_nutrition_follow_up','1a'),
    ('mv_mute','1a'),
    ('mv_newborn_danger_sign_follow_up','1a'),
    ('mv_person','1b'),
    ('mv_pnc_baby_follow_up','1a'),
    ('mv_pnc_danger_sign','1a'),
    ('mv_pnc_follow_up','1a'),
    ('mv_pregnancy','1b'),
    ('mv_pregnancy_danger_sign_follow_up','1a'),
    ('mv_referral_follow_up','1a'),
    ('mv_screening','1b'),
    ('mv_sdx_follow_up','1a'),
    ('mv_sdx_notify','1a'),
    ('mv_sdx_trigger','1a'),
    ('mv_sputum_collection','1a'),
    ('mv_sputum_collection_refusal','1a'),
    ('mv_stock_count','1a'),
    ('mv_stockout','1a'),
    ('mv_support_supervision','1a'),
    ('mv_tb_follow_up','1a'),
    ('mv_tb_referral_follow_up','1a'),
    ('mv_tb_results_notification','1a'),
    ('mv_tb_screening','1a'),
    ('mv_tb_uncompleted_referral','1a'),
    ('mv_training_evaluation','1a'),
    ('mv_treatment_follow_up','1a'),
    ('mv_uncompleted_referral','1a'),
    ('mv_unmute','1a'),
    ('mv_useview_ai_image_assessment','1a'),
    ('mv_useview_missing_mrdt_photo','1a'),
    ('mv_useview_mrdt_mismatch','1a'),
    ('mv_vht_consumption_log','1a'),
    ('mv_vht_home_location','1a'),
    ('mv_wash_report','1a')
)
SELECT e.tier,
       e.mv AS expected_mv,
       CASE WHEN m.matviewname IS NULL THEN 'MISSING' ELSE 'ok' END AS status,
       m.ispopulated AS populated
FROM expected e
LEFT JOIN pg_matviews m
  ON m.schemaname = 'cht' AND m.matviewname = e.mv
ORDER BY status DESC, e.tier, e.mv;

-- Summary counts
WITH expected(mv, tier) AS (VALUES
    ('mv_afp_notification','1a'),
    ('mv_anc_danger_sign','1a'),
    ('mv_anc_danger_sign_escalation','1a'),
    ('mv_anc_danger_sign_follow_up','1a'),
    ('mv_anc_danger_sign_notification','1a'),
    ('mv_anc_referral_follow_up','1a'),
    ('mv_anc_visit_follow_up','1a'),
    ('mv_assessment','1a'),
    ('mv_cebs_signal_report_chew','1a'),
    ('mv_cebs_signal_report_vht','1a'),
    ('mv_cebs_signal_verification','1a'),
    ('mv_cebs_signal_verification_notification','1a'),
    ('mv_child_health_escalation','1a'),
    ('mv_child_health_notification','1a'),
    ('mv_child_nutrition_follow_up','1a'),
    ('mv_child_nutrition_referral_follow_up','1a'),
    ('mv_clinic','1a'),
    ('mv_community_death_notification','1a'),
    ('mv_copy_of_danger_signs_follow_up_report','1a'),
    ('mv_death_notification','1a'),
    ('mv_death_report','1a'),
    ('mv_delivery','1b'),
    ('mv_delivery_check','1a'),
    ('mv_drowning_workflow','1a'),
    ('mv_fp_follow_up','1a'),
    ('mv_fp_referral_follow_up','1a'),
    ('mv_fp_registration','1a'),
    ('mv_gbv_community_form','1a'),
    ('mv_ha_danger_signs_follow_up','1a'),
    ('mv_health_education','1a'),
    ('mv_household_model_follow_up','1a'),
    ('mv_household_model_notification','1a'),
    ('mv_maternal_health_education','1a'),
    ('mv_maternal_nutrition_follow_up','1a'),
    ('mv_mute','1a'),
    ('mv_newborn_danger_sign_follow_up','1a'),
    ('mv_person','1b'),
    ('mv_pnc_baby_follow_up','1a'),
    ('mv_pnc_danger_sign','1a'),
    ('mv_pnc_follow_up','1a'),
    ('mv_pregnancy','1b'),
    ('mv_pregnancy_danger_sign_follow_up','1a'),
    ('mv_referral_follow_up','1a'),
    ('mv_screening','1b'),
    ('mv_sdx_follow_up','1a'),
    ('mv_sdx_notify','1a'),
    ('mv_sdx_trigger','1a'),
    ('mv_sputum_collection','1a'),
    ('mv_sputum_collection_refusal','1a'),
    ('mv_stock_count','1a'),
    ('mv_stockout','1a'),
    ('mv_support_supervision','1a'),
    ('mv_tb_follow_up','1a'),
    ('mv_tb_referral_follow_up','1a'),
    ('mv_tb_results_notification','1a'),
    ('mv_tb_screening','1a'),
    ('mv_tb_uncompleted_referral','1a'),
    ('mv_training_evaluation','1a'),
    ('mv_treatment_follow_up','1a'),
    ('mv_uncompleted_referral','1a'),
    ('mv_unmute','1a'),
    ('mv_useview_ai_image_assessment','1a'),
    ('mv_useview_missing_mrdt_photo','1a'),
    ('mv_useview_mrdt_mismatch','1a'),
    ('mv_vht_consumption_log','1a'),
    ('mv_vht_home_location','1a'),
    ('mv_wash_report','1a')
)
SELECT count(*)                                              AS expected_total,
       count(m.matviewname)                                 AS created,
       count(*) FILTER (WHERE m.matviewname IS NULL)         AS missing,
       count(m.matviewname) FILTER (WHERE m.ispopulated)     AS populated
FROM expected e
LEFT JOIN pg_matviews m
  ON m.schemaname = 'cht' AND m.matviewname = e.mv;

-- Dependent matviews dropped by the tier_1b CASCADEs (recreate manually):
SELECT matviewname, ispopulated
FROM pg_matviews
WHERE (schemaname='cht' AND matviewname IN ('mv_integrated_echis_performance','mv_delivery_report'))
   OR matviewname = 'delivery_report'
ORDER BY matviewname;
