CREATE MATERIALIZED VIEW cht.mv_delivery
TABLESPACE ts_report
AS 
SELECT doc ->> '_id'::text AS uuid,
      doc ->> '_rev'::text                             AS rev,                                 -- [NEW FIELD]
      to_timestamp((NULLIF(d.doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'YYYY-MM-DD'::text)::date AS date,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'YYYY'::text)::integer AS year,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'FMMonth'::text) AS monthname,
     doc ->'fields'->'meta'->>'instanceID' AS instanceID,
     doc ->'fields'->'inputs'->'meta'->>'deprecatedID' AS deprecatedID,
     doc ->'fields'->'inputs'->'meta'->'location'->>'lat' AS location_lat,
     doc ->'fields'->'inputs'->'meta'->'location'->>'long' AS location_long,
     doc ->'fields'->'inputs'->'meta'->'location'->>'error' AS location_error,
     doc ->'fields'->'inputs'->'meta'->'location'->>'message' AS location_message,
     doc ->'geolocation'->>'code' AS geolocation_code,
     doc ->'geolocation'->>'message' AS geolocation_message,
    
    doc #>> '{fields,inputs,source_id}'::text[] AS source_id,
    doc #>> '{fields,inputs,source}'::text[]    AS source,
    doc ->> 'form'::text                        AS form,
    doc #>> '{fields,inputs,contact,_id}'::text[]        AS contact_id,
    doc #>> '{fields,inputs,contact,sex}'::text[]        AS contact_sex,
    doc #>> '{fields,inputs,contact,name}'::text[]       AS contact_name,
    doc #>> '{fields,inputs,contact,date_of_birth}'::text[] AS contat_date_of_birth,
    
    doc #>> '{fields,is_of_child_bearing_age}'::text[]                   AS is_of_child_bearing_age,
    doc #>> '{fields,visited_contact_uuid}'::text[]                       AS visited_contact_uuid,
    doc #>> '{fields,family_id}'::text[]                                  AS family_id,
    doc #>> '{fields,area_id}'::text[]                                    AS area_id,
    doc #>> '{fields,facility_id}'::text[]                                 AS facility_id,
    doc #>> '{fields,patient_age_in_years}'::text[]                        AS patient_age_in_years,
    doc #>> '{fields,patient_age_in_months}'::text[]                       AS patient_age_in_months,
    doc #>> '{fields,patient_age_in_days}'::text[]                         AS patient_age_in_days,
    doc #>> '{fields,patient_age_display}'::text[]                         AS patient_age_display,
    doc #>> '{fields,patient_id}'::text[]                                   AS patient_id,
    doc #>> '{fields,patient_name}'::text[]                                 AS patient_name,
    doc #>> '{fields,patient_gender}'::text[]                               AS patient_gender,
    doc #>> '{fields,today_date}'::text[]                                   AS today_date,
    doc #>> '{fields,days_since_delivery_date}'::text[]                     AS days_since_delivery_date,
    doc #>> '{fields,referred_for_nutrition_follow_up}'::text[]             AS referred_for_nutrition_follow_up,
    doc #>> '{fields,delivery_place_label}'::text[]                          AS delivery_place_label,
    doc #>> '{fields,pregnancy_hiv_test_result}'::text[]                          AS pregnancy_hiv_test_result,
  
    doc #>> '{fields,group_woman_condition,woman_outcome}'::text[]      AS woman_outcome,
    doc #>> '{fields,group_delivery_outcomes,number_of_babies_delivered}'::text[]      AS number_of_babies_delivered,
    doc #>> '{fields,group_delivery_outcomes,number_of_babies_alive}'::text[]      AS number_of_babies_alive,

    doc #>> '{fields,group_woman_danger_sign_check,note_title_danger_sign}'::text[]           AS note_title_danger_sign,
    doc #>> '{fields,group_woman_danger_sign_check,note_has_any_danger_signs_woman}'::text[]  AS note_has_any_danger_signs_woman,
    doc #>> '{fields,group_woman_danger_sign_check,woman_danger_sign_fever}'::text[]          AS woman_danger_sign_fever,
    doc #>> '{fields,group_woman_danger_sign_check,woman_danger_sign_severe_headache}'::text[] AS woman_danger_sign_severe_headache,
    doc #>> '{fields,group_woman_danger_sign_check,woman_danger_sign_vaginal_bleeding}'::text[] AS woman_danger_sign_vaginal_bleeding,
    doc #>> '{fields,group_woman_danger_sign_check,woman_danger_sign_foul_vaginal_discharge}'::text[] AS woman_danger_sign_foul_vaginal_discharge,
    doc #>> '{fields,group_woman_danger_sign_check,woman_danger_sign_convulsions}'::text[]    AS woman_danger_sign_convulsions,
    doc #>> '{fields,group_woman_danger_sign_check,has_danger_signs_woman}'::text[]           AS has_danger_signs_woman,
    doc #>> '{fields,group_woman_danger_sign_check,note_refer_woman_danger_signs}'::text[]    AS note_refer_woman_danger_signs,
    doc #>> '{fields,group_woman_danger_sign_check,referred_woman_danger_signs}'::text[]      AS referred_woman_danger_signs,
    doc #>> '{fields,group_woman_danger_sign_check,woman_date_of_death}'::text[]              AS woman_date_of_death,
    doc #>> '{fields,group_woman_danger_sign_check,woman_place_of_death}'::text[]             AS woman_place_of_death,
    doc #>> '{fields,group_woman_danger_sign_check,woman_place_of_death_other}'::text[]       AS woman_place_of_death_other,
    doc #>> '{fields,group_woman_danger_sign_check,delivered_babies_before_dying}'::text[]    AS delivered_babies_before_dying,
    doc #>> '{fields,group_woman_danger_sign_check,woman_dead_additional_notes}'::text[]      AS woman_dead_additional_notes,
    doc #>> '{fields,group_woman_danger_sign_check,note_woman_dead_notes_detailed}'::text[]   AS note_woman_dead_notes_detailed,
    doc #>> '{fields,group_woman_danger_sign_check,note_encourage_kangaroo_fathers}'::text[]  AS note_encourage_kangaroo_fathers,
    
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,name}' AS name,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,sex}' AS sex,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,type}' AS type,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,parent,_id}' AS house_hold_id,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_name}' AS baby_name,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,mother_id}' AS mother_id,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,date_of_birth}' AS date_of_birth,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_condition}' AS baby_condition,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,created_by_doc}' AS created_by_doc,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,has_danger_signs_baby}' AS has_danger_signs_baby,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_body}' AS baby_danger_sign_body,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_fever}' AS baby_danger_sign_fever,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_drowsy}' AS baby_danger_sign_drowsy,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,breastfed_within_one_hour}' AS breastfed_within_one_hour,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_blue_skin}' AS baby_danger_sign_blue_skin,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,note_any_baby_danger_signs}' AS note_any_baby_danger_signs,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_yellow_skin}' AS baby_danger_sign_yellow_skin,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,is_exclusively_breast_feeding}' AS is_exclusively_breast_feeding,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_body_stiffness}' AS baby_danger_sign_body_stiffness,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_vomits_everything}' AS baby_danger_sign_vomits_everything,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_infected_convulsions}' AS baby_danger_sign_infected_convulsions,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_infected_umbilical_cord}' AS baby_danger_sign_infected_umbilical_cord,
doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_infected_feeding_difficulty}' AS baby_danger_sign_infected_feeding_difficulty,
 
    
    doc #>> '{fields,group_delivery_information,delivery_date}'::text[]                             AS delivery_date,
    doc #>> '{fields,group_delivery_information,delivery_date_local}'::text[]                        AS delivery_date_local,
    doc #>> '{fields,group_delivery_information,delivery_place}'::text[]                             AS delivery_place,
    doc #>> '{fields,group_delivery_information,delivery_place_other}'::text[]                       AS delivery_place_other,
    doc #>> '{fields,group_delivery_information,delivery_method}'::text[]                            AS delivery_method,
    doc #>> '{fields,group_delivery_information,who_conducted_delivery}'::text[]                     AS who_conducted_delivery,
    doc #>> '{fields,group_delivery_information,who_conducted_delivery_other}'::text[]                AS who_conducted_delivery_other,
    doc #>> '{fields,group_delivery_information,note_referred_to_health_facility_danger_signs}'::text[] AS note_referred_to_health_facility_danger_signs,
    doc #>> '{fields,group_delivery_information,referred_to_health_facility_home_delivery}'::text[]   AS referred_to_health_facility_home_delivery,
    doc #>> '{fields,group_delivery_information,agreed_health_facility_visit_date}'::text[]           AS agreed_health_facility_visit_date,
    
    doc #>> '{fields,group_death_report_baby,baby_date_of_death}'::text[]             AS baby_date_of_death,
    doc #>> '{fields,group_death_report_baby,baby_place_of_death}'::text[]            AS baby_place_of_death,
    doc #>> '{fields,group_death_report_baby,baby_place_of_death_other}'::text[]      AS baby_place_of_death_other,
    doc #>> '{fields,group_death_report_baby,still_birth}'::text[]                    AS still_birth,
    doc #>> '{fields,group_death_report_baby,baby_death_additional_notes}'::text[]    AS baby_death_additional_notes,
   
    doc #>> '{fields,group_woman_nutritional_status,note_nutrition_status}'::text[]                         AS note_nutrition_status,
    doc #>> '{fields,group_woman_nutritional_status,taken_muac}'::text[]                                    AS taken_muac,
    doc #>> '{fields,group_woman_nutritional_status,muac_measurement}'::text[]                              AS muac_measurement,
    doc #>> '{fields,group_woman_nutritional_status,encourage_client_to_consume_sufficient_diet}'::text[]   AS encourage_client_to_consume_sufficient_diet,
    doc #>> '{fields,group_woman_nutritional_status,note_has_sam}'::text[]                                  AS note_has_sam,
    doc #>> '{fields,group_woman_nutritional_status,note_has_mam}'::text[]                                  AS note_has_mam,
    doc #>> '{fields,group_woman_nutritional_status,note_refer_to_health_facility}'::text[]                 AS note_refer_to_health_facility,
    doc #>> '{fields,group_woman_nutritional_status,referred_to_health_facility_nutrition}'::text[]         AS referred_to_health_facility_nutrition,
    doc #>> '{fields,group_woman_nutritional_status,micro_nutrient_supplementation_received}'::text[]       AS micro_nutrient_supplementation_received,
    doc #>> '{fields,group_woman_nutritional_status,note_encourage_micro-nutrients}'::text[]                AS note_encourage_micro_nutrients,
    doc #>> '{fields,group_woman_nutritional_status,counsel_mother}'::text[]                                AS counsel_mother,
    doc #>> '{fields,group_woman_nutritional_status,referred_to_health_facility_no_micro_nutrient-supplementation}'::text[] AS referred_to_health_facility_no_micro_nutrient_supplementation,

    doc #>> '{fields,group_safe_postnatal_practices,note_eat_well}'::text[]                      AS note_eat_well,
    doc #>> '{fields,group_safe_postnatal_practices,note_exclusive_breastfeeding_counsel}'::text[]   AS note_exclusive_breastfeeding_counsel,
    doc #>> '{fields,group_safe_postnatal_practices,note_positioning_and_attachment}'::text[]         AS note_positioning_and_attachment,
    doc #>> '{fields,group_safe_postnatal_practices,note_how_to_keep_baby_warm}'::text[]              AS note_how_to_keep_baby_warm,
    doc #>> '{fields,group_safe_postnatal_practices,note_sleep_under_llin}'::text[]                   AS note_sleep_under_llin,
    doc #>> '{fields,group_safe_postnatal_practices,note_keep_umbilical_cord_clean}'::text[]          AS note_keep_umbilical_cord_clean,
    doc #>> '{fields,group_safe_postnatal_practices,note_introduce_age_appropiate_foods}'::text[]     AS note_introduce_age_appropiate_foods,
    doc #>> '{fields,group_safe_postnatal_practices,note_infants_receive_vitamin_a}'::text[]          AS note_infants_receive_vitamin_a,
    doc #>> '{fields,group_safe_postnatal_practices,note_micro_nutrient_supplements}'::text[]         AS note_micro_nutrient_supplements,
    doc #>> '{fields,group_safe_postnatal_practices,note_promote_early_childhood_stimulation}'::text[] AS note_promote_early_childhood_stimulation,
    doc #>> '{fields,group_safe_postnatal_practices,note_counsel_women_living_with_hiv}'::text[]      AS note_counsel_women_living_with_hiv,
    doc #>> '{fields,group_safe_postnatal_practices,note_hiv_exposed_infants}'::text[]                AS note_hiv_exposed_infants,
    doc #>> '{fields,group_safe_postnatal_practices,note_hiv_infected_infants}'::text[]               AS note_hiv_infected_infants,
    
    doc #>> '{fields,group_pnc_visits,who_recommendation}'::text[]             AS who_recommendation,
    doc #>> '{fields,group_pnc_visits,pnc_visits}'::text[]            AS pnc_visits,

  --- reporting hierarchy
    doc #>> '{contact,_id}'                         AS chw_id,
    h.facility_name,
    h.village,
    h.district,
    h.region,
    --delivery.is_current,


    CURRENT_TIMESTAMP AS last_refresh_date   

  FROM dwh.cht_data d
  LEFT JOIN cht.mv_chew_hierarchy_2 h
       ON (d.doc #>> '{contact,_id}') = h.chw_id
  WHERE (doc ->> 'form'::text) = 'delivery'::text 
  AND is_current = true
WITH DATA;

-- View indexes:
CREATE INDEX mv_delivery_reported ON cht.mv_delivery USING btree (reported);