-- cht.mv_anc_danger_sign_escalation source
DROP MATERIALIZED VIEW IF EXISTS cht.mv_anc_danger_sign_escalation;
CREATE MATERIALIZED VIEW cht.mv_anc_danger_sign_escalation
TABLESPACE ts_report
AS SELECT doc ->> '_id'::text AS uuid,
    doc ->> '_rev'::text AS rev,
    doc ->> 'form'::text AS form,
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    to_char(to_timestamp((((doc ->>'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS monthname,
    ((doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    (NULLIF((doc -> 'geolocation'::text) ->> 'latitude'::text, ''::text))::double precision AS geolocation_latitude,
    (NULLIF((doc -> 'geolocation'::text) ->> 'longitude'::text, ''::text))::double precision AS geolocation_longitude,
    (NULLIF((doc -> 'geolocation'::text) ->> 'accuracy'::text, ''::text))::double precision AS geolocation_accuracy,
    (NULLIF((doc -> 'geolocation'::text) ->> 'altitude'::text, ''::text))::double precision AS geolocation_altitude,
    (NULLIF((doc -> 'geolocation'::text) ->> 'altitudeAccuracy'::text, ''::text))::double precision AS geolocation_altitude_accuracy,
    (NULLIF((doc -> 'geolocation'::text) ->> 'speed'::text, ''::text))::double precision AS geolocation_speed,
    (NULLIF((doc -> 'geolocation'::text) ->> 'heading'::text, ''::text))::double precision AS geolocation_heading,
    doc ->> 'from'::text AS submitter,
    doc ->> 'content_type'::text AS top_content_type,
    to_timestamp((NULLIF(doc #>> '{form_version,time}'::text[], ''::text)::bigint::numeric / 1000.0)::double precision) AS form_version_time,
    doc #>> '{fields,inputs,user,contact_id}'::text[] AS user_contact_id,
    doc #>> '{fields,inputs,user,facility_id}'::text[] AS user_facility_id,
    doc #>> '{fields,inputs,contact,_id}'::text[] AS contact_id,
    doc #>> '{fields,inputs,contact,name}'::text[] AS contact_name,
    doc #>> '{fields,inputs,contact,sex}'::text[] AS contact_sex,
    doc #>> '{fields,inputs,contact,date_of_birth}'::text[] AS contact_date_of_birth,
    doc #>> '{fields,dob}'::text[] AS dob,
    doc #>> '{fields,patient_id}'::text[] AS patient_id,
    doc #>> '{fields,patient_name}'::text[] AS patient_name,
    doc #>> '{fields,patient_gender}'::text[] AS patient_gender,
    doc #>> '{fields,needs_signoff}'::text[] AS needs_signoff,
    doc #>> '{fields,patient_age_display}'::text[] AS patient_age,
    doc #>> '{fields,patient_age_in_days}'::text[] AS patient_age_in_days,
    doc #>> '{fields,patient_age_in_months}'::text[] AS patient_age_in_months,
    doc #>> '{fields,patient_age_in_years}'::text[] AS patient_age_in_years,
    doc #>> '{fields,inputs,t_place_name}'::text[] AS tvh_place_name,
    doc #>> '{fields,inputs,t_vht_name}'::text[] AS vht_name,
    doc #>> '{fields,inputs,t_vht_phone}'::text[] AS vht_vht_phone,
    doc #>> '{fields,inputs,t_pregnancy_danger_signs}'::text[] AS t_pregnancy_danger_signs,
    doc #>> '{fields,inputs,t_reduced_or_no_feotal_movements}'::text[] AS t_reduced_or_no_feotal_movements,
    doc #>> '{fields,inputs,t_fever}'::text[] AS t_fever,
    doc #>> '{fields,inputs,t_swelling}'::text[] AS t_swelling,
    doc #>> '{fields,inputs,t_very_pale}'::text[] AS t_very_pale,
    doc #>> '{fields,inputs,t_blurred_vision}'::text[] AS t_blurred_vision,
    doc #>> '{fields,inputs,t_breathlessness}'::text[] AS t_breathlessness,
    doc #>> '{fields,inputs,t_severe_headache}'::text[] AS t_severe_headache,
    doc #>> '{fields,inputs,t_vaginal_bleeding}'::text[] AS t_vaginal_bleeding,
    doc #>> '{fields,inputs,t_lower_abdomen_pain}'::text[] AS t_lower_abdomen_pain,
    doc #>> '{fields,inputs,t_patient_id}'::text[] AS t_patient_id,
    doc #>> '{fields,inputs,t_patient_name}'::text[] AS t_patient_name,
    doc #>> '{fields,inputs,t_patient_gender}'::text[] AS t_patient_gender,
    doc #>> '{fields,inputs,t_patient_date_of_birth}'::text[] AS t_patient_date_of_birth,
    doc #>> '{fields,action_taken,explain_vht_not_submit_referral}'::text[] AS explain_vht_not_submit_referral,
    doc #>> '{fields,action_taken,reason_vht_did_not_follow_up}'::text[] AS reason_vht_did_not_follow_up,
    doc #>> '{fields,action_taken,specify}'::text[] AS other_reson_specify,
    doc #>> '{fields,action_taken,vht_completed_referral_follow_up}'::text[] AS vht_completed_referral_follow_up,
    doc #>> '{fields,action_taken,call_chw}'::text[] AS action_call_chw,
    doc #>> '{fields,action_taken,call_button}'::text[] AS action_call_button,
    doc #>> '{fields,danger_signs,referral_signs}'::text[] AS danger_signs_referral_signs,
    doc #>> '{fields,danger_signs,vaginal_bleeding}'::text[] AS danger_signs_vaginal_bleeding,
    doc #>> '{fields,danger_signs,lower_abdomen_pain}'::text[] AS danger_signs_lower_abdomen_pain,
    doc #>> '{fields,danger_signs,severe_headache}'::text[] AS danger_signs_severe_headache,
    doc #>> '{fields,danger_signs,very_pale}'::text[] AS danger_signs_very_pale,
    doc #>> '{fields,danger_signs,fever}'::text[] AS danger_signs_fever,
    doc #>> '{fields,danger_signs,reduced_or_no_feotal_movements}'::text[] AS danger_signs_reduced_or_no_feotal_movements,
    doc #>> '{fields,danger_signs,blurred_vision}'::text[] AS danger_signs_blurred_vision,
    doc #>> '{fields,danger_signs,swelling}'::text[] AS danger_signs_swelling,
    doc #>> '{fields,danger_signs,breathlessness}'::text[] AS danger_signs_breathlessness,
    doc #>> '{contact,_id}'                         AS chw_id,
      h.facility,
      h.dhis2_facility_id,
      h.village,
      h.parish,
      h.district,
      h.region,
    CURRENT_TIMESTAMP AS last_refresh_date
   FROM dwh.cht_data couchdb
    LEFT JOIN cht.mv_chw_hierarchy h ON (couchdb.doc #>> '{contact,_id}') = h.chw_id
  WHERE (couchdb.doc ->> 'form'::text) = 'anc_danger_sign_escalation'::text AND couchdb.is_current
WITH NO DATA;

-- View indexes:
CREATE INDEX useview_anc_danger_sign_escalation_reported ON cht.mv_anc_danger_sign_escalation USING btree (reported) TABLESPACE ts_indexes;
CREATE INDEX useview_anc_danger_sign_escalation_chw_id ON cht.mv_anc_danger_sign_escalation USING btree (chw_id) TABLESPACE ts_indexes;
CREATE INDEX useview_anc_danger_sign_escalation_facility_id ON cht.mv_anc_danger_sign_escalation USING btree (facility) TABLESPACE ts_indexes;
CREATE INDEX useview_anc_danger_sign_escalation_district ON cht.mv_anc_danger_sign_escalation USING btree (district) TABLESPACE ts_indexes;
CREATE INDEX useview_anc_danger_sign_escalation_region ON cht.mv_anc_danger_sign_escalation USING btree (region) TABLESPACE ts_indexes;
CREATE INDEX useview_anc_danger_sign_escalation_date ON cht.mv_anc_danger_sign_escalation USING btree (date) TABLESPACE ts_indexes;
CREATE INDEX useview_anc_danger_sign_escalation_monthname ON cht.mv_anc_danger_sign_escalation USING btree (monthname) TABLESPACE ts_indexes;
CREATE INDEX mv_anc_danger_sign_escalation_year_month_district ON cht.mv_anc_danger_sign_escalation USING btree (year, month, district) TABLESPACE ts_indexes;
