-- cht.mv_anc_visit_follow_up source
DROP MATERIALIZED VIEW IF EXISTS cht.mv_anc_visit_follow_up;
CREATE MATERIALIZED VIEW cht.mv_anc_visit_follow_up
TABLESPACE ts_report
AS SELECT doc ->> '_id'::text AS uuid,
    doc ->> 'form'::text AS form,
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    to_char(to_timestamp((((doc ->>'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS monthname,
    ((doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    ((doc -> 'fields'::text) -> 'inputs'::text) ->> 'source'::text AS source,
    ((doc -> 'fields'::text) -> 'inputs'::text) ->> 'source_id'::text AS source_id,
    ((doc -> 'fields'::text) -> 'inputs'::text) ->> 'current_edd_std'::text AS current_edd_std,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) ->> '_id'::text AS inputs_contact_id,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) ->> 'name'::text AS contact_name,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) ->> 'date_of_birth'::text AS date_of_birth,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) ->> 'sex'::text AS sex,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) -> 'parent'::text) ->> '_id'::text AS parent_id,
    (doc -> 'fields'::text) ->> 'is_of_child_bearing_age'::text AS is_of_child_bearing_age,
    (doc -> 'fields'::text) ->> 'visited_contact_uuid'::text AS visited_contact_uuid,
    (doc -> 'fields'::text) ->> 'patient_age_in_years'::text AS patient_age_in_years,
    (doc -> 'fields'::text) ->> 'patient_age_in_months'::text AS patient_age_in_months,
    (doc -> 'fields'::text) ->> 'patient_age_in_days'::text AS patient_age_in_days,
    (doc -> 'fields'::text) ->> 'patient_age_display'::text AS patient_age_display,
    (doc -> 'fields'::text) ->> 'patient_id'::text AS patient_id,
    (doc -> 'fields'::text) ->> 'patient_name'::text AS patient_name,
    (doc -> 'fields'::text) ->> 'patient_name_with_s'::text AS patient_name_with_s,
    (doc -> 'fields'::text) ->> 'patient_gender'::text AS patient_gender,
    (doc -> 'fields'::text) ->> 'current_edd_local'::text AS current_edd_local,
    (doc -> 'fields'::text) ->> 'current_pregnancy_age_in_weeks'::text AS current_pregnancy_age_in_weeks,
    (doc -> 'fields'::text) ->> 'edd_std'::text AS edd_std,
    (doc -> 'fields'::text) ->> 'edd_local'::text AS edd_local,
    (doc -> 'fields'::text) ->> 'pregnancy_ended'::text AS pregnancy_ended,
    (doc -> 'fields'::text) ->> 'pregnancy_ended_label'::text AS pregnancy_ended_label,
    (doc -> 'fields'::text) ->> 'referred_for_nutrition_follow_up'::text AS referred_for_nutrition_follow_up,
    ((doc -> 'fields'::text) -> 'group_follow_up'::text) ->> 'assess_this_pregnancy'::text AS assess_this_pregnancy,
    ((doc -> 'fields'::text) -> 'group_follow_up'::text) ->> 'start_this_pregnancy'::text AS start_this_pregnancy,
    ((doc -> 'fields'::text) -> 'group_follow_up'::text) ->> 'possible_death_cause'::text AS possible_death_cause,
    ((doc -> 'fields'::text) -> 'group_follow_up'::text) ->> 'note_submit_death_report'::text AS note_submit_death_report,
    ((doc -> 'fields'::text) -> 'group_follow_up'::text) ->> 'new_follow_up_date'::text AS new_follow_up_date,
    ((doc -> 'fields'::text) -> 'group_follow_up'::text) ->> 'is_available'::text AS is_available,
    ((doc -> 'fields'::text) -> 'update_pregnancy'::text) ->> 'edd_upto_date'::text AS edd_upto_date,
    ((doc -> 'fields'::text) -> 'update_pregnancy'::text) ->> 'correct_edd'::text AS correct_edd,
    ((doc -> 'fields'::text) -> 'update_pregnancy'::text) ->> 'new_gestation_age_in_weeks'::text AS new_gestation_age_in_weeks,
    ((doc -> 'fields'::text) -> 'update_pregnancy'::text) ->> 'note_refer_for_miscarriage'::text AS note_refer_for_miscarriage,
    ((doc -> 'fields'::text) -> 'update_pregnancy'::text) ->> 'date_of_miscarriage'::text AS date_of_miscarriage,
    ((doc -> 'fields'::text) -> 'update_pregnancy'::text) ->> 'note_reported_abortion'::text AS note_reported_abortion,
    ((doc -> 'fields'::text) -> 'update_pregnancy'::text) ->> 'note_reported_refused_care'::text AS note_reported_refused_care,
    ((doc -> 'fields'::text) -> 'update_pregnancy'::text) ->> 'refused_care_action'::text AS refused_care_action,
    ((doc -> 'fields'::text) -> 'update_pregnancy'::text) ->> 'migrated_action'::text AS migrated_action,
    ((doc -> 'fields'::text) -> 'update_pregnancy'::text) ->> 'note_reported_migrated'::text AS note_reported_migrated,
    ((doc -> 'fields'::text) -> 'update_pregnancy'::text) ->> 'note_submit_delivery_report'::text AS note_submit_delivery_report,
    ((doc -> 'fields'::text) -> 'group_past_anc_visits'::text) ->> 'completed_scheduled_anc_visit'::text AS completed_scheduled_anc_visit,
    ((doc -> 'fields'::text) -> 'group_past_anc_visits'::text) ->> 'anc_visits'::text AS anc_visits,
    ((doc -> 'fields'::text) -> 'group_past_anc_visits'::text) ->> 'date_anc_1'::text AS date_anc_1,
    ((doc -> 'fields'::text) -> 'group_past_anc_visits'::text) ->> 'date_anc_2'::text AS date_anc_2,
    ((doc -> 'fields'::text) -> 'group_past_anc_visits'::text) ->> 'date_anc_3'::text AS date_anc_3,
    ((doc -> 'fields'::text) -> 'group_past_anc_visits'::text) ->> 'date_anc_4'::text AS date_anc_4,
    ((doc -> 'fields'::text) -> 'group_past_anc_visits'::text) ->> 'person_who_accompanied_expectant_mother'::text AS person_who_accompanied_expectant_mother,
    ((doc -> 'fields'::text) -> 'group_upcoming_anc_visits'::text) ->> 'anc_appointment_date'::text AS anc_appointment_date,
    ((doc -> 'fields'::text) -> 'group_upcoming_anc_visits'::text) ->> 'anc_appointment_date_local'::text AS anc_appointment_date_local,
    ((doc -> 'fields'::text) -> 'group_missed_anc_visits'::text) ->> 'why_missed_anc_visit'::text AS why_missed_anc_visit,
    ((doc -> 'fields'::text) -> 'group_missed_anc_visits'::text) ->> 'note_encourage_to_go_for_anc'::text AS note_encourage_to_go_for_anc,
    ((doc -> 'fields'::text) -> 'group_missed_anc_visits'::text) ->> 'missed_anc_actions_taken'::text AS missed_anc_actions_taken,
    ((doc -> 'fields'::text) -> 'group_missed_anc_visits'::text) ->> 'facility_visit_date_for_missed_anc'::text AS facility_visit_date_for_missed_anc,
    ((doc -> 'fields'::text) -> 'group_missed_anc_visits'::text) ->> 'facility_visit_date_for_missed_anc_local'::text AS facility_visit_date_for_missed_anc_local,
    ((doc -> 'fields'::text) -> 'group_missed_anc_visits'::text) ->> 'refer_to_health_facility'::text AS refer_to_health_facility,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'using_llin'::text AS using_llin,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_llin_prevents_malaria'::text AS note_llin_prevents_malaria,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'referred_to_health_facility_llin'::text AS referred_to_health_facility_llin,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'tested_for_hiv_past3months'::text AS tested_for_hiv_past3months,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'hiv_test_result'::text AS hiv_test_result,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'on_art_treatment'::text AS on_art_treatment,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_encourage_client_attend_art_clinic'::text AS note_encourage_client_attend_art_clinic,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'client_taking_medication'::text AS client_taking_medication,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_explain_importance_of_medication'::text AS note_explain_importance_of_medication,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_encourage_client_to_take_medication'::text AS note_encourage_client_to_take_medication,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_encourage_client_to_reduce_hiv_risk'::text AS note_encourage_client_to_reduce_hiv_risk,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_advise_client_to_check_status'::text AS note_advise_client_to_check_status,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'current_hiv_test_result'::text AS current_hiv_test_result,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_encourage_client_to_retest'::text AS note_encourage_client_to_retest,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_encourage_and_refer_to_health_facility'::text AS note_encourage_and_refer_to_health_facility,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'client_on_art_treatment'::text AS client_on_art_treatment,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_encourage_client_begin_treatment'::text AS note_encourage_client_begin_treatment,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'is_client_taking_medication'::text AS is_client_taking_medication,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_explain_importance_of_taking_medication'::text AS note_explain_importance_of_taking_medication,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_encourage_client_to_continue_taking_medication'::text AS note_encourage_client_to_continue_taking_medication,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'received_tt_immunization'::text AS received_tt_immunization,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_tt_immunization_importance'::text AS note_tt_immunization_importance,
    ((doc -> 'fields'::text) -> 'group_safe_pregnancy_practices'::text) ->> 'note_tt_vaccination_protocol'::text AS note_tt_vaccination_protocol,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'note_nutrition_status'::text AS note_nutrition_status,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'taken_muac'::text AS taken_muac,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'muac_measurement'::text AS muac_measurement,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'encourage_client_to_consume_sufficient_diet'::text AS encourage_client_to_consume_sufficient_diet,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'note_has_sam'::text AS note_has_sam,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'note_has_mam'::text AS note_has_mam,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'note_refer_to_health_facility'::text AS note_refer_to_health_facility,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'referred_to_health_facility_nutrition'::text AS referred_to_health_facility_nutrition,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'micro_nutrient_supplementation_received'::text AS micro_nutrient_supplementation_received,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'note_encourage_micro-nutrients'::text AS note_encourage_micro_nutrients,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'refer_to_health_facility_no_micro_nutrients'::text AS refer_to_health_facility_no_micro_nutrients,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'on_nutrition_follow_up'::text AS on_nutrition_follow_up,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'completed_last_nutrition_follow_up'::text AS completed_last_nutrition_follow_up,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'next_nutrition_follow_up_date'::text AS next_nutrition_follow_up_date,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'note_thank_you_nutrition_follow_up'::text AS note_thank_you_nutrition_follow_up,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'note_refer_did_not_complete_follow_up'::text AS note_refer_did_not_complete_follow_up,
    ((doc -> 'fields'::text) -> 'group_nutrition_status'::text) ->> 'referred_to_health_facility_missed_nutrition_follow_up'::text AS referred_to_health_facility_missed_nutrition_follow_up,
    doc #>> '{contact,_id}'                         AS chw_id,
      h.facility_name,
      h.dhis2_facility_id,
      h.village,
      h.district,
      h.region,
      CURRENT_TIMESTAMP                                 AS last_refresh_date 
   FROM dwh.cht_data couchdb
    LEFT JOIN cht.mv_chw_hierarchy h ON (couchdb.doc #>> '{contact,_id}') = h.chw_id

  WHERE (doc ->> 'form'::text) = 'anc_visit_follow_up'::text AND is_current
WITH DATA;

-- View indexes:
CREATE INDEX mv_anc_visit_follow_up_reported ON cht.mv_anc_visit_follow_up USING btree (reported);
CREATE INDEX mv_anc_visit_follow_up_chw_id ON cht.mv_anc_visit_follow_up USING btree (chw_id);
CREATE INDEX mv_anc_visit_follow_up_year_month ON cht.mv_anc_visit_follow_up USING btree (year, month);
CREATE INDEX mv_anc_visit_follow_up_date ON cht.mv_anc_visit_follow_up USING btree (date);
CREATE INDEX mv_anc_visit_follow_up_location ON cht.mv_anc_visit_follow_up USING btree (location_lat, location_long);
CREATE INDEX mv_anc_visit_follow_up_patient_id ON cht.mv_anc_visit_follow_up USING btree (patient_id);
CREATE INDEX mv_anc_visit_follow_up_visited_contact_uuid ON cht.mv_anc_visit_follow_up USING btree (visited_contact_uuid);
CREATE INDEX mv_anc_visit_follow_up_inputs_contact_id ON cht.mv_anc_visit_follow_up USING btree (inputs_contact_id);
CREATE INDEX mv_anc_visit_follow_up_parent_id ON cht.mv_anc_visit_follow_up USING btree (parent_id);