drop materialized view cht.mv_assessment;
CREATE MATERIALIZED VIEW cht.mv_assessment
TABLESPACE ts_report
AS
SELECT
    -- Standard fields (appear in all forms)
    doc ->> '_id'::text AS uuid,
    doc ->> 'form'::text AS form,
    doc ->> 'from'::text AS submitter,
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    to_char(to_timestamp((((doc ->>'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS monthname,
    doc ->'fields'->'meta'->>'instanceID' AS instanceID,
    doc ->'fields'->'inputs'->'meta'->>'deprecatedID' AS deprecatedID,
    doc ->'fields'->'inputs'->'meta'->'location'->>'lat' AS location_lat,
    doc ->'fields'->'inputs'->'meta'->'location'->>'long' AS location_long,
    doc ->'fields'->'inputs'->'meta'->'location'->>'error' AS location_error,
    doc ->'fields'->'inputs'->'meta'->'location'->>'message' AS location_message,
    doc ->'geolocation'->>'code' AS geolocation_code,
    doc ->'geolocation'->>'message' AS geolocation_message,

    -- Form-specific fields (from the XML)
    doc #>> '{fields,inputs,source}'::text[] AS inputs_source,
    doc #>> '{fields,inputs,source_id}'::text[] AS inputs_source_id,
    doc #>> '{fields,inputs,user,contact_id}'::text[] AS inputs_user_contact_id,
    doc #>> '{fields,inputs,user,facility_id}'::text[] AS inputs_user_facility_id,
    doc #>> '{fields,inputs,contact,_id}'::text[] AS inputs_contact_id,
    doc #>> '{fields,inputs,contact,name}'::text[] AS inputs_contact_name,
    doc #>> '{fields,inputs,contact,date_of_birth}'::text[] AS inputs_contact_date_of_birth,
    doc #>> '{fields,inputs,contact,sex}'::text[] AS inputs_contact_sex,
    doc #>> '{fields,inputs,contact,parent,_id}'::text[] AS inputs_contact_parent_id,
    doc #>> '{fields,inputs,contact,parent,name}'::text[] AS inputs_contact_parent_name,
    doc #>> '{fields,inputs,contact,parent,parent,_id}'::text[] AS inputs_contact_parent_parent_id,
    doc #>> '{fields,inputs,contact,parent,parent,name}'::text[] AS inputs_contact_parent_parent_name,
    doc #>> '{fields,inputs,contact,parent,parent,supervisor}'::text[] AS inputs_contact_parent_parent_supervisor,
    doc #>> '{fields,inputs,contact,parent,parent,phone}'::text[] AS inputs_contact_parent_parent_phone,
    doc #>> '{fields,inputs,contact,parent,parent,village}'::text[] AS inputs_contact_parent_parent_village,
    doc #>> '{fields,inputs,contact,parent,parent,contact,_id}'::text[] AS inputs_contact_parent_parent_contact_id,
    doc #>> '{fields,inputs,contact,parent,parent,contact,phone}'::text[] AS inputs_contact_parent_parent_contact_phone,
    doc #>> '{fields,inputs,contact,parent,parent,contact,name}'::text[] AS inputs_contact_parent_parent_contact_name,
    doc #>> '{fields,inputs,contact,parent,parent,parent,_id}'::text[] AS inputs_contact_parent_parent_parent_id,
    doc #>> '{fields,vaccines_received}'::text[] AS vaccines_received,
    doc #>> '{fields,vaccination_expected}'::text[] AS vaccination_expected,
    doc #>> '{fields,date_of_birth_local}'::text[] AS date_of_birth_local,
    doc #>> '{fields,visited_contact_uuid}'::text[] AS visited_contact_uuid,
    doc #>> '{fields,patient_age_in_years}'::text[] AS patient_age_in_years,
    doc #>> '{fields,patient_age_in_months}'::text[] AS patient_age_in_months,
    doc #>> '{fields,patient_age_in_days}'::text[] AS patient_age_in_days,
    doc #>> '{fields,patient_age_display}'::text[] AS patient_age_display,
    doc #>> '{fields,patient_id}'::text[] AS patient_id,
    doc #>> '{fields,patient_name}'::text[] AS patient_name,
    doc #>> '{fields,patient_gender}'::text[] AS patient_gender,
    doc #>> '{fields,recently_assessed}'::text[] AS recently_assessed,
    doc #>> '{fields,is_hiv_positive}'::text[] AS is_hiv_positive,
    doc #>> '{fields,lastDoseOfVitaminADate}'::text[] AS lastDoseOfVitaminADate,
    doc #>> '{fields,symptom_cough}'::text[] AS symptom_cough,
    doc #>> '{fields,symptom_indrawn_chest}'::text[] AS symptom_indrawn_chest,
    doc #>> '{fields,symptom_fast_breathing}'::text[] AS symptom_fast_breathing,
    doc #>> '{fields,symptom_diarrhoea}'::text[] AS symptom_diarrhoea,
    doc #>> '{fields,symptom_fever}'::text[] AS symptom_fever,
    doc #>> '{fields,num_of_mrdt_tests}'::text[] AS num_of_mrdt_tests,
    doc #>> '{fields,symptom_malaria_test}'::text[] AS symptom_malaria_test,
    doc #>> '{fields,referral_follow_up}'::text[] AS referral_follow_up,
    doc #>> '{fields,give_prereferral_treatment}'::text[] AS give_prereferral_treatment,
    doc #>> '{fields,given_prereferral_treatment}'::text[] AS given_prereferral_treatment,
    doc #>> '{fields,diagnosis_cough}'::text[] AS diagnosis_cough,
    doc #>> '{fields,chw_area_id}'::text[] AS chw_area_id,
    doc #>> '{fields,chw_area_name}'::text[] AS chw_area_name,
    doc #>> '{fields,chw_name}'::text[] AS chw_name,
    doc #>> '{fields,chw_phone}'::text[] AS chw_phone,
    doc #>> '{fields,chw_village}'::text[] AS chw_village,
    doc #>> '{fields,supervisor_id}'::text[] AS supervisor_id,
    doc #>> '{fields,branch_id}'::text[] AS branch_id,
    doc #>> '{fields,fever_treatment}'::text[] AS fever_treatment,
    doc #>> '{fields,cough_treatment}'::text[] AS cough_treatment,
    doc #>> '{fields,diarrhoea_treatment}'::text[] AS diarrhoea_treatment,
    doc #>> '{fields,act_prereferral_treatment_quantity}'::text[] AS act_prereferral_treatment_quantity,
    doc #>> '{fields,act_treatment_quantity}'::text[] AS act_treatment_quantity,
    doc #>> '{fields,act_given}'::text[] AS act_given,
    doc #>> '{fields,zinc_given}'::text[] AS zinc_given,
    doc #>> '{fields,amoxicillin_prereferral_treatment_quantity}'::text[] AS amoxicillin_prereferral_treatment_quantity,
    doc #>> '{fields,amoxicillin_treatment_quantity}'::text[] AS amoxicillin_treatment_quantity,
    doc #>> '{fields,amoxicillin_given}'::text[] AS amoxicillin_given,
    doc #>> '{fields,mrdt_given}'::text[] AS mrdt_given,
    doc #>> '{fields,rectal_given}'::text[] AS rectal_given,
    doc #>> '{fields,gloves_given}'::text[] AS gloves_given,
    doc #>> '{fields,diagnosis_diarrhoea}'::text[] AS diagnosis_diarrhoea,
    doc #>> '{fields,diagnosis_fever}'::text[] AS diagnosis_fever,
    doc #>> '{fields,treat_child_for_diagnosis}'::text[] AS treat_child_for_diagnosis,
    doc #>> '{fields,hiv_exposure_label}'::text[] AS hiv_exposure_label,
    doc #>> '{fields,tb_exposure_label}'::text[] AS tb_exposure_label,
    doc #>> '{fields,needs_signoff}'::text[] AS needs_signoff,
    doc #>> '{fields,should_escalate_nutrtion_referral_follow_up}'::text[] AS should_escalate_nutrtion_referral_follow_up,
    doc #>> '{fields,should_escalate_to_chew}'::text[] AS should_escalate_to_chew,
    doc #>> '{fields,group_vht_assessment_date,vht_assessment_date}'::text[] AS vht_vht_assessment_date,
    doc #>> '{fields,group_vht_assessment_date,note_date_of_birth}'::text[] AS vht_note_date_of_birth,
    doc #>> '{fields,group_vht_assessment_date,is_date_of_birth_correct}'::text[] AS vht_is_date_of_birth_correct,
    doc #>> '{fields,group_vht_assessment_date,note_update_correct_date_of_birth}'::text[] AS vht_note_update_correct_date_of_birth,
    doc #>> '{fields,group_danger_sign_screening,any_danger_signs}'::text[] AS gany_danger_signs,
    doc #>> '{fields,group_danger_sign_screening,child_has_danger_signs}'::text[] AS gchild_has_danger_signs,
    doc #>> '{fields,group_danger_sign_screening,refer_urgent_to_health_facility}'::text[] AS grefer_urgent_to_health_facility,
    doc #>> '{fields,group_cough,has_cough}'::text[] AS g_has_cough,
    doc #>> '{fields,group_cough,cough_duration}'::text[] AS g_cough_duration,
    doc #>> '{fields,group_cough,has_chest_indrawing}'::text[] AS g_has_chest_indrawing,
    doc #>> '{fields,group_cough,note_check_fast_breathing}'::text[] AS g_note_check_fast_breathing,
    doc #>> '{fields,group_cough,cough_danger_sign}'::text[] AS g_cough_danger_sign,
    doc #>> '{fields,group_breathing,note_press_timer}'::text[] AS g_note_press_timer,
    doc #>> '{fields,group_breathing,note_fast_breathing_depends_on}'::text[] AS g_note_fast_breathing_depends_on,
    doc #>> '{fields,group_breathing,breath_count}'::text[] AS g_breath_count,
    doc #>> '{fields,group_breathing,fast_breathing}'::text[] AS g_fast_breathing,
    doc #>> '{fields,group_breathing,fast_breathing_note_true}'::text[] AS g_fast_breathing_note_true,
    doc #>> '{fields,group_breathing,fast_breathing_note_false}'::text[] AS g_fast_breathing_note_false,
    doc #>> '{fields,group_diarrhoea,has_diarrhoea}'::text[] AS g_has_diarrhoea,
    doc #>> '{fields,group_diarrhoea,diarrhoea_duration}'::text[] AS g_diarrhoea_duration,
    doc #>> '{fields,group_diarrhoea,blood_in_stool}'::text[] AS g_blood_in_stool,
    doc #>> '{fields,group_diarrhoea,diarrhoea_danger_sign}'::text[] AS g_diarrhoea_danger_sign,
    doc #>> '{fields,group_fever,has_fever}'::text[] AS g_has_fever,
    doc #>> '{fields,group_fever,has_thermometer}'::text[] AS g_has_thermometer,
    doc #>> '{fields,group_fever,patient_temperature}'::text[] AS g_patient_temperature,
    doc #>> '{fields,group_fever,fever_duration}'::text[] AS g_fever_duration,
    doc #>> '{fields,group_fever,has_mrdt}'::text[] AS g_has_mrdt,
    doc #>> '{fields,group_fever,mrdt_repeat_count}'::text[] AS g_mrdt_repeat_count,
    doc #>> '{fields,group_fever,mrdt_repeat,note_do_mrdt}'::text[] AS g_mrdt_repeat_note_do_mrdt,
    doc #>> '{fields,group_fever,mrdt_repeat,mrdt_used_repeat}'::text[] AS g_mrdt_repeat_mrdt_used_repeat,
    doc #>> '{fields,group_fever,mrdt_repeat,after_blood_note_carestat}'::text[] AS g_mrdt_repeat_after_blood_note_carestat,
    doc #>> '{fields,group_fever,mrdt_repeat,after_blood_note_bioline}'::text[] AS g_mrdt_repeat_after_blood_note_bioline,
    doc #>> '{fields,group_fever,mrdt_repeat,mrdt_result_repeat}'::text[] AS g_mrdt_repeat_mrdt_result_repeat,
    doc #>> '{fields,group_fever,mrdt_repeat,why_mrdt_not_done_repeat}'::text[] AS g_mrdt_repeat_why_mrdt_not_done_repeat,
    doc #>> '{fields,group_fever,mrdt_repeat,note_mrdt_positive_repeat}'::text[] AS g_mrdt_repeat_note_mrdt_positive_repeat,
    doc #>> '{fields,group_fever,mrdt_repeat,note_mrdt_negative}'::text[] AS g_mrdt_repeat_note_mrdt_negative,
    doc #>> '{fields,group_fever,mrdt_repeat,note_mrdt_no_results}'::text[] AS g_mrdt_repeat_note_mrdt_no_results,
    doc #>> '{fields,group_fever,mrdt_repeat,note_encourage_client_to_take_mrdt}'::text[] AS g_mrdt_repeat_note_encourage_client_to_take_mrdt,
    doc #>> '{fields,group_fever,want_to_repeat_mrdt}'::text[] AS g_want_to_repeat_mrdt,
    doc #>> '{fields,group_fever,mrdt_result}'::text[] AS g_mrdt_result,
    doc #>> '{fields,group_fever,mrdt_used}'::text[] AS g_mrdt_used,
    doc #>> '{fields,group_fever,why_mrdt_not_done}'::text[] AS g_why_mrdt_not_done,
    doc #>> '{fields,group_fever,note_mrdt_positive}'::text[] AS g_note_mrdt_positive,
    doc #>> '{fields,group_fever,fever_danger_sign}'::text[] AS g_fever_danger_sign,
    doc #>> '{fields,group_hiv_tb,has_hiv_exposure}'::text[] AS g_has_hiv_exposure,
    doc #>> '{fields,group_hiv_tb,has_tb_exposure}'::text[] AS g_has_tb_exposure,
    doc #>> '{fields,group_malnutrition,acute_malnutrition_signs}'::text[] AS g_acute_malnutrition_signs,
    doc #>> '{fields,group_malnutrition,note_use_muac_tape}'::text[] AS g_note_use_muac_tape,
    doc #>> '{fields,group_malnutrition,muac_colour}'::text[] AS g_muac_colour,
    doc #>> '{fields,group_malnutrition,child_sam}'::text[] AS g_child_sam,
    doc #>> '{fields,group_malnutrition,child_mam}'::text[] AS g_child_mam,
    doc #>> '{fields,group_malnutrition,refer_to_health_facility}'::text[] AS g_refer_to_health_facility,
    doc #>> '{fields,group_malnutrition,referred_to_health_facility}'::text[] AS mal_referred_to_health_facility,
    doc #>> '{fields,group_malnutrition,assess_for_exclusive_breastfeeding}'::text[] AS g_assess_for_exclusive_breastfeeding,
        -- Continuation of form-specific fields (from the XML)
    doc #>> '{fields,group_malnutrition,encourage_to_give_balanced_diet}'::text[] AS g_encourage_to_give_balanced_diet,
    doc #>> '{fields,group_malnutrition,appears_too_small}'::text[] AS g_appears_too_small,
    doc #>> '{fields,group_malnutrition,malnutrition_danger_sign}'::text[] AS g_malnutrition_danger_sign,
    doc #>> '{fields,group_immunization,has_chc}'::text[] AS g_has_chc,
    doc #>> '{fields,group_immunization,note_vaccines_received}'::text[] AS g_note_vaccines_received,
    doc #>> '{fields,group_immunization,immunization_received}'::text[] AS g_immunization_received,
    doc #>> '{fields,group_immunization,immunization_uptodate}'::text[] AS g_immunization_uptodate,
    doc #>> '{fields,group_immunization,note_uptodate}'::text[] AS g_note_uptodate,
    doc #>> '{fields,group_immunization,note_not_uptodate}'::text[] AS g_note_not_uptodate,
    doc #>> '{fields,group_immunization,refer_immunization_ack}'::text[] AS g_refer_immunization_ack,
    doc #>> '{fields,group_immunization,note_encourage_imm}'::text[] AS g_note_encourage_imm,
    doc #>> '{fields,group_immunization,afp_vpd}'::text[] AS g_afp_vpd,
    doc #>> '{fields,group_immunization,refer_afp_ack}'::text[] AS g_refer_afp_ack,
    doc #>> '{fields,group_other_information,exclusive_breast_feeding}'::text[] AS g_exclusive_breast_feeding,
    doc #>> '{fields,group_other_information,reason_child_not_breastfeeding}'::text[] AS g_reason_child_not_breastfeeding,
    doc #>> '{fields,group_other_information,not_breastfeeding_reason_other}'::text[] AS g_not_breastfeeding_reason_other,
    doc #>> '{fields,group_other_information,referred_to_health_facility}'::text[] AS other_referred_to_health_facility,
    doc #>> '{fields,group_other_information,still_breastfeeding}'::text[] AS g_still_breastfeeding,
    doc #>> '{fields,group_other_information,note_counsel_and_educate}'::text[] AS g_note_counsel_and_educate,
    doc #>> '{fields,group_other_information,note_educate_mother}'::text[] AS g_note_educate_mother,
    doc #>> '{fields,group_other_information,walking_or_crawling}'::text[] AS g_walking_or_crawling,
    doc #>> '{fields,group_other_information,note_educate_caregiver}'::text[] AS g_note_educate_caregiver,
    doc #>> '{fields,group_other_information,child_been_dewormed}'::text[] AS g_child_been_dewormed,
    doc #>> '{fields,group_other_information,note_vitamin_a}'::text[] AS g_note_vitamin_a,
    doc #>> '{fields,group_other_information,received_vitamin_a}'::text[] AS g_received_vitamin_a,
    doc #>> '{fields,group_other_information,last_vitamin_A_date}'::text[] AS g_last_vitamin_A_date,
    doc #>> '{fields,group_other_information,refer_to_health_facility_no_vitamin_a}'::text[] AS g_refer_to_health_facility_no_vitamin_a,
    doc #>> '{fields,group_other_information,note_vitamin_a_advice}'::text[] AS g_note_vitamin_a_advice,
    doc #>> '{fields,group_routine_care,wrap_baby_warm}'::text[] AS g_wrap_baby_warm,
    doc #>> '{fields,group_routine_care,skin_cord_care}'::text[] AS g_skin_cord_care,
    doc #>> '{fields,group_routine_care,breastfeeding_exclusively}'::text[] AS g_breastfeeding_exclusively,
    doc #>> '{fields,group_routine_care,wash_hands_before_handling_baby}'::text[] AS g_wash_hands_before_handling_baby,
    doc #>> '{fields,group_routine_care,bathe_baby_clean_water}'::text[] AS g_bathe_baby_clean_water,
    doc #>> '{fields,group_routine_care,do_not_apply_anything_on_cord}'::text[] AS g_do_not_apply_anything_on_cord,
    doc #>> '{fields,group_routine_care,start_breastfeeding_immediately}'::text[] AS g_start_breastfeeding_immediately,
    doc #>> '{fields,group_routine_care,feed_the_baby}'::text[] AS g_feed_the_baby,
    doc #>> '{fields,group_routine_care,ensure_baby_well_positioned}'::text[] AS g_ensure_baby_well_positioned,
    doc #>> '{fields,group_patient_summary,have_you_referred}' AS have_you_referred,
    -- Last column for tracking refresh
    doc #>> '{contact,_id}'                         AS chw_id,
      h.facility,
      h.village,
      h.district,
      h.region,
      CURRENT_TIMESTAMP                                 AS last_refresh_date     

FROM dwh.cht_data d
LEFT JOIN cht.mv_chw_hierarchy h
  ON (d.doc #>> '{contact,_id}') = h.chw_id 

WHERE (doc ->> 'form'::text) = 'assessment'::text
  AND is_current
WITH NO DATA;

-- Indexes
CREATE INDEX mv_assessment_reported
    ON cht.mv_assessment USING btree (reported) TABLESPACE ts_indexes;
CREATE INDEX mv_assessment_patient_id
    ON cht.mv_assessment USING btree (patient_id) TABLESPACE ts_indexes;
CREATE INDEX mv_assessment_chw_id
    ON cht.mv_assessment USING btree (chw_id) TABLESPACE ts_indexes;
CREATE INDEX mv_assessment_year_month
    ON cht.mv_assessment USING btree (year, month) TABLESPACE ts_indexes;
CREATE INDEX mv_assessment_date
    ON cht.mv_assessment USING btree (date) TABLESPACE ts_indexes;
-- Org hierarchy
CREATE INDEX mv_assessment_region_district_facility
ON cht.mv_assessment (region, district, facility) TABLESPACE ts_indexes;

CREATE INDEX mv_assessment_district
ON cht.mv_assessment (district) TABLESPACE ts_indexes;

CREATE INDEX mv_assessment_district_facility
ON cht.mv_assessment (district, facility) TABLESPACE ts_indexes;

-- High-impact (MOST IMPORTANT)
CREATE INDEX mv_assessment_year_month_district
ON cht.mv_assessment (year, month, district) TABLESPACE ts_indexes;

