-- cht.mv_community_death_notification source
DrOP MATERIALIZED VIEW IF EXISTS cht.mv_community_death_notification;
CREATE MATERIALIZED VIEW cht.mv_community_death_notification
TABLESPACE ts_report
AS SELECT d.doc ->> '_id'::text AS uuid,
    d.doc ->> 'form'::text AS form,
    d.doc ->> 'from'::text AS submitter,
    to_timestamp((NULLIF(d.doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'YYYY-MM-DD'::text)::date AS date,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'YYYY'::text)::integer AS year,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'FMMonth'::text) AS monthname,
    ((d.doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (d.doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (d.doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'latitude'::text, ''::text))::double precision AS geolocation_latitude,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'longitude'::text, ''::text))::double precision AS geolocation_longitude,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'accuracy'::text, ''::text))::double precision AS geolocation_accuracy,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'altitude'::text, ''::text))::double precision AS geolocation_altitude,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'altitudeAccuracy'::text, ''::text))::double precision AS geolocation_altitude_accuracy,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'speed'::text, ''::text))::double precision AS geolocation_speed,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'heading'::text, ''::text))::double precision AS geolocation_heading,
    h.chw_name AS chw_name,
    h.phone,
    h.role,
    ((d.doc -> 'fields'::text) -> 'inputs'::text) ->> 'source'::text AS source,
    ((d.doc -> 'fields'::text) -> 'inputs'::text) ->> 'source_id'::text AS source_id,
    (((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) ->> '_id'::text AS contact_id,
    (((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) ->> 'name'::text AS contact_name,
    (((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) ->> 'date_of_birth'::text AS contact_date_of_birth,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'head_household_name'::text AS head_household_name,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'head_household_contact'::text AS head_household_contact,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'mother_name'::text AS mother_name,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'mother_dob'::text AS mother_dob,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'mother_age'::text AS mother_age,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'mother_pregnanies'::text AS mother_pregnanies,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'mother_village'::text AS mother_village,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'Woman_parish'::text AS woman_parish,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'Woman_subcounty'::text AS woman_subcounty,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'Woman_district'::text AS woman_district,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'Woman_Usual_Res'::text AS woman_usual_residence,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'Woman_Temp_village'::text AS woman_temporary_village,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'Woman_Temp_Parish'::text AS woman_temporary_parish,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'Woman_Temp_subcounty'::text AS woman_temporary_subcounty,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'Woman_Temp_District'::text AS woman_temporary_district,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'Informer_name'::text AS informer_name,
    ((d.doc -> 'fields'::text) -> 'reporter_info'::text) ->> 'Informer_contact'::text AS informer_contact,
    ((d.doc -> 'fields'::text) -> 'death_type'::text) ->> 'death_category'::text AS death_category,
    ((d.doc -> 'fields'::text) -> 'mothers_details'::text) ->> 'mother_death_timing'::text AS mother_death_timing,
    ((d.doc -> 'fields'::text) -> 'mothers_details'::text) ->> 'Woman_Nationality'::text AS woman_nationality,
    ((d.doc -> 'fields'::text) -> 'mothers_details'::text) ->> 'mother_date_of_death'::text AS mother_date_of_death,
    ((d.doc -> 'fields'::text) -> 'mothers_details'::text) ->> 'mother_time_of_death'::text AS mother_time_of_death,
    ((d.doc -> 'fields'::text) -> 'mothers_details'::text) ->> 'MD_Weeks'::text AS maternal_death_weeks,
    ((d.doc -> 'fields'::text) -> 'mothers_details'::text) ->> 'mother_days_after_delivery'::text AS mother_days_after_delivery,
    ((d.doc -> 'fields'::text) -> 'mothers_details'::text) ->> 'mother_place_of_death'::text AS mother_place_of_death,
    ((d.doc -> 'fields'::text) -> 'mothers_details'::text) ->> 'MD_Place_Spec'::text AS maternal_death_place,
    ((d.doc -> 'fields'::text) -> 'mothers_details'::text) ->> 'mother_cause_of_death'::text AS mother_cause_of_death,
    ((d.doc -> 'fields'::text) -> 'mothers_details'::text) ->> 'MD_Carer'::text AS carer_for_mother_before_death,
    ((d.doc -> 'fields'::text) -> 'mothers_details'::text) ->> 'MD_Carer_Rel'::text AS carer_relationship_to_mother,
    ((d.doc -> 'fields'::text) -> 'mothers_details'::text) ->> 'MD_Carer_Contact'::text AS carer_contact,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'baby_place_of_birth'::text AS baby_place_of_birth,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'baby_sex'::text AS baby_sex,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'baby_birth_date'::text AS baby_birth_date,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'baby_birth_time'::text AS baby_birth_time,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'baby_death_date'::text AS baby_death_date,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'baby_death_time'::text AS baby_death_time,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'NND_24'::text AS neonatal_death_24,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'NND_age_H'::text AS neonatal_age_hours,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'NND_age_days'::text AS neonatal_death_age_days,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'baby_place_of_death'::text AS baby_place_of_death,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'NND_place_Spec'::text AS neonatal_death_place,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'NND_Cause'::text AS neonatal_death_cause,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'NND_Mother'::text AS neonate_with_mother,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'NND_carer'::text AS neonate_with_carer,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'NND_carer_contact'::text AS neonate_with_carer_contact,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'baby_multiple_pregnancy'::text AS baby_multiple_pregnancy,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'baby_multiple_howmany'::text AS baby_multiple_howmany,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'NND_other_death'::text AS neonatal_other_death,
    ((d.doc -> 'fields'::text) -> 'baby_details'::text) ->> 'other_babies_alive'::text AS other_babies_alive,
    ((d.doc -> 'fields'::text) -> 'baby_details_stillbirth'::text) ->> 'SB_date'::text AS still_birth_date,
    ((d.doc -> 'fields'::text) -> 'baby_details_stillbirth'::text) ->> 'SB_time'::text AS still_birth_time,
    ((d.doc -> 'fields'::text) -> 'baby_details_stillbirth'::text) ->> 'SB_sex'::text AS still_birth_sex,
    ((d.doc -> 'fields'::text) -> 'baby_details_stillbirth'::text) ->> 'SB_place'::text AS still_birth_place,
    ((d.doc -> 'fields'::text) -> 'baby_details_stillbirth'::text) ->> 'SB_place_spec'::text AS still_birth_place_spec,
    ((d.doc -> 'fields'::text) -> 'baby_details_stillbirth'::text) ->> 'Comment'::text AS comment,
    doc #>> '{contact,_id}'                         AS chw_id,
      h.facility,
      h.dhis2_facility_id,
      h.village,
      h.district,
      h.region,
      CURRENT_TIMESTAMP                                 AS last_refresh_date 
   FROM dwh.cht_data d
     LEFT JOIN cht.mv_chw_hierarchy h ON (d.doc #>> '{contact,_id}') = h.chw_id
  WHERE (d.doc ->> 'form'::text) = 'community_death_notification'::text AND d.is_current
WITH NO DATA;

-- View indexes:
CREATE INDEX mv_community_death_notification_chw ON cht.mv_community_death_notification USING btree (chw_id) tablespace ts_indexes;
CREATE INDEX mv_community_death_notification_reported ON cht.mv_community_death_notification USING btree (reported) tablespace ts_indexes;
CREATE INDEX mv_community_death_notification_year_month_district ON cht.mv_community_death_notification USING btree (year, month, district) TABLESPACE ts_indexes;
CREATE INDEX mv_community_death_notification_district ON cht.mv_community_death_notification USING btree (district) tablespace ts_indexes;
CREATE INDEX mv_community_death_notification_source ON cht.mv_community_death_notification USING btree (source) tablespace ts_indexes;
CREATE INDEX mv_community_death_notification_source_id ON cht.mv_community_death_notification USING btree (source_id) tablespace ts_indexes;
CREATE INDEX mv_community_death_notification_contact_id ON cht.mv_community_death_notification USING btree (contact_id) tablespace ts_indexes;
CREATE INDEX mv_community_death_notification_chw_district ON cht.mv_community_death_notification USING btree (chw_id, district) tablespace ts_indexes;
CREATE INDEX mv_community_death_notification_chw_district_reported ON cht.mv_community_death_notification USING btree (chw_id, district, reported) tablespace ts_indexes;
