-- cht.mv_death_notification source
DROP MATERIALIZED VIEW IF EXISTS cht.mv_death_notification;
CREATE MATERIALIZED VIEW cht.mv_death_notification
TABLESPACE ts_report
AS SELECT doc ->> '_id'::text AS uuid,
    doc ->> 'form'::text AS form,
    doc ->> 'from'::text AS submitter,
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    to_char(to_timestamp((((doc ->>'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS monthname,
    ((doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    (NULLIF((doc -> 'geolocation'::text) ->> 'latitude'::text, ''::text))::double precision AS geolocation_latitude,
    (NULLIF((doc -> 'geolocation'::text) ->> 'longitude'::text, ''::text))::double precision AS geolocation_longitude,
    (NULLIF((doc -> 'geolocation'::text) ->> 'accuracy'::text, ''::text))::double precision AS geolocation_accuracy,
    (NULLIF((doc -> 'geolocation'::text) ->> 'altitude'::text, ''::text))::double precision AS geolocation_altitude,
    (NULLIF((doc -> 'geolocation'::text) ->> 'altitudeAccuracy'::text, ''::text))::double precision AS geolocation_altitude_accuracy,
    (NULLIF((doc -> 'geolocation'::text) ->> 'speed'::text, ''::text))::double precision AS geolocation_speed,
    (NULLIF((doc -> 'geolocation'::text) ->> 'heading'::text, ''::text))::double precision AS geolocation_heading,
    doc #>> '{fields,inputs,source}'::text[] AS inputs_source,
    doc #>> '{fields,inputs,source_id}'::text[] AS inputs_source_id,
    doc #>> '{fields,inputs,t_client_death_date}'::text[] AS inputs_t_client_death_date,
    doc #>> '{fields,inputs,t_client_birth_date}'::text[] AS inputs_t_client_birth_date,
    doc #>> '{fields,inputs,t_client_name}'::text[] AS inputs_t_client_name,
    doc #>> '{fields,inputs,t_client_id}'::text[] AS inputs_t_client_id,
    doc #>> '{fields,inputs,t_client_national_identification_number}'::text[] AS inputs_t_client_national_identification_number,
    doc #>> '{fields,inputs,t_client_sex}'::text[] AS inputs_t_client_sex,
    doc #>> '{fields,inputs,t_client_age}'::text[] AS inputs_t_client_age,
    doc #>> '{fields,inputs,t_client_death_report_date}'::text[] AS inputs_t_client_death_report_date,
    doc #>> '{fields,inputs,t_client_place_of_death}'::text[] AS inputs_t_client_place_of_death,
    doc #>> '{fields,inputs,t_client_place_of_death_other}'::text[] AS inputs_t_client_place_of_death_other,
    doc #>> '{fields,inputs,t_client_cause_of_death}'::text[] AS inputs_t_client_cause_of_death,
    doc #>> '{fields,inputs,t_user_contact_id}'::text[] AS inputs_t_user_contact_id,
    doc #>> '{fields,inputs,t_user_name}'::text[] AS inputs_t_user_name,
    doc #>> '{fields,inputs,t_user_phone}'::text[] AS inputs_t_user_phone,
    doc #>> '{fields,inputs,user,contact_id}'::text[] AS inputs_user_contact_id,
    doc #>> '{fields,inputs,contact,_id}'::text[] AS inputs_contact_id,
    doc #>> '{fields,inputs,contact,name}'::text[] AS inputs_contact_name,
    doc #>> '{fields,inputs,contact,date_of_birth}'::text[] AS inputs_contact_date_of_birth,
    doc #>> '{fields,inputs,contact,sex}'::text[] AS inputs_contact_sex,
    doc #>> '{fields,inputs,contact,parent,_id}'::text[] AS inputs_contact_parent_id,
    doc #>> '{fields,inputs,contact,parent,parent,_id}'::text[] AS inputs_contact_parent_parent_id,
    doc #>> '{fields,health_center_id}'::text[] AS health_center_id,
    doc #>> '{fields,supervisor_id}'::text[] AS supervisor_id,
    doc #>> '{fields,patient_id}'::text[] AS patient_id,
    doc #>> '{fields,needs_signoff}'::text[] AS needs_signoff,
    doc #>> '{fields,date_of_death}'::text[] AS date_of_death,
    doc #>> '{fields,notification_details,user_details}'::text[] AS notification_details_user_details,
    doc #>> '{fields,notification_details,client_details}'::text[] AS notification_details_client_details,
    doc #>> '{fields,notification_details,death_details}'::text[] AS notification_details_death_details,
    doc #>> '{fields,notification_details,note_call_vht}'::text[] AS notification_details_note_call_vht,
    doc #>> '{fields,notification_details,call_button}'::text[] AS notification_details_call_button,
    doc #>> '{fields,notification_details,call_summary}'::text[] AS notification_details_call_summary,
    doc #>> '{fields,notification_details,verification_status}'::text[] AS notification_details_verification_status,
    doc #>> '{fields,notification_details,death_not_verified_reason}'::text[] AS notification_details_death_not_verified_reason,
    doc #>> '{fields,notification_details,not_verified_vht_note}'::text[] AS notification_details_not_verified_vht_note,
    doc #>> '{fields,notification_details,actions}'::text[] AS notification_details_actions,
    doc #>> '{fields,notification_details,action_others}'::text[] AS notification_details_action_others,
    doc #>> '{fields,notification_details,action_note}'::text[] AS notification_details_action_note,
    doc #>> '{fields,status}'::text[] AS submission_status,
    doc #>> '{fields,death_report}'::text[] AS submission_death_report,
    doc #>> '{fields,place_id}'::text[] AS submission_place_id,
    doc #>> '{fields,needs_signoff}'::text[] AS submission_needs_signoff,
    doc #>> '{fields,date_of_death}'::text[] AS submission_date_of_death,
    doc #>> '{fields,d_client_death_date}'::text[] AS submission_d_client_death_date,
    doc #>> '{fields,d_client_birth_date}'::text[] AS submission_d_client_birth_date,
    doc #>> '{fields,d_client_name}'::text[] AS submission_d_client_name,
    doc #>> '{fields,d_client_id}'::text[] AS submission_d_client_id,
    doc #>> '{fields,d_client_national_identification_number}'::text[] AS submission_d_client_national_identification_number,
    doc #>> '{fields,d_client_sex}'::text[] AS submission_d_client_sex,
    doc #>> '{fields,d_client_age}'::text[] AS submission_d_client_age,
    doc #>> '{fields,d_client_death_report_date}'::text[] AS submission_d_client_death_report_date,
    doc #>> '{fields,d_client_place_of_death}'::text[] AS submission_d_client_place_of_death,
    doc #>> '{fields,d_client_place_of_death_other}'::text[] AS submission_d_client_place_of_death_other,
    doc #>> '{fields,d_client_cause_of_death}'::text[] AS submission_d_client_cause_of_death,
    doc #>> '{fields,d_user_contact_id}'::text[] AS submission_d_user_contact_id,
    doc #>> '{fields,d_user_name}'::text[] AS submission_d_user_name,
    doc #>> '{fields,d_user_phone}'::text[] AS submission_d_user_phone,
    doc #>> '{contact,_id}'                         AS chw_id,
      h.facility,
      h.dhis2_facility_id,
      h.village,
      h.district,
      h.region,
      CURRENT_TIMESTAMP                                 AS last_refresh_date 
   FROM dwh.cht_data couchdb
LEFT JOIN cht.mv_chw_hierarchy h ON (couchdb.doc #>> '{contact,_id}') = h.chw_id
  WHERE (doc ->> 'form'::text) = 'death_notification'::text AND is_current
WITH NO DATA;

-- View indexes:
CREATE INDEX mv_death_notification_chw_id ON cht.mv_death_notification USING btree (chw_id) tablespace ts_indexes;
CREATE INDEX mv_death_notification_reported ON cht.mv_death_notification USING btree (reported) tablespace ts_indexes;
CREATE INDEX mv_death_notification_year_month_district ON cht.mv_death_notification USING btree (year, month, district) TABLESPACE ts_indexes;