-- cht.mv_delivery source
DROP MATERIALIZED VIEW cht.mv_delivery;
CREATE MATERIALIZED VIEW cht.mv_delivery
TABLESPACE ts_report
AS SELECT d.doc ->> '_id'::text AS uuid,
    d.doc ->> '_rev'::text AS rev,
    to_timestamp((NULLIF(d.doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'YYYY-MM-DD'::text)::date AS date,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'YYYY'::text)::integer AS year,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'FMMonth'::text) AS monthname,
    ((d.doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (d.doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (d.doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    d.doc #>> '{fields,inputs,source_id}'::text[] AS source_id,
    d.doc #>> '{fields,inputs,source}'::text[] AS source,
    d.doc ->> 'form'::text AS form,
    d.doc #>> '{fields,inputs,contact,_id}'::text[] AS inputs_contact_id,
    d.doc #>> '{fields,inputs,contact,sex}'::text[] AS inputs_contact_sex,
    d.doc #>> '{fields,inputs,contact,name}'::text[] AS inputs_contact_name,
    d.doc #>> '{fields,inputs,contact,date_of_birth}'::text[] AS inputs_contact_date_of_birth,
    d.doc #>> '{fields,is_of_child_bearing_age}'::text[] AS is_of_child_bearing_age,
    d.doc #>> '{fields,visited_contact_uuid}'::text[] AS visited_contact_uuid,
    d.doc #>> '{fields,family_id}'::text[] AS family_id,
    d.doc #>> '{fields,area_id}'::text[] AS area_id,
    d.doc #>> '{fields,facility_id}'::text[] AS facility_id,
    d.doc #>> '{fields,patient_age_in_years}'::text[] AS patient_age_in_years,
    d.doc #>> '{fields,patient_age_in_months}'::text[] AS patient_age_in_months,
    d.doc #>> '{fields,patient_age_in_days}'::text[] AS patient_age_in_days,
    d.doc #>> '{fields,patient_age_display}'::text[] AS patient_age_display,
    d.doc #>> '{fields,patient_id}'::text[] AS patient_id,
    d.doc #>> '{fields,patient_name}'::text[] AS patient_name,
    d.doc #>> '{fields,patient_gender}'::text[] AS patient_gender,
    d.doc #>> '{fields,today_date}'::text[] AS today_date,
    d.doc #>> '{fields,days_since_delivery_date}'::text[] AS days_since_delivery_date,
    d.doc #>> '{fields,referred_for_nutrition_follow_up}'::text[] AS referred_for_nutrition_follow_up,
    d.doc #>> '{fields,delivery_place_label}'::text[] AS delivery_place_label,
    d.doc #>> '{fields,pregnancy_hiv_test_result}'::text[] AS pregnancy_hiv_test_result,
    d.doc #>> '{fields,group_woman_condition,woman_outcome}'::text[] AS woman_outcome,
    d.doc #>> '{fields,group_delivery_outcomes,number_of_babies_delivered}'::text[] AS number_of_babies_delivered,
    d.doc #>> '{fields,group_delivery_outcomes,number_of_babies_alive}'::text[] AS number_of_babies_alive,
    d.doc #>> '{fields,group_woman_danger_sign_check,note_title_danger_sign}'::text[] AS note_title_danger_sign,
    d.doc #>> '{fields,group_woman_danger_sign_check,note_has_any_danger_signs_woman}'::text[] AS note_has_any_danger_signs_woman,
    d.doc #>> '{fields,group_woman_danger_sign_check,woman_danger_sign_fever}'::text[] AS woman_danger_sign_fever,
    d.doc #>> '{fields,group_woman_danger_sign_check,woman_danger_sign_severe_headache}'::text[] AS woman_danger_sign_severe_headache,
    d.doc #>> '{fields,group_woman_danger_sign_check,woman_danger_sign_vaginal_bleeding}'::text[] AS woman_danger_sign_vaginal_bleeding,
    d.doc #>> '{fields,group_woman_danger_sign_check,woman_danger_sign_foul_vaginal_discharge}'::text[] AS woman_danger_sign_foul_vaginal_discharge,
    d.doc #>> '{fields,group_woman_danger_sign_check,woman_danger_sign_convulsions}'::text[] AS woman_danger_sign_convulsions,
    d.doc #>> '{fields,group_woman_danger_sign_check,has_danger_signs_woman}'::text[] AS has_danger_signs_woman,
    d.doc #>> '{fields,group_woman_danger_sign_check,note_refer_woman_danger_signs}'::text[] AS note_refer_woman_danger_signs,
    d.doc #>> '{fields,group_woman_danger_sign_check,referred_woman_danger_signs}'::text[] AS referred_woman_danger_signs,
    d.doc #>> '{fields,group_woman_danger_sign_check,woman_date_of_death}'::text[] AS woman_date_of_death,
    d.doc #>> '{fields,group_woman_danger_sign_check,woman_place_of_death}'::text[] AS woman_place_of_death,
    d.doc #>> '{fields,group_woman_danger_sign_check,woman_place_of_death_other}'::text[] AS woman_place_of_death_other,
    d.doc #>> '{fields,group_woman_danger_sign_check,delivered_babies_before_dying}'::text[] AS delivered_babies_before_dying,
    d.doc #>> '{fields,group_woman_danger_sign_check,woman_dead_additional_notes}'::text[] AS woman_dead_additional_notes,
    d.doc #>> '{fields,group_woman_danger_sign_check,note_woman_dead_notes_detailed}'::text[] AS note_woman_dead_notes_detailed,
    d.doc #>> '{fields,group_woman_danger_sign_check,note_encourage_kangaroo_fathers}'::text[] AS note_encourage_kangaroo_fathers,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,name}'::text[] AS name,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,sex}'::text[] AS sex,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,type}'::text[] AS type,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,parent,_id}'::text[] AS house_hold_id,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_name}'::text[] AS baby_name,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,mother_id}'::text[] AS mother_id,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,date_of_birth}'::text[] AS date_of_birth,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_condition}'::text[] AS baby_condition,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,created_by_doc}'::text[] AS created_by_doc,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,has_danger_signs_baby}'::text[] AS has_danger_signs_baby,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_body}'::text[] AS baby_danger_sign_body,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_fever}'::text[] AS baby_danger_sign_fever,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_drowsy}'::text[] AS baby_danger_sign_drowsy,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,breastfed_within_one_hour}'::text[] AS breastfed_within_one_hour,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_blue_skin}'::text[] AS baby_danger_sign_blue_skin,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,note_any_baby_danger_signs}'::text[] AS note_any_baby_danger_signs,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_yellow_skin}'::text[] AS baby_danger_sign_yellow_skin,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,is_exclusively_breast_feeding}'::text[] AS is_exclusively_breast_feeding,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_body_stiffness}'::text[] AS baby_danger_sign_body_stiffness,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_vomits_everything}'::text[] AS baby_danger_sign_vomits_everything,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_infected_convulsions}'::text[] AS baby_danger_sign_infected_convulsions,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_infected_umbilical_cord}'::text[] AS baby_danger_sign_infected_umbilical_cord,
    d.doc #>> '{fields,group_baby_condition,child_repeat,0,child_profile,baby_danger_sign_infected_feeding_difficulty}'::text[] AS baby_danger_sign_infected_feeding_difficulty,
    d.doc #>> '{fields,group_delivery_information,delivery_date}'::text[] AS delivery_date,
    d.doc #>> '{fields,group_delivery_information,delivery_date_local}'::text[] AS delivery_date_local,
    d.doc #>> '{fields,group_delivery_information,delivery_place}'::text[] AS delivery_place,
    d.doc #>> '{fields,group_delivery_information,delivery_place_other}'::text[] AS delivery_place_other,
    d.doc #>> '{fields,group_delivery_information,delivery_method}'::text[] AS delivery_method,
    d.doc #>> '{fields,group_delivery_information,who_conducted_delivery}'::text[] AS who_conducted_delivery,
    d.doc #>> '{fields,group_delivery_information,who_conducted_delivery_other}'::text[] AS who_conducted_delivery_other,
    d.doc #>> '{fields,group_delivery_information,note_referred_to_health_facility_danger_signs}'::text[] AS note_referred_to_health_facility_danger_signs,
    d.doc #>> '{fields,group_delivery_information,referred_to_health_facility_home_delivery}'::text[] AS referred_to_health_facility_home_delivery,
    d.doc #>> '{fields,group_delivery_information,agreed_health_facility_visit_date}'::text[] AS agreed_health_facility_visit_date,
    d.doc #>> '{fields,group_death_report_baby,baby_date_of_death}'::text[] AS baby_date_of_death,
    d.doc #>> '{fields,group_death_report_baby,baby_place_of_death}'::text[] AS baby_place_of_death,
    d.doc #>> '{fields,group_death_report_baby,baby_place_of_death_other}'::text[] AS baby_place_of_death_other,
    d.doc #>> '{fields,group_death_report_baby,still_birth}'::text[] AS still_birth,
    d.doc #>> '{fields,group_death_report_baby,baby_death_additional_notes}'::text[] AS baby_death_additional_notes,
    d.doc #>> '{fields,group_woman_nutritional_status,note_nutrition_status}'::text[] AS note_nutrition_status,
    d.doc #>> '{fields,group_woman_nutritional_status,taken_muac}'::text[] AS taken_muac,
    d.doc #>> '{fields,group_woman_nutritional_status,muac_measurement}'::text[] AS muac_measurement,
    d.doc #>> '{fields,group_woman_nutritional_status,encourage_client_to_consume_sufficient_diet}'::text[] AS encourage_client_to_consume_sufficient_diet,
    d.doc #>> '{fields,group_woman_nutritional_status,note_has_sam}'::text[] AS note_has_sam,
    d.doc #>> '{fields,group_woman_nutritional_status,note_has_mam}'::text[] AS note_has_mam,
    d.doc #>> '{fields,group_woman_nutritional_status,note_refer_to_health_facility}'::text[] AS note_refer_to_health_facility,
    d.doc #>> '{fields,group_woman_nutritional_status,referred_to_health_facility_nutrition}'::text[] AS referred_to_health_facility_nutrition,
    d.doc #>> '{fields,group_woman_nutritional_status,micro_nutrient_supplementation_received}'::text[] AS micro_nutrient_supplementation_received,
    d.doc #>> '{fields,group_woman_nutritional_status,note_encourage_micro-nutrients}'::text[] AS note_encourage_micro_nutrients,
    d.doc #>> '{fields,group_woman_nutritional_status,counsel_mother}'::text[] AS counsel_mother,
    d.doc #>> '{fields,group_woman_nutritional_status,referred_to_health_facility_no_micro_nutrient-supplementation}'::text[] AS referred_to_health_facility_no_micro_nutrient_supplementation,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_eat_well}'::text[] AS note_eat_well,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_exclusive_breastfeeding_counsel}'::text[] AS note_exclusive_breastfeeding_counsel,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_positioning_and_attachment}'::text[] AS note_positioning_and_attachment,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_how_to_keep_baby_warm}'::text[] AS note_how_to_keep_baby_warm,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_sleep_under_llin}'::text[] AS note_sleep_under_llin,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_keep_umbilical_cord_clean}'::text[] AS note_keep_umbilical_cord_clean,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_introduce_age_appropiate_foods}'::text[] AS note_introduce_age_appropiate_foods,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_infants_receive_vitamin_a}'::text[] AS note_infants_receive_vitamin_a,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_micro_nutrient_supplements}'::text[] AS note_micro_nutrient_supplements,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_promote_early_childhood_stimulation}'::text[] AS note_promote_early_childhood_stimulation,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_counsel_women_living_with_hiv}'::text[] AS note_counsel_women_living_with_hiv,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_hiv_exposed_infants}'::text[] AS note_hiv_exposed_infants,
    d.doc #>> '{fields,group_safe_postnatal_practices,note_hiv_infected_infants}'::text[] AS note_hiv_infected_infants,
    d.doc #>> '{fields,group_pnc_visits,who_recommendation}'::text[] AS who_recommendation,
    d.doc #>> '{fields,group_pnc_visits,pnc_visits}'::text[] AS pnc_visits,
    d.doc #>> '{contact,_id}'::text[] AS chw_id,
    h.facility_name,
    h.village,
    h.district,
    h.region,
    CURRENT_TIMESTAMP AS last_refresh_date
   FROM dwh.cht_data d
     LEFT JOIN cht.mv_chew_hierarchy_2 h ON (d.doc #>> '{contact,_id}'::text[]) = h.chw_id
  WHERE (d.doc ->> 'form'::text) = 'delivery'::text AND d.is_current = true
WITH DATA;

-- View indexes:
CREATE INDEX mv_delivery_reported ON cht.mv_delivery USING btree (reported) tablespace ts_indexes;
CREATE INDEX mv_delivery_year_month ON cht.mv_delivery USING btree (year, month) tablespace ts_indexes;
CREATE INDEX mv_delivery_date ON cht.mv_delivery USING btree (date) tablespace ts_indexes;
CREATE INDEX mv_delivery_inputs_contact_id ON cht.mv_delivery USING btree (inputs_contact_id) tablespace ts_indexes;
CREATE INDEX mv_delivery_chw_id ON cht.mv_delivery USING btree (chw_id) tablespace ts_indexes;
CREATE INDEX mv_delivery_facility_name ON cht.mv_delivery USING btree (facility_name) tablespace ts_indexes;
CREATE INDEX mv_delivery_district ON cht.mv_delivery USING btree (district) tablespace ts_indexes;