-- cht.mv_gbv_community_form source
DROP MATERIALIZED VIEW IF EXISTS cht.mv_gbv_community_form;
CREATE MATERIALIZED VIEW cht.mv_gbv_community_form
TABLESPACE ts_report
AS SELECT d.doc ->> '_id'::text AS uuid,
    d.doc ->> 'form'::text AS form,
    d.doc ->> '_rev'::text AS rev,
    to_timestamp((NULLIF(d.doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'YYYY-MM-DD'::text)::date AS date,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'YYYY'::text)::integer AS year,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'FMMonth'::text) AS monthname,
    ((d.doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS "Location Lat",
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS "Location Long",
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS "Location Error",
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS "Location Message",
    ((d.doc -> 'fields'::text) -> 'inputs'::text) ->> 'source'::text AS "Source",
    ((d.doc -> 'fields'::text) -> 'inputs'::text) ->> 'source_id'::text AS "Source ID",
    (((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'user'::text) ->> 'contact_id'::text AS "User Contact ID",
    (((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'user'::text) ->> 'facility_id'::text AS "User Facility ID",
    (((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) ->> '_id'::text AS "CHEW Area Id",
    (((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) ->> 'name'::text AS "CHEW Area Name",
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) -> 'contact'::text) ->> '_id'::text AS "CHEW ID",
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) -> 'contact'::text) ->> 'name'::text AS "CHEW Name",
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) -> 'contact'::text) ->> 'date_of_birth'::text AS "CHEW Date of Birth",
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'contact'::text) -> 'contact'::text) ->> 'phone'::text AS "Phone",
    (d.doc -> 'fields'::text) ->> 'chew_name'::text AS "CHEW Name (calculated)",
    (d.doc -> 'fields'::text) ->> 'chew_phone'::text AS "CHEW Phone (calculated)",
    (d.doc -> 'fields'::text) ->> 'place_id'::text AS "ID",
    (d.doc -> 'fields'::text) ->> 'place_name'::text AS "Name",
    (d.doc -> 'fields'::text) ->> 'start_time'::text AS "Time interview starts (system)",
    ((d.doc -> 'fields'::text) -> 'opening'::text) ->> 'note1_1'::text AS "Opening Note 1-1",
    ((d.doc -> 'fields'::text) -> 'opening'::text) ->> 'tool'::text AS "Please select an interview to be conducted",
    ((d.doc -> 'fields'::text) -> 'opening'::text) ->> 'consent'::text AS "Has the respondent agreed to be interviewed?",
    (d.doc -> 'fields'::text) ->> 'tool_label'::text AS "Tool Label (calculated)",
    (d.doc -> 'fields'::text) ->> 'interview_date'::text AS "Interview Date (calculated)",
    (d.doc -> 'fields'::text) ->> 'interviewer'::text AS "Interviewer (calculated)",
    ((d.doc -> 'fields'::text) -> 'lc1_group'::text) ->> 'note1_lc'::text AS "LC1 Note 1-LC",
    ((d.doc -> 'fields'::text) -> 'lc1_group'::text) ->> 'lc1'::text AS "LC1: Aware of physical violence in past 3 months?",
    ((d.doc -> 'fields'::text) -> 'lc1_group'::text) ->> 'lc2'::text AS "LC2: Heard of sexual violence in past 3 months?",
    ((d.doc -> 'fields'::text) -> 'lc1_group'::text) ->> 'lc4'::text AS "LC4: Total cases of violence/child abuse (past 3 months)",
    ((d.doc -> 'fields'::text) -> 'lc1_group'::text) ->> 'lc4_calc'::text AS "LC4 Calculated",
    ((d.doc -> 'fields'::text) -> 'lc1_group'::text) ->> 'lc15'::text AS "LC15: Risky households/locations/circumstances?",
    ((d.doc -> 'fields'::text) -> 'lc1_group'::text) ->> 'lc15b'::text AS "LC15B: Which kind of households?",
    ((d.doc -> 'fields'::text) -> 'lc1_group'::text) ->> 'lc16'::text AS "LC16: How are survivors helped?",
    ((d.doc -> 'fields'::text) -> 'lc1_group'::text) ->> 'lccases_repeat_count'::text AS "LCCases Repeat Count",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'note1_hm'::text AS "HM Note 1-HM",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm1'::text AS "HM1: Learners reported sexual touching/force?",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm2'::text AS "HM2: How many learners reported?",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm2_calc'::text AS "HM2 Calculated",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm11'::text AS "HM11: Unsafe places/situations at school?",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm12'::text AS "HM12: When/where do concerns occur?",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm12oth'::text AS "HM12 Other",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm13'::text AS "HM13: Gifts for sexual acts?",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm14'::text AS "HM14: Were they linked to care?",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm14b'::text AS "HM14B: Where linked?",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm14both'::text AS "HM14 Both",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm15'::text AS "HM15: Who gives gifts?",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm16'::text AS "HM16: Coerced/promised help?",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm17'::text AS "HM17: How were they helped?",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'hm17oth'::text AS "HM17 Other",
    ((d.doc -> 'fields'::text) -> 'hm_group'::text) ->> 'schcases_repeat_count'::text AS "School Cases Repeat Count",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'note1_hh'::text AS "HH Note 1-HH",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh1'::text AS "HH1: Household member physically/sexually harmed?",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh2'::text AS "HH2: Who was harmed (age)?",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh3'::text AS "HH3: Who was harmed (sex)?",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh4'::text AS "HH4: By who?",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh5'::text AS "HH5: Did survivors report/seek help?",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh6'::text AS "HH6: Where reported?",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh6oth'::text AS "HH6 Other",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh7'::text AS "HH7: Report barriers?",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh7oth'::text AS "HH7 Other",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh9'::text AS "HH9: Need immediate assistance?",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh10'::text AS "HH10: Victim has disability?",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh10b'::text AS "HH10B: Type of case",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh10c'::text AS "HH10C: Intimate-partner violence?",
    ((d.doc -> 'fields'::text) -> 'hh_group'::text) ->> 'hh1note'::text AS "HH1 Note",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'note1_pc'::text AS "PC Note 1-PC",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc1'::text AS "PC1: Who was harmed (age)?",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc2'::text AS "PC2: Who was harmed (sex)?",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc3'::text AS "PC3: By who?",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc4'::text AS "PC4: Type of violence?",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc5'::text AS "PC5: Where did it happen?",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc5oth'::text AS "PC5 Other",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc6a'::text AS "PC6A: Case referred?",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc6b'::text AS "PC6B: Where referred?",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc6both'::text AS "PC6 Both",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc7'::text AS "PC7: Victim has disability?",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc7b'::text AS "PC7B: Type of case",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc7c'::text AS "PC7C: Intimate-partner violence?",
    ((d.doc -> 'fields'::text) -> 'pc_group'::text) ->> 'pc8'::text AS "PC8: Brief description",
    (d.doc -> 'fields'::text) ->> 'consenta'::text AS "If no consent, reason for refusal",
    (d.doc -> 'fields'::text) ->> 'obs'::text AS "Record any helpful observation/comment",
    (d.doc -> 'fields'::text) ->> 'end_time'::text AS "End Time (system)",
    d.doc #>> '{contact,_id}'::text[] AS chw_id,
    h.facility,
    h.village,
    h.district,
    h.region,
    CURRENT_TIMESTAMP AS last_refresh_date
   FROM dwh.cht_data d
     LEFT JOIN cht.mv_chw_hierarchy h ON (d.doc #>> '{contact,_id}'::text[]) = h.chw_id
  WHERE (d.doc ->> 'form'::text) = 'gbv_community_form'::text AND d.is_current
WITH DATA;

-- View indexes:
CREATE INDEX mv_gbv_community_chw_idx ON cht.mv_gbv_community_form USING btree (chw_id) TABLESPACE ts_indexes;
CREATE INDEX mv_gbv_community_reported_idx ON cht.mv_gbv_community_form USING btree (reported) TABLESPACE ts_indexes;
CREATE INDEX mv_gbv_community_date_idx ON cht.mv_gbv_community_form USING btree (date) TABLESPACE ts_indexes;
CREATE INDEX mv_gbv_community_year_idx ON cht.mv_gbv_community_form USING btree (year) TABLESPACE ts_indexes;
CREATE INDEX mv_gbv_community_month_idx ON cht.mv_gbv_community_form USING btree (month) TABLESPACE ts_indexes;   