-- cht.mv_health_education_new source
DROP MATERIALIZED VIEW cht.mv_health_education;
CREATE MATERIALIZED VIEW cht.mv_health_education
TABLESPACE ts_report
AS SELECT doc ->> '_id'::text AS uuid,
    doc ->> 'form'::text AS form,
    doc ->> 'from'::text AS submitter,
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    to_char(to_timestamp((((doc ->>'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS monthname,
    ((doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    doc #>> '{fields,inputs,source}'::text[] AS inputs_source,
    doc #>> '{fields,inputs,source_id}'::text[] AS inputs_source_id,
    doc #>> '{fields,inputs,user,contact_id}'::text[] AS inputs_user_contact_id,
    doc #>> '{fields,inputs,user,facility_id}'::text[] AS inputs_user_facility_id,
    doc #>> '{fields,inputs,contact,_id}'::text[] AS inputs_contact_id,
    doc #>> '{fields,inputs,contact,name}'::text[] AS inputs_contact_name,
    doc #>> '{fields,inputs,contact,contact,_id}'::text[] AS inputs_contact_contact_id,
    doc #>> '{fields,inputs,contact,contact,name}'::text[] AS inputs_contact_contact_name,
    doc #>> '{fields,inputs,contact,contact,date_of_birth}'::text[] AS inputs_contact_contact_date_of_birth,
    doc #>> '{fields,patient_id}'::text[] AS patient_id,
    doc #>> '{fields,place_id}'::text[] AS place_id,
    doc #>> '{fields,chew_name}'::text[] AS chew_name,
    doc #>> '{fields,chew_date_of_birth}'::text[] AS chew_date_of_birth,
    doc #>> '{fields,chew_age_display}'::text[] AS chew_age_display,
    doc #>> '{fields,village_id}'::text[] AS village_id,
    doc #>> '{fields,village_name}'::text[] AS village_name,
    doc #>> '{fields,needs_signoff}'::text[] AS needs_signoff,
    doc #>> '{fields,chosen_venue}'::text[] AS chosen_venue,
    doc #>> '{fields,selected_village,venue}'::text[] AS selected_village_venue,
    doc #>> '{fields,selected_village,village_id}'::text[] AS selected_village_village_id,
    doc #>> '{fields,selected_village,name}'::text[] AS selected_village_name,
    doc #>> '{fields,geolocation,n_geolocation}'::text[] AS fields_geolocation_n_geolocation,
    doc #>> '{fields,geolocation,want_to_capture_gps}'::text[] AS fields_geolocation_want_to_capture_gps,
    doc #>> '{fields,geolocation,gps_capture_checklist}'::text[] AS fields_geolocation_gps_capture_checklist,
    doc #>> '{fields,geolocation,gps}'::text[] AS fields_geolocation_gps,
    doc #>> '{fields,geolocation,gps_capture_checklist_completed}'::text[] AS fields_geolocation_gps_capture_checklist_completed,
    doc #>> '{fields,geolocation,latitude}'::text[] AS fields_geolocation_latitude,
    doc #>> '{fields,geolocation,longitude}'::text[] AS fields_geolocation_longitude,
    doc #>> '{fields,geolocation,altitude}'::text[] AS fields_geolocation_altitude,
    doc #>> '{fields,geolocation,accuracy}'::text[] AS fields_geolocation_accuracy,
    doc #>> '{fields,geolocation,gps_location_picked_display}'::text[] AS fields_geolocation_gps_location_picked_display,
    doc #>> '{fields,geolocation,additional_comments}'::text[] AS fields_geolocation_additional_comments,
    doc #>> '{fields,g_health_education_topics,session_date}'::text[] AS he_session_date,
    doc #>> '{fields,g_health_education_topics,topics_covered}'::text[] AS he_topics_covered,
    doc #>> '{fields,g_health_education_topics,specify_other_topic}'::text[] AS he_specify_other_topic,
    doc #>> '{fields,g_wash_topic,wash_priorities}'::text[] AS g_wash_topic_wash_priorities,
    (doc #>> '{fields,g_wash_topic,nb_attendee_wash}'::text[])::integer AS g_wash_topic_nb_attendee_wash,
    doc #>> '{fields,g_wash_topic,additional_notes_wash}'::text[] AS g_wash_topic_additional_notes_wash,
    doc #>> '{fields,g_nutrition_promotion_topic,nutrition_practices}'::text[] AS g_nutrition_promotion_topic_nutrition_practices,
    (doc #>> '{fields,g_nutrition_promotion_topic,nb_attendee_food_promotion}'::text[])::integer AS g_nutrition_promotion_topic_nb_attendee_food_promotion,
    doc #>> '{fields,g_nutrition_promotion_topic,additional_notes_promotion}'::text[] AS g_nutrition_promotion_topic_additional_notes_promotion,
    doc #>> '{fields,g_non_communicable_diseases_topic,non_communicable_diseases_facts}'::text[] AS g_non_communicable_diseases_topic_non_communicable_diseases_fac,
    (doc #>> '{fields,g_non_communicable_diseases_topic,nb_attendee_commun_diseases}'::text[])::integer AS g_non_communicable_diseases_topic_nb_attendee_commun_diseases,
    doc #>> '{fields,g_non_communicable_diseases_topic,additional_notes_commun_diseases}'::text[] AS g_non_communicable_diseases_topic_additional_notes_commun_disea,
    doc #>> '{fields,g_leprosy_topic,leprosy_facts}'::text[] AS g_leprosy_topic_leprosy_facts,
    (doc #>> '{fields,g_leprosy_topic,nb_attendee_leprosy}'::text[])::integer AS g_leprosy_topic_nb_attendee_leprosy,
    doc #>> '{fields,g_leprosy_topic,additional_notes_leprosy}'::text[] AS g_leprosy_topic_additional_notes_leprosy,
    doc #>> '{fields,g_malaria_topic,malaria_facts}'::text[] AS g_malaria_topic_malaria_facts,
    (doc #>> '{fields,g_malaria_topic,nb_attendee_malaria}'::text[])::integer AS g_malaria_topic_nb_attendee_malaria,
    doc #>> '{fields,g_malaria_topic,additional_notes_malaria}'::text[] AS g_malaria_topic_additional_notes_malaria,
    doc #>> '{fields,g_hiv_aids_topic,hiv_aids_facts}'::text[] AS g_hiv_aids_topic_hiv_aids_facts,
    (doc #>> '{fields,g_hiv_aids_topic,nb_attendee_hiv}'::text[])::integer AS g_hiv_aids_topic_nb_attendee_hiv,
    doc #>> '{fields,g_hiv_aids_topic,additional_notes_hiv}'::text[] AS g_hiv_aids_topic_additional_notes_hiv,
    doc #>> '{fields,g_tb_topic,tb_facts}'::text[] AS g_tb_topic_tb_facts,
    (doc #>> '{fields,g_tb_topic,nb_attendee_tb}'::text[])::integer AS g_tb_topic_nb_attendee_tb,
    doc #>> '{fields,g_tb_topic,additional_notes_tb}'::text[] AS g_tb_topic_additional_notes_tb,
    doc #>> '{fields,g_maternal_health_topic,maternal_health_facts}'::text[] AS g_maternal_health_topic_maternal_health_facts,
    (doc #>> '{fields,g_maternal_health_topic,nb_attendee_maternal_health}'::text[])::integer AS g_maternal_health_topic_nb_attendee_maternal_health,
    doc #>> '{fields,g_maternal_health_topic,additional_notes_maternal_health}'::text[] AS g_maternal_health_topic_additional_notes_maternal_health,
    doc #>> '{fields,g_child_health_topic,child_health_facts}'::text[] AS g_child_health_topic_child_health_facts,
    (doc #>> '{fields,g_child_health_topic,nb_attendee_child_health}'::text[])::integer AS g_child_health_topic_nb_attendee_child_health,
    doc #>> '{fields,g_child_health_topic,additional_notes_child_health}'::text[] AS g_child_health_topic_additional_notes_child_health,
    (doc #>> '{fields,g_other_topic,nb_attendee_other_topic}'::text[])::integer AS g_other_topic_nb_attendee_other_topic,
    doc #>> '{fields,g_other_topic,additional_notes_other_topic}'::text[] AS g_other_topic_additional_notes_other_topic,
    doc #>> '{contact,_id}'                         AS chw_id,
      h.facility_name,
      h.dhis2_facility_id,
      h.village,
      h.district,
      h.region,
      CURRENT_TIMESTAMP                                 AS last_refresh_date
   FROM dwh.cht_data couchdb
LEFT JOIN cht.mv_chw_hierarchy h ON (couchdb.doc #>> '{contact,_id}') = h.chw_id
  WHERE (doc ->> 'form'::text) = 'health_education'::text AND is_current
WITH DATA;

-- View indexes:
CREATE INDEX mv_health_education_chw_id ON cht.mv_health_education USING btree (chw_id) TABLESPACE ts_indexes;
CREATE INDEX mv_health_education_reported ON cht.mv_health_education USING btree (reported) TABLESPACE ts_indexes;
CREATE INDEX mv_health_education_year_month ON cht.mv_health_education USING btree (year, month) TABLESPACE ts_indexes;
CREATE INDEX mv_health_education_facility ON cht.mv_health_education USING btree (facility_name) TABLESPACE ts_indexes;
CREATE INDEX mv_health_education_dhis2_facility_id ON cht.mv_health_education USING btree (dhis2_facility_id) TABLESPACE ts_indexes;
CREATE INDEX mv_health_education_district ON cht.mv_health_education USING btree (district) TABLESPACE ts_indexes;  
CREATE INDEX mv_health_education_region ON cht.mv_health_education USING btree (region) TABLESPACE ts_indexes;  
