-- cht.mv_ha_danger_signs_follow_up_new source
DROP MATERIALIZED VIEW cht.mv_ha_danger_signs_follow_up;
CREATE MATERIALIZED VIEW cht.mv_ha_danger_signs_follow_up
TABLESPACE ts_report
AS SELECT doc ->> '_id'::text AS doc_id,
    doc ->> '_rev'::text AS rev,
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    to_char(to_timestamp((((doc ->>'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS monthname,
    ((doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    doc ->> 'from'::text AS "from",
    doc #>> '{fields,inputs,source}'::text[] AS source,
    doc #>> '{fields,inputs,source_id}'::text[] AS source_id,
    doc #>> '{fields,inputs,t_place_name}'::text[] AS t_place_name,
    doc #>> '{fields,inputs,t_created_by_doc}'::text[] AS t_created_by_doc,
    doc #>> '{fields,inputs,t_place_id}'::text[] AS t_place_id,
    doc #>> '{fields,inputs,t_patient_name}'::text[] AS t_patient_name,
    doc #>> '{fields,inputs,t_patient_id}'::text[] AS t_patient_id,
    doc #>> '{fields,inputs,t_vht_name}'::text[] AS t_vht_name,
    doc #>> '{fields,inputs,t_vht_phone}'::text[] AS t_vht_phone,
    doc #>> '{fields,inputs,t_patient_age_in_years}'::text[] AS t_patient_age_in_years,
    doc #>> '{fields,inputs,t_patient_age_in_months}'::text[] AS t_patient_age_in_months,
    doc #>> '{fields,inputs,t_patient_age_in_days}'::text[] AS t_patient_age_in_days,
    doc #>> '{fields,inputs,t_patient_age_display}'::text[] AS t_patient_age_display,
    doc #>> '{fields,inputs,t_patient_sex}'::text[] AS t_patient_sex,
    doc #>> '{fields,inputs,t_source}'::text[] AS t_source,
    doc #>> '{fields,inputs,t_source_id}'::text[] AS t_source_id,
    doc #>> '{fields,inputs,t_danger_signs}'::text[] AS t_danger_signs,
    doc #>> '{fields,inputs,user,contact_id}'::text[] AS user_contact_id,
    doc #>> '{fields,inputs,user,facility_id}'::text[] AS user_facility_id,
    doc #>> '{fields,place_id}'::text[] AS place_id,
    doc #>> '{fields,place_name}'::text[] AS place_name,
    doc #>> '{fields,needs_signoff}'::text[] AS needs_signoff,
    doc #>> '{fields,additional_doc,patient_id}'::text[] AS patient_id,
    doc #>> '{fields,additional_doc,patient_name}'::text[] AS patient_name,
    doc #>> '{fields,additional_doc,patient_age_in_years}'::text[] AS patient_age_in_years,
    doc #>> '{fields,additional_doc,patient_age_in_months}'::text[] AS patient_age_in_months,
    doc #>> '{fields,additional_doc,patient_age_in_days}'::text[] AS patient_age_in_days,
    doc #>> '{fields,additional_doc,patient_age_display}'::text[] AS patient_age_display,
    doc #>> '{fields,additional_doc,patient_sex}'::text[] AS patient_sex,
    doc #>> '{fields,additional_doc,vht_area_id}'::text[] AS vht_area_id,
    doc #>> '{fields,additional_doc,vht_area_name}'::text[] AS vht_area_name,
    doc #>> '{fields,additional_doc,vht_name}'::text[] AS vht_name,
    doc #>> '{fields,additional_doc,vht_phone}'::text[] AS vht_phone,
    doc #>> '{fields,additional_doc,status}'::text[] AS status,
    doc #>> '{fields,additional_doc,status_other}'::text[] AS status_other,
    doc #>> '{fields,additional_doc,remarks}'::text[] AS remarks,
    doc #>> '{fields,additional_doc,follow_up_date}'::text[] AS follow_up_date,
    doc #>> '{fields,group_danger,danger_signs_note}'::text[] AS danger_signs_note,
    doc #>> '{fields,group_danger,danger_signs}'::text[] AS danger_signs,
    doc #>> '{fields,group_danger,vaginal_bleeding}'::text[] AS vaginal_bleeding,
    doc #>> '{fields,group_danger,lower_abdomen_pain}'::text[] AS lower_abdomen_pain,
    doc #>> '{fields,group_danger,severe_headache}'::text[] AS severe_headache,
    doc #>> '{fields,group_danger,very_pale}'::text[] AS very_pale,
    doc #>> '{fields,group_danger,fever}'::text[] AS fever,
    doc #>> '{fields,group_danger,reduced_or_no_feotal_movements}'::text[] AS reduced_or_no_feotal_movements,
    doc #>> '{fields,group_danger,blurred_vision}'::text[] AS blurred_vision,
    doc #>> '{fields,group_danger,swelling}'::text[] AS swelling,
    doc #>> '{fields,group_danger,breathlessness}'::text[] AS breathlessness,
    doc #>> '{fields,group_danger,woman_danger_sign_fever}'::text[] AS woman_danger_sign_fever,
    doc #>> '{fields,group_danger,woman_danger_sign_severe_headache}'::text[] AS woman_danger_sign_severe_headache,
    doc #>> '{fields,group_danger,woman_danger_sign_vaginal_bleeding}'::text[] AS woman_danger_sign_vaginal_bleeding,
    doc #>> '{fields,group_danger,woman_danger_sign_foul_vaginal_discharge}'::text[] AS woman_danger_sign_foul_vaginal_discharge,
    doc #>> '{fields,group_danger,woman_danger_sign_convulsions}'::text[] AS woman_danger_sign_convulsions,
    doc #>> '{fields,group_danger,child_vomits_everything}'::text[] AS child_vomits_everything,
    doc #>> '{fields,group_danger,child_has_convulsions}'::text[] AS child_has_convulsions,
    doc #>> '{fields,group_danger,child_cannot_drink_breastfeed}'::text[] AS child_cannot_drink_breastfeed,
    doc #>> '{fields,group_danger,child_unconscious}'::text[] AS child_unconscious,
    doc #>> '{fields,group_danger,child_has_low_temp}'::text[] AS child_has_low_temp,
    doc #>> '{fields,group_danger,child_has_yellow_eyes_or_palms}'::text[] AS child_has_yellow_eyes_or_palms,
    doc #>> '{fields,group_danger,child_has_infected_umbilical_cord}'::text[] AS child_has_infected_umbilical_cord,
    doc #>> '{fields,group_danger,child_has_chest_in_drawing}'::text[] AS child_has_chest_in_drawing,
    doc #>> '{fields,group_danger,child_vomiting_everything}'::text[] AS child_vomiting_everything,
    doc #>> '{fields,group_danger,child_has_difficulty_feeding}'::text[] AS child_has_difficulty_feeding,
    doc #>> '{fields,group_danger,child_has_body_stiffness}'::text[] AS child_has_body_stiffness,
    doc #>> '{fields,group_danger,child_has_fever}'::text[] AS child_has_fever,
    doc #>> '{fields,group_danger,child_has_yellow_skin}'::text[] AS child_has_yellow_skin,
    doc #>> '{fields,group_danger,call_button}'::text[] AS call_button,
    doc #>> '{fields,group_danger,action}'::text[] AS action,
    doc #>> '{fields,group_danger,specify}'::text[] AS specify,
    doc #>> '{fields,group_danger,comment}'::text[] AS comment,
    doc #>> '{contact,_id}'                         AS chw_id,
      h.facility,
      h.dhis2_facility_id,
      h.village,
      h.district,
      h.region,
      CURRENT_TIMESTAMP                                 AS last_refresh_date 
   FROM dwh.cht_data couchdb
LEFT JOIN cht.mv_chw_hierarchy h ON (couchdb.doc #>> '{contact,_id}') = h.chw_id
  WHERE (doc ->> 'form'::text) = 'ha_danger_signs_follow_up'::text AND is_current
WITH DATA;

-- View indexes:
CREATE INDEX ha_danger_signs_follow_up_reported_idx ON cht.mv_ha_danger_signs_follow_up USING btree (reported) TABLESPACE ts_indexes;
CREATE INDEX ha_danger_signs_follow_up_chw_id_idx ON cht.mv_ha_danger_signs_follow_up USING btree (chw_id) TABLESPACE ts_indexes;
CREATE INDEX ha_danger_signs_follow_up_district_idx ON cht.mv_ha_danger_signs_follow_up USING btree (district) TABLESPACE ts_indexes;
CREATE INDEX ha_danger_signs_follow_up_facility_idx ON cht.mv_ha_danger_signs_follow_up USING btree (facility) TABLESPACE ts_indexes;
CREATE INDEX ha_danger_signs_follow_up_year_idx ON cht.mv_ha_danger_signs_follow_up USING btree (year) TABLESPACE ts_indexes;
CREATE INDEX ha_danger_signs_follow_up_month_idx ON cht.mv_ha_danger_signs_follow_up USING btree (month) TABLESPACE ts_indexes;