-- cht.mv_household_model_follow_up source
DROP MATERIALIZED VIEW IF EXISTS cht.mv_household_model_follow_up;
CREATE MATERIALIZED VIEW cht.mv_household_model_follow_up
TABLESPACE ts_report
AS SELECT doc ->> '_id'::text AS uuid,
    doc ->> 'form'::text AS form,
    doc ->> 'from'::text AS submitter,
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    to_char(to_timestamp((((doc ->>'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS monthname,
    ((doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    doc #>> '{fields,inputs,source}'::text[] AS inputs_source,
    doc #>> '{fields,inputs,source_id}'::text[] AS inputs_source_id,
    doc #>> '{fields,inputs,t_hh_head_name}'::text[] AS inputs_t_hh_head_name,
    doc #>> '{fields,inputs,contact,_id}'::text[] AS inputs_contact_id,
    doc #>> '{fields,inputs,contact,name}'::text[] AS inputs_contact_name,
    doc #>> '{fields,inputs,contact,parent,village}'::text[] AS inputs_contact_parent_village,
    doc #>> '{fields,inputs,contact,contact,name}'::text[] AS inputs_contact_contact_name,
    doc #>> '{fields,visited_contact_uuid}'::text[] AS visited_contact_uuid,
    doc #>> '{fields,place_id}'::text[] AS place_id,
    doc #>> '{fields,place_name}'::text[] AS place_name,
    doc #>> '{fields,hh_head_name}'::text[] AS hh_head_name,
    doc #>> '{fields,chw_village}'::text[] AS chw_village,
    doc #>> '{fields,current_gps}'::text[] AS current_gps,
    doc #>> '{fields,needs_signoff}'::text[] AS needs_signoff,
    doc #>> '{fields,hh_head}'::text[] AS hh_head,
    doc #>> '{fields,geolocation,latitude}'::text[] AS geolocation_latitude,
    doc #>> '{fields,geolocation,longitude}'::text[] AS geolocation_longitude,
    doc #>> '{fields,geolocation,altitude}'::text[] AS geolocation_altitude,
    doc #>> '{fields,geolocation,accuracy}'::text[] AS geolocation_accuracy,
    doc #>> '{fields,geolocation,note_no_hh_gps}'::text[] AS geolocation_note_no_hh_gps,
    doc #>> '{fields,geolocation,want_to_capture_gps}'::text[] AS geolocation_want_to_capture_gps,
    doc #>> '{fields,geolocation,ensure_gps}'::text[] AS geolocation_ensure_gps,
    doc #>> '{fields,geolocation,gps}'::text[] AS geolocation_gps,
    doc #>> '{fields,geolocation,coordinates}'::text[] AS geolocation_coordinates,
    doc #>> '{fields,geolocation,additional_comments}'::text[] AS geolocation_additional_comments,
    doc #>> '{fields,group_wash,hh_in_sanitary_dwelling_house}'::text[] AS hh_in_sanitary_dwelling_house,
    doc #>> '{fields,group_wash,hh_access_safe_water_source}'::text[] AS hh_access_safe_water_source,
    doc #>> '{fields,group_wash,hh_have_safe_drinking_water}'::text[] AS hh_have_safe_drinking_water,
    doc #>> '{fields,group_wash,hh_have_sanitary_kitchen}'::text[] AS hh_have_sanitary_kitchen,
    doc #>> '{fields,group_wash,hh_have_drying_rack}'::text[] AS hh_have_drying_rack,
    doc #>> '{fields,group_wash,hh_have_backyard_garden}'::text[] AS hh_have_backyard_garden,
    doc #>> '{fields,group_wash,hh_have_rubbish_pit}'::text[] AS hh_have_rubbish_pit,
    doc #>> '{fields,group_wash,hh_have_bath_shelter}'::text[] AS hh_have_bath_shelter,
    doc #>> '{fields,group_wash,hh_sanitary_facility}'::text[] AS hh_sanitary_facility,
    doc #>> '{fields,group_wash,hh_sharing_sanitary_facility}'::text[] AS hh_sharing_sanitary_facility,
    doc #>> '{fields,group_wash,verify_hh_sharing_sanitary_facility}'::text[] AS verify_hh_sharing_sanitary_facility,
    doc #>> '{fields,group_wash,hh_kind_of_public_toilet}'::text[] AS hh_kind_of_public_toilet,
    doc #>> '{fields,group_wash,hh_latrine_fly_proof}'::text[] AS hh_latrine_fly_proof,
    doc #>> '{fields,group_wash,hh_floor_of_toilet_or_latrine}'::text[] AS hh_floor_of_toilet_or_latrine,
    doc #>> '{fields,group_wash,hh_toilet_conected_to_sewer}'::text[] AS hh_toilet_conected_to_sewer,
    doc #>> '{fields,group_wash,hh_sanitary_facility_filled_up}'::text[] AS hh_sanitary_facility_filled_up,
    doc #>> '{fields,group_wash,hh_empited_pit_latrine_or_septic_tank}'::text[] AS hh_empited_pit_latrine_or_septic_tank,
    doc #>> '{fields,group_wash,hh_emptying_services}'::text[] AS hh_emptying_services,
    doc #>> '{fields,group_wash,hh_emptied_contents_location}'::text[] AS hh_emptied_contents_location,
    doc #>> '{fields,group_wash,hh_handwashing_near_toilet_latrine}'::text[] AS hh_handwashing_near_toilet_latrine,
    doc #>> '{fields,group_wash,hh_handwashing_facility_status}'::text[] AS hh_handwashing_facility_status,
    doc #>> '{fields,group_wash,hh_is_odf}'::text[] AS hh_is_odf,
    doc #>> '{fields,hh_model_assessment,hh_have_drying_lines}'::text[] AS hh_have_drying_lines,
    doc #>> '{fields,hh_model_assessment,hh_have_animal_house}'::text[] AS hh_have_animal_house,
    doc #>> '{fields,hh_model_assessment,hh_have_food_storage_access}'::text[] AS hh_have_food_storage_access,
    doc #>> '{fields,hh_model_assessment,hh_compound_well_maintained}'::text[] AS hh_compound_well_maintained,
    doc #>> '{fields,hh_model_assessment,hh_have_vermin_rodent}'::text[] AS hh_have_vermin_rodent,
    doc #>> '{fields,hh_model_assessment,n_train_on_missing_indicators}'::text[] AS n_train_on_missing_indicators,
    doc #>> '{fields,hh_model_assessment,n_animal_house_indicator}'::text[] AS n_animal_house_indicator,
    doc #>> '{fields,hh_model_assessment,n_adequate_drying_lines_indicator}'::text[] AS n_adequate_drying_lines_indicator,
    doc #>> '{fields,hh_model_assessment,n_food_storage_indicator}'::text[] AS n_food_storage_indicator,
    doc #>> '{fields,hh_model_assessment,n_well_maintained_compound_indicator}'::text[] AS n_well_maintained_compound_indicator,
    doc #>> '{fields,hh_model_assessment,n_vermin_rodent_control_indicator}'::text[] AS n_vermin_rodent_control_indicator,
    doc #>> '{fields,hh_model_assessment,follow_household}'::text[] AS follow_household,
    doc #>> '{fields,hh_model_assessment,next_household_follow_up_date}'::text[] AS next_household_follow_up_date,
    doc #>> '{fields,is_model_household}'::text[] AS is_model_household,
    doc #>> '{fields,next_wash_report_task_date}'::text[] AS next_wash_report_task_date,
    doc #>> '{contact,_id}'                         AS chw_id,
      h.facility,
      h.dhis2_facility_id,
      h.village,
      h.district,
      h.region,
      CURRENT_TIMESTAMP                                 AS last_refresh_date 
   FROM dwh.cht_data
    LEFT JOIN cht.mv_chw_hierarchy h ON (dwh.cht_data.doc #>> '{contact,_id}') = h.chw_id
  WHERE (doc ->> 'form'::text) = 'household_model_follow_up'::text AND is_current
WITH DATA;

-- View indexes:
CREATE INDEX mv_household_model_follow_up_chw_id ON cht.mv_household_model_follow_up USING btree (chw_id) tablespace ts_indexes;
CREATE INDEX mv_household_model_follow_up_reported ON cht.mv_household_model_follow_up USING btree (reported) tablespace ts_indexes;
CREATE INDEX mv_household_model_follow_up_year_month ON cht.mv_household_model_follow_up USING btree (year, month) tablespace ts_indexes;
CREATE INDEX mv_household_model_follow_up_district ON cht.mv_household_model_follow_up USING btree (district) tablespace ts_indexes;
CREATE INDEX mv_household_model_follow_up_facility ON cht.mv_household_model_follow_up USING btree (facility) tablespace ts_indexes;
CREATE INDEX mv_household_model_follow_up_dhis2_facility_id ON cht.mv_household_model_follow_up USING btree (dhis2_facility_id) tablespace ts_indexes;
CREATE INDEX mv_household_model_follow_up_village ON cht.mv_household_model_follow_up USING btree (village) tablespace ts_indexes;
CREATE INDEX mv_household_model_follow_up_region ON cht.mv_household_model_follow_up USING btree (region) tablespace ts_indexes;