-- cht.mv_maternal_health_education_new source
DROP MATERIALIZED VIEW cht.mv_maternal_health_education;
CREATE MATERIALIZED VIEW cht.mv_maternal_health_education
TABLESPACE ts_report
AS SELECT doc ->> '_id'::text AS doc_id,
    doc ->> '_rev'::text AS rev,
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    to_char(to_timestamp((((doc ->>'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS monthname,
    ((doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    doc ->> 'form'::text AS form,
    doc ->> 'from'::text AS "from",
    doc #>> '{fields,inputs,source}'::text[] AS source,
    doc #>> '{fields,inputs,source_id}'::text[] AS source_id,
    doc #>> '{fields,inputs,current_edd_std}'::text[] AS current_edd_std,
    doc #>> '{fields,inputs,anc_visits}'::text[] AS anc_visits,
    doc #>> '{fields,inputs,t_vaginal_bleeding}'::text[] AS t_vaginal_bleeding,
    doc #>> '{fields,inputs,t_lower_abdomen_pain}'::text[] AS t_lower_abdomen_pain,
    doc #>> '{fields,inputs,t_severe_headache}'::text[] AS t_severe_headache,
    doc #>> '{fields,inputs,t_very_pale}'::text[] AS t_very_pale,
    doc #>> '{fields,inputs,t_fever}'::text[] AS t_fever,
    doc #>> '{fields,inputs,t_reduced_or_no_feotal_movements}'::text[] AS t_reduced_or_no_feotal_movements,
    doc #>> '{fields,inputs,t_blurred_vision}'::text[] AS t_blurred_vision,
    doc #>> '{fields,inputs,t_swelling}'::text[] AS t_swelling,
    doc #>> '{fields,inputs,t_breathlessness}'::text[] AS t_breathlessness,
    doc #>> '{fields,inputs,t_has_hypertension}'::text[] AS t_has_hypertension,
    doc #>> '{fields,inputs,t_hiv_test_result}'::text[] AS t_hiv_test_result,
    doc #>> '{fields,inputs,t_patient_name}'::text[] AS t_patient_name,
    doc #>> '{fields,inputs,t_patient_gender}'::text[] AS t_patient_gender,
    doc #>> '{fields,inputs,t_patient_date_of_birth}'::text[] AS t_patient_date_of_birth,
    doc #>> '{fields,inputs,t_patient_id}'::text[] AS t_patient_id,
    doc #>> '{fields,inputs,user,contact_id}'::text[] AS user_contact_id,
    doc #>> '{fields,inputs,user,facility_id}'::text[] AS user_facility_id,
    doc #>> '{fields,inputs,contact,_id}'::text[] AS inputs_contact_id,
    doc #>> '{fields,inputs,contact,name}'::text[] AS inputs_contact_name,
    doc #>> '{fields,inputs,contact,date_of_birth}'::text[] AS inputs_contact_date_of_birth,
    doc #>> '{fields,inputs,contact,sex}'::text[] AS inputs_contact_sex,
    doc #>> '{fields,inputs,contact,has_hypertension}'::text[] AS inputs_contact_has_hypertension,
    doc #>> '{fields,inputs,contact,hiv_test_result}'::text[] AS inputs_contact_hiv_test_result,
    doc #>> '{fields,dob}'::text[] AS dob,
    doc #>> '{fields,patient_age_in_years}'::text[] AS patient_age_in_years,
    doc #>> '{fields,patient_age_in_months}'::text[] AS patient_age_in_months,
    doc #>> '{fields,patient_age_in_days}'::text[] AS patient_age_in_days,
    doc #>> '{fields,patient_age_display}'::text[] AS patient_age_display,
    doc #>> '{fields,patient_id}'::text[] AS patient_id,
    doc #>> '{fields,patient_name}'::text[] AS patient_name,
    doc #>> '{fields,patient_gender}'::text[] AS patient_gender,
    doc #>> '{fields,current_pregnancy_age_in_weeks}'::text[] AS current_pregnancy_age_in_weeks,
    doc #>> '{fields,no_pregnancy_danger_sign}'::text[] AS no_pregnancy_danger_sign,
    doc #>> '{fields,no_pregnancy_risk_factor}'::text[] AS no_pregnancy_risk_factor,
    doc #>> '{fields,needs_signoff}'::text[] AS needs_signoff,
    doc #>> '{fields,pregnancy_details,is_pregnant}'::text[] AS is_pregnant,
    doc #>> '{fields,pregnancy_details,pregnancy_outcome}'::text[] AS pregnancy_outcome,
    doc #>> '{fields,pregnancy_details,note_vht_delivery_report}'::text[] AS note_vht_delivery_report,
    doc #>> '{fields,pregnancy_details,refer_to_health_facility}'::text[] AS refer_to_health_facility,
    doc #>> '{fields,pregnancy_details,anc_visits_typo}'::text[] AS anc_visits_typo,
    doc #>> '{fields,pregnancy_details,patient_pregnancy_details}'::text[] AS patient_pregnancy_details,
    doc #>> '{fields,pregnancy_details,pregnancy_danger_signs}'::text[] AS pregnancy_danger_signs,
    doc #>> '{fields,pregnancy_details,danger_sign_none}'::text[] AS danger_sign_none,
    doc #>> '{fields,pregnancy_details,vaginal_bleeding}'::text[] AS vaginal_bleeding,
    doc #>> '{fields,pregnancy_details,lower_abdomen_pain}'::text[] AS lower_abdomen_pain,
    doc #>> '{fields,pregnancy_details,severe_headache}'::text[] AS severe_headache,
    doc #>> '{fields,pregnancy_details,very_pale}'::text[] AS very_pale,
    doc #>> '{fields,pregnancy_details,fever}'::text[] AS fever,
    doc #>> '{fields,pregnancy_details,reduced_or_no_feotal_movements}'::text[] AS reduced_or_no_feotal_movements,
    doc #>> '{fields,pregnancy_details,blurred_vision}'::text[] AS blurred_vision,
    doc #>> '{fields,pregnancy_details,swelling}'::text[] AS swelling,
    doc #>> '{fields,pregnancy_details,breathlessness}'::text[] AS breathlessness,
    doc #>> '{fields,pregnancy_details,pregnancy_risk_factors}'::text[] AS pregnancy_risk_factors,
    doc #>> '{fields,pregnancy_details,pregnancy_risk_none}'::text[] AS pregnancy_risk_none,
    doc #>> '{fields,pregnancy_details,below_18}'::text[] AS below_18,
    doc #>> '{fields,pregnancy_details,above_35}'::text[] AS above_35,
    doc #>> '{fields,pregnancy_details,hypertension}'::text[] AS hypertension,
    doc #>> '{fields,pregnancy_details,hiv_positive}'::text[] AS hiv_positive,
    doc #>> '{fields,pregnancy_details,next_maternal_health_date}'::text[] AS next_maternal_health_date,
    doc #>> '{fields,health_education,select_health_condition}'::text[] AS select_health_condition,
    doc #>> '{contact,_id}'                         AS chw_id,
      h.facility_name,
      h.dhis2_facility_id,
      h.village,
      h.district,
      h.region,
      CURRENT_TIMESTAMP                                 AS last_refresh_date
FROM dwh.cht_data d
LEFT JOIN cht.mv_chw_hierarchy h ON (d.doc #>> '{contact,_id}') = h.chw_id
  WHERE (doc ->> 'form'::text) = 'maternal_health_education'::text AND is_current
WITH DATA;

-- View indexes:
CREATE INDEX mv_maternal_health_education_reported ON cht.mv_maternal_health_education USING btree (reported) tablespace ts_indexes;
CREATE INDEX mv_maternal_health_education_chw_id ON cht.mv_maternal_health_education USING btree (chw_id) tablespace ts_indexes;
CREATE INDEX mv_maternal_health_education_year_month ON cht.mv_maternal_health_education USING btree (year, month) tablespace ts_indexes;
CREATE INDEX mv_maternal_health_education_facility ON cht.mv_maternal_health_education USING btree (facility_name) tablespace ts_indexes;
CREATE INDEX mv_maternal_health_education_district ON cht.mv_maternal_health_education USING btree (district) tablespace ts_indexes;
CREATE INDEX mv_maternal_health_education_region ON cht.mv_maternal_health_education USING btree (region) tablespace ts_indexes;