-- cht.mv_newborn_danger_sign_follow_up source
DROP MATERIALIZED VIEW IF EXISTS cht.mv_newborn_danger_sign_follow_up;
CREATE MATERIALIZED VIEW cht.mv_newborn_danger_sign_follow_up
TABLESPACE ts_report
AS SELECT doc ->> '_id'::text AS uuid,
    doc ->> '_rev'::text AS rev,
    doc ->> 'form'::text AS form,
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    to_char(to_timestamp((((doc ->>'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS monthname,
    (doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    (NULLIF((doc -> 'geolocation'::text) ->> 'latitude'::text, ''::text))::double precision AS geolocation_latitude,
    (NULLIF((doc -> 'geolocation'::text) ->> 'longitude'::text, ''::text))::double precision AS geolocation_longitude,
    (NULLIF((doc -> 'geolocation'::text) ->> 'accuracy'::text, ''::text))::double precision AS geolocation_accuracy,
    (NULLIF((doc -> 'geolocation'::text) ->> 'altitude'::text, ''::text))::double precision AS geolocation_altitude,
    (NULLIF((doc -> 'geolocation'::text) ->> 'altitudeAccuracy'::text, ''::text))::double precision AS geolocation_altitude_accuracy,
    (NULLIF((doc -> 'geolocation'::text) ->> 'speed'::text, ''::text))::double precision AS geolocation_speed,
    (NULLIF((doc -> 'geolocation'::text) ->> 'heading'::text, ''::text))::double precision AS geolocation_heading,
    doc ->> 'from'::text AS submitter,
    doc #>> '{fields,inputs,source}'::text[] AS source,
    doc #>> '{fields,inputs,source_id}'::text[] AS source_id,
    doc #>> '{fields,inputs,t_place_name}'::text[] AS t_place_name,
    doc #>> '{fields,inputs,t_vht_name}'::text[] AS t_vht_name,
    doc #>> '{fields,inputs,t_vht_phone}'::text[] AS t_vht_phone,
    doc #>> '{fields,inputs,user,contact_id}'::text[] AS contact_id,
    doc #>> '{fields,inputs,user,facility_id}'::text[] AS facility_id,
    doc #>> '{fields,inputs,contact,_id}'::text[] AS _id,
    doc #>> '{fields,inputs,contact,name}'::text[] AS name,
    doc #>> '{fields,inputs,contact,date_of_birth}'::text[] AS date_of_birth,
    doc #>> '{fields,inputs,contact,sex}'::text[] AS sex,
    doc #>> '{fields,inputs,contact,parent,_id}'::text[] AS parent__id,
    doc #>> '{fields,inputs,contact,parent,name}'::text[] AS parent_name,
    doc #>> '{fields,inputs,contact,parent,parent,_id}'::text[] AS parent_parent__id,
    doc #>> '{fields,inputs,contact,parent,parent,name}'::text[] AS parent_parent_name,
    doc #>> '{fields,inputs,contact,parent,parent,contact,_id}'::text[] AS contact__id,
    doc #>> '{fields,inputs,contact,parent,parent,contact,name}'::text[] AS contact_name,
    doc #>> '{fields,inputs,contact,parent,parent,contact,phone}'::text[] AS phone,
    doc #>> '{fields,patient_age_in_years}'::text[] AS patient_age_in_years,
    doc #>> '{fields,patient_age_in_months}'::text[] AS patient_age_in_months,
    doc #>> '{fields,patient_age_in_days}'::text[] AS patient_age_in_days,
    doc #>> '{fields,patient_age_display}'::text[] AS patient_age_display,
    doc #>> '{fields,patient_id}'::text[] AS patient_id,
    doc #>> '{fields,patient_name}'::text[] AS patient_name,
    doc #>> '{fields,patient_gender}'::text[] AS patient_gender,
    doc #>> '{fields,chw_name}'::text[] AS chw_name,
    doc #>> '{fields,chw_phone}'::text[] AS chw_phone,
    doc #>> '{fields,chw_village}'::text[] AS chw_village,
    doc #>> '{fields,needs_signoff}'::text[] AS needs_signoff,
    doc #>> '{fields,group_danger_sign_follow_up,taken_to_health_facility}'::text[] AS taken_to_health_facility,
    doc #>> '{fields,group_danger_sign_follow_up,still_experiencing_danger_signs}'::text[] AS still_experiencing_danger_signs,
    doc #>> '{fields,group_danger_sign_follow_up,breathing_difficulty}'::text[] AS breathing_difficulty,
    doc #>> '{fields,group_danger_sign_follow_up,not_breastfeeding_Well}'::text[] AS not_breastfeeding_well,
    doc #>> '{fields,group_danger_sign_follow_up,feels_hot_or_cold}'::text[] AS feels_hot_or_cold,
    doc #>> '{fields,group_danger_sign_follow_up,less_active}'::text[] AS less_active,
    doc #>> '{fields,group_danger_sign_follow_up,yellow_body}'::text[] AS yellow_body,
    doc #>> '{fields,group_danger_sign_follow_up,has_danger_signs}'::text[] AS has_danger_signs,
    doc #>> '{fields,additional_doc,type}'::text[] AS type,
    doc #>> '{fields,additional_doc,content_type}'::text[] AS content_type,
    doc #>> '{fields,additional_doc,form}'::text[] AS form_field,
    doc #>> '{fields,additional_doc,contact,_id}'::text[] AS additional_doc_contact__id,
    doc #>> '{fields,additional_doc,parent,_id}'::text[] AS additional_doc_parent__id,
    doc #>> '{fields,additional_doc,fields,inputs,source}'::text[] AS inputs_source,
    doc #>> '{fields,additional_doc,fields,inputs,source_id}'::text[] AS inputs_source_id,
    doc #>> '{fields,additional_doc,fields,inputs,contact,_id}'::text[] AS inputs_contact__id,
    doc #>> '{fields,additional_doc,fields,inputs,contact,name}'::text[] AS inputs_contact_name,
    doc #>> '{fields,additional_doc,fields,created_by_doc}'::text[] AS created_by_doc,
    doc #>> '{fields,additional_doc,fields,client_id}'::text[] AS client_id,
    doc #>> '{fields,additional_doc,fields,client_uuid}'::text[] AS client_uuid,
    doc #>> '{fields,additional_doc,fields,client_name}'::text[] AS client_name,
    doc #>> '{fields,additional_doc,fields,place_id}'::text[] AS place_id,
    doc #>> '{fields,additional_doc,fields,place_name}'::text[] AS place_name,
    doc #>> '{fields,additional_doc,fields,vht_name}'::text[] AS vht_name,
    doc #>> '{fields,additional_doc,fields,vht_phone}'::text[] AS vht_phone,
    doc #>> '{fields,additional_doc,fields,follow_up_date}'::text[] AS follow_up_date,
    doc #>> '{fields,additional_doc,fields,client_age_in_years}'::text[] AS client_age_in_years,
    doc #>> '{fields,additional_doc,fields,client_age_in_months}'::text[] AS client_age_in_months,
    doc #>> '{fields,additional_doc,fields,client_age_in_days}'::text[] AS client_age_in_days,
    doc #>> '{fields,additional_doc,fields,client_age_display}'::text[] AS client_age_display,
    doc #>> '{fields,additional_doc,fields,client_sex}'::text[] AS client_sex,
    doc #>> '{fields,additional_doc,fields,danger_signs,_breathing_difficulty}'::text[] AS _breathing_difficulty,
    doc #>> '{fields,additional_doc,fields,danger_signs,_not_breastfeeding_Well}'::text[] AS _not_breastfeeding_well,
    doc #>> '{fields,additional_doc,fields,danger_signs,_feels_hot_or_cold}'::text[] AS _feels_hot_or_cold,
    doc #>> '{fields,additional_doc,fields,danger_signs,_less_active}'::text[] AS _less_active,
    doc #>> '{fields,additional_doc,fields,danger_signs,_yellow_body}'::text[] AS _yellow_body,
    doc #>> '{fields,additional_doc_follow_up,type}'::text[] AS additional_doc_follow_up_type,
    doc #>> '{fields,additional_doc_follow_up,content_type}'::text[] AS additional_doc_follow_up_content_type,
    doc #>> '{fields,additional_doc_follow_up,form}'::text[] AS additional_doc_follow_up_form,
    doc #>> '{fields,additional_doc_follow_up,contact,_id}'::text[] AS additional_doc_follow_up_contact__id,
    doc #>> '{fields,additional_doc_follow_up,parent,_id}'::text[] AS additional_doc_follow_up_parent__id,
    doc #>> '{fields,additional_doc_follow_up,fields,inputs,source}'::text[] AS fields_inputs_source,
    doc #>> '{fields,additional_doc_follow_up,fields,inputs,source_id}'::text[] AS fields_inputs_source_id,
    doc #>> '{fields,additional_doc_follow_up,fields,inputs,contact,_id}'::text[] AS fields_inputs_contact__id,
    doc #>> '{fields,additional_doc_follow_up,fields,inputs,contact,name}'::text[] AS fields_inputs_contact_name,
    doc #>> '{fields,additional_doc_follow_up,fields,created_by_doc}'::text[] AS fields_created_by_doc,
    doc #>> '{fields,additional_doc_follow_up,fields,client_id}'::text[] AS fields_client_id,
    doc #>> '{fields,additional_doc_follow_up,fields,client_name}'::text[] AS fields_client_name,
    doc #>> '{fields,additional_doc_follow_up,fields,place_id}'::text[] AS fields_place_id,
    doc #>> '{fields,additional_doc_follow_up,fields,place_name}'::text[] AS fields_place_name,
    doc #>> '{fields,additional_doc_follow_up,fields,vht_name}'::text[] AS fields_vht_name,
    doc #>> '{fields,additional_doc_follow_up,fields,vht_phone}'::text[] AS fields_vht_phone,
    doc #>> '{fields,additional_doc_follow_up,fields,completed_referral}'::text[] AS completed_referral,
    doc #>> '{fields,additional_doc_follow_up,fields,still_has_danger_signs}'::text[] AS still_has_danger_signs,
    doc #>> '{contact,_id}'                         AS chw_id,
      h.facility,
      h.dhis2_facility_id,
      h.village,
      h.district,
      h.region,
      CURRENT_TIMESTAMP                                 AS last_refresh_date  
FROM dwh.cht_data d
LEFT JOIN cht.mv_chw_hierarchy h ON (d.doc #>> '{contact,_id}') = h.chw_id 
 WHERE (doc ->> 'form'::text) = 'newborn_danger_sign_follow_up'::text AND is_current
WITH NO DATA;

-- View indexes:
CREATE INDEX newborn_danger_sign_follow_up_reported_idx ON cht.mv_newborn_danger_sign_follow_up USING btree (reported) tablespace ts_indexes;
CREATE INDEX newborn_danger_sign_follow_up_chw_id_idx ON cht.mv_newborn_danger_sign_follow_up USING btree (chw_id) tablespace ts_indexes;
CREATE INDEX newborn_danger_sign_follow_up_district_idx ON cht.mv_newborn_danger_sign_follow_up USING btree (district) tablespace ts_indexes;
CREATE INDEX newborn_danger_sign_follow_up_facility_id_idx ON cht.mv_newborn_danger_sign_follow_up USING btree (dhis2_facility_id) tablespace ts_indexes;
CREATE INDEX newborn_danger_sign_follow_up_village_idx ON cht.mv_newborn_danger_sign_follow_up USING btree (village) tablespace ts_indexes;
CREATE INDEX newborn_danger_sign_follow_up_region_idx ON cht.mv_newborn_danger_sign_follow_up USING btree (region) tablespace ts_indexes;
CREATE INDEX newborn_danger_sign_follow_up_year_idx ON cht.mv_newborn_danger_sign_follow_up USING btree (year) tablespace ts_indexes;
CREATE INDEX newborn_danger_sign_follow_up_month_idx ON cht.mv_newborn_danger_sign_follow_up USING btree (month) tablespace ts_indexes;
CREATE INDEX newborn_danger_sign_follow_up_patient_id_idx ON cht.mv_newborn_danger_sign_follow_up USING btree (patient_id) tablespace ts_indexes;