-- cht.mv_pregnancy source

CREATE MATERIALIZED VIEW cht.mv_pregnancy
TABLESPACE ts_report
AS SELECT d.doc ->> '_id'::text AS doc_id,
    d.doc ->> '_rev'::text AS rev,
    d.doc ->> 'form'::text AS form,
    d.doc ->> 'from'::text AS "from",
    d.doc ->> 'type'::text AS type,
    to_timestamp((NULLIF(d.doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'YYYY-MM-DD'::text)::date AS date,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'YYYY'::text)::integer AS year,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'FMMonth'::text) AS monthname,
    ((d.doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (d.doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (d.doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    NULLIF((d.doc -> 'geolocation'::text) ->> 'latitude'::text, ''::text)::double precision AS geolocation_latitude,
    NULLIF((d.doc -> 'geolocation'::text) ->> 'longitude'::text, ''::text)::double precision AS geolocation_longitude,
    NULLIF((d.doc -> 'geolocation'::text) ->> 'accuracy'::text, ''::text)::double precision AS geolocation_accuracy,
    NULLIF((d.doc -> 'geolocation'::text) ->> 'altitude'::text, ''::text)::double precision AS geolocation_altitude,
    NULLIF((d.doc -> 'geolocation'::text) ->> 'altitudeAccuracy'::text, ''::text)::double precision AS geolocation_altitude_accuracy,
    NULLIF((d.doc -> 'geolocation'::text) ->> 'speed'::text, ''::text)::double precision AS geolocation_speed,
    NULLIF((d.doc -> 'geolocation'::text) ->> 'heading'::text, ''::text)::double precision AS geolocation_heading,
    d.doc #>> '{fields,inputs,source}'::text[] AS source,
    d.doc #>> '{fields,inputs,source_id}'::text[] AS source_id,
    d.doc #>> '{fields,inputs,user,contact_id}'::text[] AS user_contact_id,
    d.doc #>> '{fields,inputs,user,facility_id}'::text[] AS user_facility_id,
    d.doc #>> '{fields,inputs,contact,_id}'::text[] AS inputs_contact_id,
    d.doc #>> '{fields,inputs,contact,name}'::text[] AS inputs_contact_name,
    d.doc #>> '{fields,inputs,contact,date_of_birth}'::text[] AS inputs_contact_date_of_birth,
    d.doc #>> '{fields,inputs,contact,sex}'::text[] AS inputs_contact_sex,
    d.doc #>> '{fields,inputs,contact,parent,_id}'::text[] AS inputs_parent_id,
    d.doc #>> '{fields,inputs,contact,parent,name}'::text[] AS inputs_parent_name,
    d.doc #>> '{fields,is_of_child_bearing_age}'::text[] AS is_of_child_bearing_age,
    d.doc #>> '{fields,visited_contact_uuid}'::text[] AS visited_contact_uuid,
    d.doc #>> '{fields,patient_age_in_years}'::text[] AS patient_age_in_years,
    d.doc #>> '{fields,patient_age_in_months}'::text[] AS patient_age_in_months,
    d.doc #>> '{fields,patient_age_in_days}'::text[] AS patient_age_in_days,
    d.doc #>> '{fields,patient_age_display}'::text[] AS patient_age_display,
    d.doc #>> '{fields,patient_id}'::text[] AS patient_id,
    d.doc #>> '{fields,patient_name}'::text[] AS patient_name,
    d.doc #>> '{fields,patient_gender}'::text[] AS patient_gender,
    d.doc #>> '{fields,edd_std}'::text[] AS edd_std,
    d.doc #>> '{fields,edd_local}'::text[] AS edd_local,
    d.doc #>> '{fields,lmp}'::text[] AS lmp,
    d.doc #>> '{fields,nutrition_follow_up_date}'::text[] AS nutrition_follow_up_date,
    d.doc #>> '{fields,referred_for_nutrition_follow_up}'::text[] AS referred_for_nutrition_follow_up,
    d.doc #>> '{fields,chw_area_name}'::text[] AS chw_area_name,
    d.doc #>> '{fields,chw_name}'::text[] AS chw_name,
    d.doc #>> '{fields,chw_phone}'::text[] AS chw_phone,
    d.doc #>> '{fields,chw_village}'::text[] AS chw_village,
    d.doc #>> '{fields,needs_signoff}'::text[] AS needs_signoff,
    d.doc #>> '{fields,additional_doc,follow_up_date}'::text[] AS follow_up_date,
    d.doc #>> '{fields,additional_doc,client_age_in_years}'::text[] AS client_age_in_years,
    d.doc #>> '{fields,additional_doc,client_age_in_months}'::text[] AS client_age_in_months,
    d.doc #>> '{fields,additional_doc,client_age_in_days}'::text[] AS client_age_in_days,
    d.doc #>> '{fields,additional_doc,client_age_display}'::text[] AS client_age_display,
    d.doc #>> '{fields,additional_doc,client_sex}'::text[] AS client_sex,
    d.doc #>> '{fields,additional_doc,client_id}'::text[] AS client_id,
    d.doc #>> '{fields,additional_doc,client_uuid}'::text[] AS client_uuid,
    d.doc #>> '{fields,additional_doc,client_name}'::text[] AS client_name,
    d.doc #>> '{fields,additional_doc,place_id}'::text[] AS place_id,
    d.doc #>> '{fields,additional_doc,place_name}'::text[] AS place_name,
    d.doc #>> '{fields,additional_doc,vht_name}'::text[] AS vht_name,
    d.doc #>> '{fields,additional_doc,vht_phone}'::text[] AS vht_phone,
    d.doc #>> '{fields,group_safe_pregnancy_practices,using_llin}'::text[] AS using_llin,
    d.doc #>> '{fields,group_safe_pregnancy_practices,note_llin_prevents_malaria}'::text[] AS note_llin_prevents_malaria,
    d.doc #>> '{fields,group_safe_pregnancy_practices,refer_client_to_health_facility}'::text[] AS refer_client_to_health_facility,
    d.doc #>> '{fields,group_safe_pregnancy_practices,has_tt_card}'::text[] AS has_tt_card,
    d.doc #>> '{fields,group_safe_pregnancy_practices,tt_immunizations}'::text[] AS tt_immunizations,
    d.doc #>> '{fields,group_safe_pregnancy_practices,note_tt_protects_newborn_and_mother}'::text[] AS note_tt_protects_newborn_and_mother,
    d.doc #>> '{fields,group_safe_pregnancy_practices,note_two_tt_vaccines_per_pregnancy}'::text[] AS note_two_tt_vaccines_per_pregnancy,
    d.doc #>> '{fields,group_safe_pregnancy_practices,tt_refer_ack}'::text[] AS tt_refer_ack,
    d.doc #>> '{fields,group_safe_pregnancy_practices,received_tt_immunizations}'::text[] AS received_tt_immunizations,
    d.doc #>> '{fields,group_safe_pregnancy_practices,note_provide_nutrition_education}'::text[] AS note_provide_nutrition_education,
    d.doc #>> '{fields,group_safe_pregnancy_practices,note_encourage_micro_nutrient_supplementation}'::text[] AS note_encourage_micro_nutrient_supplementation,
    d.doc #>> '{fields,group_safe_pregnancy_practices,note_encourage_sleep_under_itns}'::text[] AS note_encourage_sleep_under_itns,
    d.doc #>> '{fields,group_safe_pregnancy_practices,note_encourage_men_to_participate}'::text[] AS note_encourage_men_to_participate,
    d.doc #>> '{fields,group_safe_pregnancy_practices,note_encourage_to_go_for_anc}'::text[] AS note_encourage_to_go_for_anc,
    d.doc #>> '{fields,group_nutrition_status,note_nutrition_status}'::text[] AS note_nutrition_status,
    d.doc #>> '{fields,group_nutrition_status,taken_muac}'::text[] AS taken_muac,
    d.doc #>> '{fields,group_nutrition_status,muac_measurement}'::text[] AS muac_measurement,
    d.doc #>> '{fields,group_nutrition_status,encourage_client_to_consume_sufficient_diet}'::text[] AS encourage_client_to_consume_sufficient_diet,
    d.doc #>> '{fields,group_nutrition_status,note_has_sam}'::text[] AS note_has_sam,
    d.doc #>> '{fields,group_nutrition_status,note_has_mam}'::text[] AS note_has_mam,
    d.doc #>> '{fields,group_nutrition_status,note_refer_to_health_facility}'::text[] AS note_refer_to_health_facility,
    d.doc #>> '{fields,group_nutrition_status,referred_to_health_facility_nutrition}'::text[] AS referred_to_health_facility_nutrition,
    d.doc #>> '{fields,group_nutrition_status,micro_nutrient_supplementation_received}'::text[] AS micro_nutrient_supplementation_received,
    d.doc #>> '{fields,group_nutrition_status,note_encourage_micro-nutrients}'::text[] AS note_encourage_micro_nutrients,
    d.doc #>> '{fields,group_nutrition_status,refer_to_health_facility_no_micro_nutrients}'::text[] AS refer_to_health_facility_no_micro_nutrients,
    d.doc #>> '{fields,group_nutrition_status,on_nutrition_follow_up}'::text[] AS on_nutrition_follow_up,
    d.doc #>> '{fields,group_nutrition_status,completed_last_nutrition_follow_up}'::text[] AS completed_last_nutrition_follow_up,
    d.doc #>> '{fields,group_nutrition_status,schedule_follow_up_visit}'::text[] AS schedule_follow_up_visit,
    d.doc #>> '{fields,group_nutrition_status,next_nutrition_follow_up_date}'::text[] AS next_nutrition_follow_up_date,
    d.doc #>> '{fields,group_nutrition_status,note_thank_you_nutrition_follow_up}'::text[] AS note_thank_you_nutrition_follow_up,
    d.doc #>> '{fields,group_nutrition_status,note_refer_did_not_complete_follow_up}'::text[] AS note_refer_did_not_complete_follow_up,
    d.doc #>> '{fields,group_nutrition_status,referred_to_health_facility_missed_nutrition_follow_up}'::text[] AS referred_to_health_facility_missed_nutrition_follow_up,
    d.doc #>> '{fields,group_danger_sign_check,note_danger_signs}'::text[] AS ds_note_danger_signs,
    d.doc #>> '{fields,group_danger_sign_check,vaginal_bleeding}'::text[] AS ds_vaginal_bleeding,
    d.doc #>> '{fields,group_danger_sign_check,lower_abdomen_pain}'::text[] AS ds_lower_abdomen_pain,
    d.doc #>> '{fields,group_danger_sign_check,severe_headache}'::text[] AS ds_severe_headache,
    d.doc #>> '{fields,group_danger_sign_check,very_pale}'::text[] AS ds_very_pale,
    d.doc #>> '{fields,group_danger_sign_check,fever}'::text[] AS ds_fever,
    d.doc #>> '{fields,group_danger_sign_check,reduced_or_no_feotal_movements}'::text[] AS ds_reduced_or_no_feotal_movements,
    d.doc #>> '{fields,group_danger_sign_check,blurred_vision}'::text[] AS ds_blurred_vision,
    d.doc #>> '{fields,group_danger_sign_check,swelling}'::text[] AS ds_swelling,
    d.doc #>> '{fields,group_danger_sign_check,breathlessness}'::text[] AS ds_breathlessness,
    d.doc #>> '{fields,group_danger_sign_check,has_danger_signs}'::text[] AS ds_has_danger_signs,
    d.doc #>> '{fields,group_danger_sign_check,has_no_danger_signs}'::text[] AS ds_has_no_danger_signs,
    d.doc #>> '{fields,group_danger_sign_check,note_has_no_danger_signs}'::text[] AS ds_note_has_no_danger_signs,
    d.doc #>> '{fields,group_danger_sign_check,note_has_danger_signs}'::text[] AS ds_note_has_danger_signs,
    d.doc #>> '{fields,group_danger_sign_check,referred_to_health_facility_danger_signs}'::text[] AS ds_referred_to_health_facility_danger_signs,
    d.doc #>> '{fields,group_danger_sign_check,note_complete_follow_up_task}'::text[] AS ds_note_complete_follow_up_task,
    d.doc #>> '{fields,group_scheduled_anc_visits,note_check_for_upcoming_anc_visits}'::text[] AS note_check_for_upcoming_anc_visits,
    d.doc #>> '{fields,group_scheduled_anc_visits,has_upcoming_anc_visits}'::text[] AS has_upcoming_anc_visits,
    d.doc #>> '{fields,group_scheduled_anc_visits,anc_appointment_date}'::text[] AS anc_appointment_date,
    d.doc #>> '{fields,group_past_anc_visits,number_of_anc_visits}'::text[] AS number_of_anc_visits,
    d.doc #>> '{fields,group_past_anc_visits,anc_visits}'::text[] AS anc_visits,
    d.doc #>> '{fields,group_past_anc_visits,hiv_test_done}'::text[] AS hiv_test_done,
    d.doc #>> '{fields,group_past_anc_visits,hiv_test_result}'::text[] AS hiv_test_result,
    d.doc #>> '{fields,group_past_anc_visits,note_reduce_risk_of_hiv}'::text[] AS note_reduce_risk_of_hiv,
    d.doc #>> '{fields,group_past_anc_visits,on_art_treatment}'::text[] AS on_art_treatment,
    d.doc #>> '{fields,group_past_anc_visits,taking_medication}'::text[] AS taking_medication,
    d.doc #>> '{fields,group_past_anc_visits,explain_the_mportance_of_taking_medication}'::text[] AS explain_the_mportance_of_taking_medication,
    d.doc #>> '{fields,group_past_anc_visits,note_encourage_client_to_take_medication}'::text[] AS note_encourage_client_to_take_medication,
    d.doc #>> '{fields,group_gestational_Age,note_pregnancy_registration_introduction}'::text[] AS note_pregnancy_registration_introduction,
    d.doc #>> '{fields,group_gestational_Age,pregnancy_report_method}'::text[] AS pregnancy_report_method,
    d.doc #>> '{fields,group_gestational_Age,lmp_start_date}'::text[] AS lmp_start_date,
    d.doc #>> '{fields,group_gestational_Age,lmp_start_date_local}'::text[] AS lmp_start_date_local,
    d.doc #>> '{fields,group_gestational_Age,estimated_edd_std}'::text[] AS estimated_edd_std,
    d.doc #>> '{fields,group_gestational_Age,estimated_edd_local}'::text[] AS estimated_edd_local,
    d.doc #>> '{fields,group_gestational_Age,note_entered_lmp}'::text[] AS note_entered_lmp,
    d.doc #>> '{fields,group_gestational_Age,note_estimated_edd}'::text[] AS note_estimated_edd,
    d.doc #>> '{fields,group_gestational_Age,entered_edd}'::text[] AS entered_edd,
    d.doc #>> '{fields,group_gestational_Age,entered_edd_local}'::text[] AS entered_edd_local,
    d.doc #>> '{fields,group_gestational_Age,pregnancy_age_in_weeks}'::text[] AS pregnancy_age_in_weeks,
    d.doc #>> '{fields,group_gestational_Age,note_pregnancy_age}'::text[] AS note_pregnancy_age,
    d.doc #>> '{fields,group_gestational_Age,note_no_information}'::text[] AS note_no_information,
    d.doc #>> '{fields,danger_signs,_vaginal_bleeding}'::text[] AS vaginal_bleeding,
    d.doc #>> '{fields,danger_signs,_lower_abdomen_pain}'::text[] AS lower_abdomen_pain,
    d.doc #>> '{fields,danger_signs,_severe_headache}'::text[] AS severe_headache,
    d.doc #>> '{fields,danger_signs,_very_pale}'::text[] AS very_pale,
    d.doc #>> '{fields,danger_signs,_fever}'::text[] AS fever,
    d.doc #>> '{fields,danger_signs,_reduced_or_no_feotal_movements}'::text[] AS reduced_or_no_feotal_movements,
    d.doc #>> '{fields,danger_signs,_blurred_vision}'::text[] AS blurred_vision,
    d.doc #>> '{fields,danger_signs,_swelling}'::text[] AS swelling,
    d.doc #>> '{fields,danger_signs,_breathlessness}'::text[] AS breathlessness,
    d.doc #>> '{contact,_id}'::text[] AS chw_id,
    h.facility,
    h.dhis2_facility_id,
    h.village,
    h.district,
    h.region,
    CURRENT_TIMESTAMP AS last_refresh_date
   FROM dwh.cht_data d
     LEFT JOIN cht.mv_chw_hierarchy h ON (d.doc #>> '{contact,_id}'::text[]) = h.chw_id
  WHERE (d.doc ->> 'form'::text) = 'pregnancy'::text AND d.is_current
WITH DATA;

-- View indexes:
CREATE INDEX pregnancy_date_idx ON cht.mv_pregnancy USING btree (date);
CREATE INDEX pregnancy_district_idx ON cht.mv_pregnancy USING btree (district);
CREATE INDEX pregnancy_monthname_idx ON cht.mv_pregnancy USING btree (monthname);
CREATE INDEX pregnancy_region_idx ON cht.mv_pregnancy USING btree (region);
CREATE INDEX pregnancy_reported_idx ON cht.mv_pregnancy USING btree (reported);
CREATE INDEX pregnancy_village_idx ON cht.mv_pregnancy USING btree (village);
CREATE INDEX pregnancy_year_month_district_idx ON cht.mv_pregnancy USING btree (year, month, district);