CREATE MATERIALIZED VIEW report.useview_pnc_baby_follow_up
TABLESPACE ts_report
AS
SELECT
       doc ->> '_id'::text                              AS doc_id,
      doc ->> '_rev'::text                             AS rev,                                 -- [NEW FIELD]
      to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
     (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
     (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
     TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS month,
     doc ->'fields'->'meta'->>'instanceID' AS instanceID,
     doc ->'fields'->'inputs'->'meta'->>'deprecatedID' AS deprecatedID,
     doc ->'fields'->'inputs'->'meta'->'location'->>'lat' AS location_lat,
     doc ->'fields'->'inputs'->'meta'->'location'->>'long' AS location_long,
     doc ->'fields'->'inputs'->'meta'->'location'->>'error' AS location_error,
     doc ->'fields'->'inputs'->'meta'->'location'->>'message' AS location_message,
     doc ->'geolocation'->>'code' AS geolocation_code,
     doc ->'geolocation'->>'message' AS geolocation_message,
     doc ->> 'form'::text                             AS  form,
     doc ->> 'from'::text                             AS  from,
     

     doc #>> '{fields,inputs,source}'                                    AS source,
     doc #>> '{fields,inputs,source_id}'                                 AS source_id,
     doc #>> '{fields,inputs,user,contact_id}'                           AS user_contact_id,
     doc #>> '{fields,inputs,user,facility_id}'                          AS user_facility_id,
     doc #>> '{fields,inputs,contact,_id}'                               AS contact_id,
     doc #>> '{fields,inputs,contact,name}'                              AS contact_name,
     doc #>> '{fields,inputs,contact,date_of_birth}'                     AS contact_date_of_birth,
     doc #>> '{fields,inputs,contact,sex}'                               AS contact_sex,

      doc #>> '{fields,patient_age_in_years}'::text[]      AS patient_age_in_years,
      doc #>> '{fields,patient_age_in_months}'::text[]     AS patient_age_in_months,
      doc #>> '{fields,patient_age_in_days}'::text[]       AS patient_age_in_days,
      doc #>> '{fields,patient_age_display}'::text[]       AS patient_age_display,
      doc #>> '{fields,patient_id}'::text[]                AS patient_id,
      doc #>> '{fields,patient_name}'::text[]              AS patient_name,
      doc #>> '{fields,patient_name_with_s}'::text[]       AS patient_name_with_s,
      doc #>> '{fields,patient_gender}'::text[]            AS patient_gender,
      doc #>> '{fields,has_danger_signs}'::text[]          AS has_danger_signs,
      doc #>> '{fields,pnc_visit_label}'::text[]           AS pnc_visit_label,
      doc #>> '{fields,chw_name}'::text[]                  AS chw_name,
      doc #>> '{fields,chw_phone}'::text[]                 AS chw_phone,
      doc #>> '{fields,chw_village}'::text[]               AS chw_village,

      doc #>> '{fields,group_pnc_visit_details,has_attended_pnc}'::text[]        AS has_attended_pnc,
      doc #>> '{fields,group_pnc_visit_details,patient_age_1_day_older}'::text[] AS patient_age_1_day_older,
      doc #>> '{fields,group_pnc_visit_details,pnc_visit}'::text[]               AS pnc_visit,
      doc #>> '{fields,group_pnc_visit_details,pnc_visit_date}'::text[]          AS pnc_visit_date,

      doc #>> '{fields,group_missed_pnc,reason_missed_pnc}'::text[]           AS reason_missed_pnc,
      doc #>> '{fields,group_missed_pnc,other_missed_pnc}'::text[]            AS other_missed_pnc,
      doc #>> '{fields,group_missed_pnc,has_agreed_to_pnc_visit}'::text[]     AS has_agreed_to_pnc_visit,
      doc #>> '{fields,group_missed_pnc,note_pnc_visit_counsel}'::text[]      AS note_pnc_visit_counsel,
      doc #>> '{fields,group_missed_pnc,date_agreed_to_pnc_visit}'::text[]    AS date_agreed_to_pnc_visit,

      doc #>> '{fields,group_patient_summary,s_note_patient_assessment}'::text[]         AS s_note_patient_assessment,
      doc #>> '{fields,group_patient_summary,s_note_before_submit}'::text[]              AS s_note_before_submit,
      doc #>> '{fields,group_patient_summary,s_note_patient_details}'::text[]           AS s_note_patient_details,
      doc #>> '{fields,group_patient_summary,s_note_patient_details_values}'::text[]    AS s_note_patient_details_values,
      doc #>> '{fields,group_patient_summary,s_note_baby_condition}'::text[]            AS s_note_baby_condition,
      doc #>> '{fields,group_patient_summary,s_note_baby_alive}'::text[]                AS s_note_baby_alive,
      doc #>> '{fields,group_patient_summary,s_note_baby_deceased}'::text[]             AS s_note_baby_deceased,
      doc #>> '{fields,group_patient_summary,s_note_danger_signs}'::text[]              AS s_note_danger_signs,
      doc #>> '{fields,group_patient_summary,s_note_child_has_chest_in_drawing}'::text[] AS s_note_child_has_chest_in_drawing,
      doc #>> '{fields,group_patient_summary,s_note_child_has_convulsions}'::text[]     AS s_note_child_has_convulsions,
      doc #>> '{fields,group_patient_summary,s_note_child_vomiting_everything}'::text[] AS s_note_child_vomiting_everything,
      doc #>> '{fields,group_patient_summary,s_note_child_unconscious}'::text[]         AS s_note_child_unconscious,
      doc #>> '{fields,group_patient_summary,s_note_child_has_infected_umbilical_cord}'::text[] AS s_note_child_has_infected_umbilical_cord,
      doc #>> '{fields,group_patient_summary,s_note_child_has_difficulty_feeding}'::text[] AS s_note_child_has_difficulty_feeding,
      doc #>> '{fields,group_patient_summary,s_note_child_has_body_stiffness}'::text[]   AS s_note_child_has_body_stiffness,
      doc #>> '{fields,group_patient_summary,s_note_child_has_fever}'::text[]            AS s_note_child_has_fever,
      doc #>> '{fields,group_patient_summary,s_note_child_has_yellow_skin}'::text[]      AS s_note_child_has_yellow_skin,
      doc #>> '{fields,group_patient_summary,s_note_pnc_visit_details}'::text[]          AS s_note_pnc_visit_details,
      doc #>> '{fields,group_patient_summary,s_note_completed_pnc}'::text[]              AS s_note_completed_pnc,
      doc #>> '{fields,group_patient_summary,s_note_remaining_pnc_visits}'::text[]      AS s_note_remaining_pnc_visits,
      doc #>> '{fields,group_patient_summary,s_note_referral}'::text[]                   AS s_note_referral,
      doc #>> '{fields,group_patient_summary,s_note_refer}'::text[]                      AS s_note_refer,
      doc #>> '{fields,group_patient_summary,s_note_follow_up}'::text[]                  AS s_note_follow_up,
      doc #>> '{fields,group_patient_summary,s_note_conduct_follow_up}'::text[]         AS s_note_conduct_follow_up,

      doc #>> '{fields,group_baby_condition,baby_condition}'::text[]               AS baby_condition,
      doc #>> '{fields,group_baby_condition,death_date}'::text[]                  AS death_date,
      doc #>> '{fields,group_baby_condition,breastfeeding_exclusively}'::text[]   AS breastfeeding_exclusively,
      doc #>> '{fields,group_baby_condition,breastfeeding_within_1hour_delivery}'::text[] AS breastfeeding_within_1hour_delivery,
      doc #>> '{fields,group_baby_condition,note_any_danger_signs}'::text[]        AS note_any_danger_signs,
      doc #>> '{fields,group_baby_condition,child_has_chest_in_drawing}'::text[]  AS child_has_chest_in_drawing,
      doc #>> '{fields,group_baby_condition,child_has_convulsions}'::text[]       AS child_has_convulsions,
      doc #>> '{fields,group_baby_condition,child_vomiting_everything}'::text[]   AS child_vomiting_everything,
      doc #>> '{fields,group_baby_condition,child_unconscious}'::text[]           AS child_unconscious,
      doc #>> '{fields,group_baby_condition,child_has_infected_umbilical_cord}'::text[] AS child_has_infected_umbilical_cord,
      doc #>> '{fields,group_baby_condition,child_has_difficulty_feeding}'::text[] AS child_has_difficulty_feeding,
      doc #>> '{fields,group_baby_condition,child_has_body_stiffness}'::text[]    AS child_has_body_stiffness,
      doc #>> '{fields,group_baby_condition,child_has_fever}'::text[]             AS child_has_fever,
      doc #>> '{fields,group_baby_condition,child_has_yellow_skin}'::text[]       AS child_has_yellow_skin,
      doc #>> '{fields,group_baby_condition,note_refer_to_facility}'::text[]      AS note_refer_to_facility,
      doc #>> '{fields,group_baby_condition,referred_to_facility}'::text[]        AS referred_to_facility,

      doc #>> '{fields,additional_doc,type}'::text[]                     AS additional_doc_type,
      doc #>> '{fields,additional_doc,content_type}'::text[]            AS additional_doc_content_type,
      doc #>> '{fields,additional_doc,form}'::text[]                     AS additional_doc_form,
      doc #>> '{fields,additional_doc,contact,_id}'::text[]             AS additional_doc_contact__id,
      doc #>> '{fields,additional_doc,parent,_id}'::text[]              AS additional_doc_parent__id,
      doc #>> '{fields,additional_doc,fields,inputs,source}'::text[]    AS additional_doc_inputs_source,
      doc #>> '{fields,additional_doc,fields,inputs,source_id}'::text[] AS additional_doc_inputs_source_id,
      doc #>> '{fields,additional_doc,fields,created_by_doc}'::text[]   AS additional_doc_created_by_doc,
      doc #>> '{fields,additional_doc,fields,client_id}'::text[]        AS additional_doc_client_id,
      doc #>> '{fields,additional_doc,fields,client_uuid}'::text[]      AS additional_doc_client_uuid,
      doc #>> '{fields,additional_doc,fields,client_name}'::text[]      AS additional_doc_client_name,
      doc #>> '{fields,additional_doc,fields,place_id}'::text[]         AS additional_doc_place_id,
      doc #>> '{fields,additional_doc,fields,place_name}'::text[]       AS additional_doc_place_name,
      doc #>> '{fields,additional_doc,fields,vht_name}'::text[]         AS additional_doc_vht_name,
      doc #>> '{fields,additional_doc,fields,vht_phone}'::text[]        AS additional_doc_vht_phone,
      doc #>> '{fields,additional_doc,fields,follow_up_date}'::text[]   AS additional_doc_follow_up_date,
      doc #>> '{fields,additional_doc,fields,client_age_in_years}'::text[]   AS additional_doc_client_age_in_years,
      doc #>> '{fields,additional_doc,fields,client_age_in_months}'::text[]  AS additional_doc_client_age_in_months,
      doc #>> '{fields,additional_doc,fields,client_age_in_days}'::text[]    AS additional_doc_client_age_in_days,
      doc #>> '{fields,additional_doc,fields,client_age_display}'::text[]    AS additional_doc_client_age_display,
      doc #>> '{fields,additional_doc,fields,client_sex}'::text[]            AS additional_doc_client_sex,
      doc #>> '{fields,additional_doc,fields,danger_signs,_child_has_chest_in_drawing}'::text[] AS additional_doc_child_has_chest_in_drawing,
      doc #>> '{fields,additional_doc,fields,danger_signs,_child_has_convulsions}'::text[]      AS additional_doc_child_has_convulsions,
      doc #>> '{fields,additional_doc,fields,danger_signs,_child_vomiting_everything}'::text[]  AS additional_doc_child_vomiting_everything,
      doc #>> '{fields,additional_doc,fields,danger_signs,_child_unconscious}'::text[]          AS additional_doc_child_unconscious,
      doc #>> '{fields,additional_doc,fields,danger_signs,_child_has_infected_umbilical_cord}'::text[] AS additional_doc_child_has_infected_umbilical_cord,
      doc #>> '{fields,additional_doc,fields,danger_signs,_child_has_difficulty_feeding}'::text[]      AS additional_doc_child_has_difficulty_feeding,
      doc #>> '{fields,additional_doc,fields,danger_signs,_child_has_body_stiffness}'::text[]          AS additional_doc_child_has_body_stiffness,
      doc #>> '{fields,additional_doc,fields,danger_signs,_child_has_fever}'::text[]                   AS additional_doc_child_has_fever,
      doc #>> '{fields,additional_doc,fields,danger_signs,_child_has_yellow_skin}'::text[]             AS additional_doc_child_has_yellow_skin,
  --- reporting hierarchy
    doc #>> '{contact,_id}'                         AS chw_id,                   
    doc #>> '{contact,parent,_id}'                  AS chw_area_id,  
    doc #>> '{contact,parent,parent,_id}'           AS facility_id,                                    
    doc #>> '{contact,parent,parent,parent,_id}'    AS parish,              
    doc #>> '{contact,parent,parent,parent,parent,_id}'           AS district,                 
    doc #>> '{contact,parent,parent,parent,parent,parent,_id}'           AS region                 


FROM dwh.cht_data AS couchdb
WHERE (doc ->> 'form') = 'pnc_baby_follow_up'
  AND is_current
WITH DATA;

CREATE UNIQUE INDEX pnc_baby_follow_up_uuid_idx
    ON report.useview_pnc_baby_follow_up USING btree (uuid);

CREATE INDEX pnc_baby_follow_up_reported_idx
    ON report.useview_pnc_baby_follow_up USING btree (reported);
