-- cht.mv_support_supervision source
DROP MATERIALIZED VIEW cht.mv_support_supervision;
CREATE MATERIALIZED VIEW cht.mv_support_supervision
TABLESPACE ts_report
AS SELECT d.doc ->> '_id'::text AS doc_id,
    d.doc ->> '_rev'::text AS rev,
    to_timestamp((NULLIF(d.doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'YYYY-MM-DD'::text)::date AS date,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'YYYY'::text)::integer AS year,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    to_char(to_timestamp((((d.doc ->> 'reported_date'::text)::bigint) / 1000)::double precision), 'FMMonth'::text) AS monthname,
    ((d.doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((d.doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (d.doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (d.doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'latitude'::text, ''::text))::double precision AS geolocation_latitude,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'longitude'::text, ''::text))::double precision AS geolocation_longitude,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'accuracy'::text, ''::text))::double precision AS geolocation_accuracy,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'altitude'::text, ''::text))::double precision AS geolocation_altitude,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'altitudeAccuracy'::text, ''::text))::double precision AS geolocation_altitude_accuracy,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'speed'::text, ''::text))::double precision AS geolocation_speed,
    (NULLIF((d.doc -> 'geolocation'::text) ->> 'heading'::text, ''::text))::double precision AS geolocation_heading,
    d.doc ->> 'form'::text AS form,
    d.doc ->> 'from'::text AS "from",
    d.doc #>> '{fields,source}'::text[] AS source,
    d.doc #>> '{fields,source_id}'::text[] AS source_id,
    d.doc #>> '{fields,inputs,task_id}'::text[] AS task_id,
    d.doc #>> '{fields,inputs,contact,_id}'::text[] AS inputs_contact_id,
    d.doc #>> '{fields,inputs,contact,patient_id}'::text[] AS inputs_contact_patient_id,
    d.doc #>> '{fields,inputs,contact,name}'::text[] AS inputs_contact_name,
    d.doc #>> '{fields,inputs,contact,contact,reported_date}'::text[] AS reported_date,
    d.doc #>> '{fields,inputs,contact,parent,_id}'::text[] AS parent_id, --
    d.doc #>> '{fields,inputs,contact,parent,parent,name}'::text[] AS parent_name,
    d.doc #>> '{fields,inputs,contact,parent,parent,phone}'::text[] AS phone,
    d.doc #>> '{fields,patient_id}'::text[] AS patient_id,
    d.doc #>> '{fields,vht_name}'::text[] AS vht_name,
    d.doc #>> '{fields,last_supervised}'::text[] AS last_supervised,
    d.doc #>> '{fields,supervisions_last_quarter}'::text[] AS supervisions_last_quarter,
    d.doc #>> '{fields,months_active}'::text[] AS months_active,
    d.doc #>> '{fields,commodity_gloves}'::text[] AS commodity_gloves,
    d.doc #>> '{fields,commodity_malaria}'::text[] AS commodity_malaria,
    d.doc #>> '{fields,commodity_muac}'::text[] AS commodity_muac,
    d.doc #>> '{fields,commodity_act}'::text[] AS commodity_act,
    d.doc #>> '{fields,commodity_amox}'::text[] AS commodity_amox,
    d.doc #>> '{fields,commodity_ors}'::text[] AS commodity_ors,
    d.doc #>> '{fields,commodity_rectal}'::text[] AS commodity_rectal,
    d.doc #>> '{fields,commodity_pops}'::text[] AS commodity_pops,
    d.doc #>> '{fields,commodity_cocs}'::text[] AS commodity_cocs,
    d.doc #>> '{fields,commodity_ec}'::text[] AS commodity_ec,
    d.doc #>> '{fields,details,vht_name_usage}'::text[] AS vht_name_usage,
    d.doc #>> '{fields,details,vht_education}'::text[] AS vht_education,
    d.doc #>> '{fields,support_supervision,supervision_type}'::text[] AS supervision_type,
    d.doc #>> '{fields,support_supervision,note_scheduled}'::text[] AS note_scheduled,
    d.doc #>> '{fields,support_supervision,note_spot_checking}'::text[] AS note_spot_checking,
    d.doc #>> '{fields,support_supervision,facility}'::text[] AS supervision_facility,
    d.doc #>> '{fields,support_supervision,note_number_supervision}'::text[] AS note_number_supervision,
    d.doc #>> '{fields,support_supervision,note_last_supervised}'::text[] AS note_last_supervised,
    d.doc #>> '{fields,support_supervision,last_supervision}'::text[] AS last_supervision,
    d.doc #>> '{fields,support_supervision,feedback}'::text[] AS supervision_feedback,
    d.doc #>> '{fields,support_supervision,actions,action_taken}'::text[] AS supervision_action_taken,
    d.doc #>> '{fields,support_supervision,actions,solution}'::text[] AS supervision_solution,
    d.doc #>> '{fields,support_supervision,actions,solution_timeline}'::text[] AS supervision_solution_timeline,
    d.doc #>> '{fields,support_supervision,actions,responsible_person}'::text[] AS supervision_responsible_person,
    d.doc #>> '{fields,training,services_offered}'::text[] AS services_offered,
    d.doc #>> '{fields,training,specify}'::text[] AS training_specify,
    d.doc #>> '{fields,training,vht_training}'::text[] AS vht_training,
    d.doc #>> '{fields,training,echis_training}'::text[] AS echis_training,
    d.doc #>> '{fields,training,actions,action_taken}'::text[] AS training_action_taken,
    d.doc #>> '{fields,training,actions,solution}'::text[] AS training_solution,
    d.doc #>> '{fields,training,actions,solution_timeline}'::text[] AS training_solution_timeline,
    d.doc #>> '{fields,training,actions,responsible_person}'::text[] AS training_responsible_person,
    d.doc #>> '{fields,tools_guidelines,tools}'::text[] AS tools,
    d.doc #>> '{fields,tools_guidelines,specify_tools}'::text[] AS specify_tools,
    d.doc #>> '{fields,tools_guidelines,iccm_tools}'::text[] AS iccm_tools,
    d.doc #>> '{fields,tools_guidelines,specify_icmm_tools}'::text[] AS specify_icmm_tools,
    d.doc #>> '{fields,tools_guidelines,paper}'::text[] AS paper,
    d.doc #>> '{fields,tools_guidelines,actions,action_taken}'::text[] AS tools_action_taken,
    d.doc #>> '{fields,tools_guidelines,actions,solution_timeline}'::text[] AS tools_solution_timeline,
    d.doc #>> '{fields,tools_guidelines,actions,responsible_person}'::text[] AS tools_responsible_person,
    d.doc #>> '{fields,medicines,available_medicines}'::text[] AS available_medicines,
    d.doc #>> '{fields,medicines,physical_count}'::text[] AS physical_count,
    d.doc #>> '{fields,medicines,stock_out}'::text[] AS stock_out,
    d.doc #>> '{fields,medicines,replenished}'::text[] AS replenished,
    d.doc #>> '{fields,medicines,vht_challenges}'::text[] AS vht_challenges,
    d.doc #>> '{fields,medicines,vht_store}'::text[] AS vht_store,
    d.doc #>> '{fields,medicines,dispose}'::text[] AS dispose,
    d.doc #>> '{fields,medicines,actions,action_taken}'::text[] AS medicines_action_taken,
    d.doc #>> '{fields,medicines,actions,solution}'::text[] AS medicines_solution,
    d.doc #>> '{fields,medicines,actions,solution_timeline}'::text[] AS medicines_solution_timeline,
    d.doc #>> '{fields,medicines,actions,responsible_person}'::text[] AS medicines_responsible_person,
    d.doc #>> '{fields,referral,assess_vht}'::text[] AS assess_vht,
    d.doc #>> '{fields,referral,illness}'::text[] AS illness,
    d.doc #>> '{fields,referral,vht_guidelines}'::text[] AS vht_guidelines,
    d.doc #>> '{fields,referral,job_aids}'::text[] AS job_aids,
    d.doc #>> '{fields,referral,danger_signs}'::text[] AS danger_signs,
    d.doc #>> '{fields,referral,children_treated}'::text[] AS children_treated,
    d.doc #>> '{fields,referral,children_followed}'::text[] AS children_followed,
    d.doc #>> '{fields,referral,alerts}'::text[] AS alerts,
    d.doc #>> '{fields,referral,actions,action_taken}'::text[] AS referral_action_taken,
    d.doc #>> '{fields,referral,actions,solution}'::text[] AS referral_solution,
    d.doc #>> '{fields,referral,actions,solution_timeline}'::text[] AS referral_solution_timeline,
    d.doc #>> '{fields,referral,actions,responsible_person}'::text[] AS referral_responsible_person,
    d.doc #>> '{fields,reporting,bundles}'::text[] AS bundles,
    (d.doc #>> '{fields,reporting,bundles_received}'::text[])::integer AS bundles_received,
    d.doc #>> '{fields,reporting,last_sync}'::text[] AS last_sync,
    d.doc #>> '{fields,reporting,facilitation}'::text[] AS facilitation,
    d.doc #>> '{fields,reporting,actions,action_taken}'::text[] AS reporting_action_taken,
    d.doc #>> '{fields,reporting,actions,solution}'::text[] AS reporting_solution,
    d.doc #>> '{fields,reporting,actions,solution_timeline}'::text[] AS reporting_solution_timeline,
    d.doc #>> '{fields,reporting,actions,responsible_person}'::text[] AS reporting_responsible_person,
    d.doc #>> '{fields,behavior,education_messages}'::text[] AS education_messages,
    d.doc #>> '{fields,behavior,number_deliveries}'::text[] AS number_deliveries,
    d.doc #>> '{fields,behavior,number_births}'::text[] AS number_births,
    d.doc #>> '{fields,behavior,dialogues}'::text[] AS dialogues,
    d.doc #>> '{fields,behavior,actions,action_taken}'::text[] AS behavior_action_taken,
    d.doc #>> '{fields,behavior,actions,solution}'::text[] AS behavior_solution,
    d.doc #>> '{fields,behavior,actions,solution_timeline}'::text[] AS behavior_solution_timeline,
    d.doc #>> '{fields,behavior,actions,responsible_person}'::text[] AS behavior_responsible_person,
    d.doc #>> '{fields,challenges,issues}'::text[] AS issues,
    d.doc #>> '{fields,challenges,describe_issues}'::text[] AS describe_issues,
    d.doc #>> '{fields,challenges,other_challenges}'::text[] AS other_challenges,
    d.doc #>> '{fields,challenges,actions,action_taken}'::text[] AS action_taken,
    d.doc #>> '{fields,challenges,actions,solution}'::text[] AS solution,
    d.doc #>> '{fields,challenges,actions,solution_timeline}'::text[] AS solution_timeline,
    d.doc #>> '{fields,challenges,actions,responsible_person}'::text[] AS responsible_person,
    d.doc #>> '{fields,inputs,contact,parent,_id}'::text[] AS vht_area_id,
    h.facility,
    h.dhis2_facility_id,
    h.village,
    h.district,
    h.region,
    CURRENT_TIMESTAMP AS last_refresh_date
   FROM dwh.cht_data d
     LEFT JOIN cht.mv_chw_hierarchy h ON (d.doc #>> '{fields,inputs,contact,parent,_id}'::text[]) = h.vht_area_id
  WHERE (d.doc ->> 'form'::text) = 'support_supervision'::text AND d.is_current
WITH NO DATA;

-- View indexes:
CREATE INDEX support_supervision_reported_idx ON cht.mv_support_supervision USING btree (reported) tablespace ts_indexes;
CREATE INDEX support_supervision_date_idx ON cht.mv_support_supervision USING btree (date) tablespace ts_indexes;
CREATE INDEX support_supervision_monthname_idx ON cht.mv_support_supervision USING btree (monthname) tablespace ts_indexes;
CREATE INDEX mv_support_supervision_year_month_district ON cht.mv_support_supervision USING btree (year, month, district) TABLESPACE ts_indexes;
CREATE INDEX support_supervision_vht_area_id_idx ON cht.mv_support_supervision USING btree (vht_area_id) tablespace ts_indexes;
CREATE INDEX support_supervision_facility_idx ON cht.mv_support_supervision USING btree (facility) tablespace ts_indexes;
CREATE INDEX support_supervision_dhis2_facility_id_idx ON cht.mv_support_supervision USING btree (dhis2_facility_id) tablespace ts_indexes;
CREATE INDEX support_supervision_village_idx ON cht.mv_support_supervision USING btree (village) tablespace ts_indexes;
CREATE INDEX support_supervision_district_idx ON cht.mv_support_supervision USING btree (district) tablespace ts_indexes;
CREATE INDEX support_supervision_region_idx ON cht.mv_support_supervision USING btree (region) tablespace ts_indexes; 