CREATE MATERIALIZED VIEW report.mv_sdx_follow_up
TABLESPACE ts_report
AS
SELECT
     doc ->> '_id'::text                              AS doc_id,
    doc ->> '_rev'::text                             AS rev,                                 -- [NEW FIELD]
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS month,
    doc ->'fields'->'meta'->>'instanceID' AS instanceID,
    doc ->'fields'->'inputs'->'meta'->>'deprecatedID' AS deprecatedID,
    doc ->'fields'->'inputs'->'meta'->'location'->>'lat' AS location_lat,
    doc ->'fields'->'inputs'->'meta'->'location'->>'long' AS location_long,
    doc ->'fields'->'inputs'->'meta'->'location'->>'error' AS location_error,
    doc ->'fields'->'inputs'->'meta'->'location'->>'message' AS location_message,
    doc ->'geolocation'->>'code' AS geolocation_code,
    doc ->'geolocation'->>'message' AS geolocation_message,
    doc ->> 'from'::text                             AS  from,

    doc #>> '{fields,inputs,source}'                                    AS source,
    doc #>> '{fields,inputs,source_id}'                                 AS source_id,
    doc #>> '{fields,inputs,latest_referral_status}'                    AS latest_referral_status,
    doc #>> '{fields,inputs,vht_id}'                                    AS vht_id,
    doc #>> '{fields,inputs,contact,_id}'                               AS contact_id,
    doc #>> '{fields,inputs,contact,name}'                              AS contact_name,
    doc #>> '{fields,inputs,contact,date_of_birth}'                     AS contact_date_of_birth,
    doc #>> '{fields,inputs,contact,sex}'                               AS contact_sex,
    doc #>> '{fields,inputs,contact,parent,_id}'                        AS parent_id,
    doc #>> '{fields,inputs,contact,parent,name}'                       AS parent_name,
 
    doc #>> '{fields,vht_area_id}'                   AS vht_area_id,
    doc #>> '{fields,facility_id}'                  AS facility_id,
    doc #>> '{fields,patient_age_in_years}'         AS patient_age_in_years,
    doc #>> '{fields,patient_age_in_months}'        AS patient_age_in_months,
    doc #>> '{fields,patient_age_in_days}'          AS patient_age_in_days,
    doc #>> '{fields,patient_age_display}'          AS patient_age_display,
    doc #>> '{fields,patient_id}'                   AS patient_id,
    doc #>> '{fields,_child_id}'                    AS _child_id,
    doc #>> '{fields,patient_name}'                 AS patient_name,
    doc #>> '{fields,patient_gender}'               AS patient_gender,
    doc #>> '{fields,referral_follow_up}'           AS referral_follow_up,
    doc #>> '{fields,trigger_referral_follow_up}'   AS trigger_referral_follow_up,
    doc #>> '{fields,group_danger_signs,did_visit}'                 AS did_visit,
    doc #>> '{fields,group_danger_signs,no_visit_reason}'          AS no_visit_reason,
    doc #>> '{fields,group_danger_signs,no_visit_reason_other}'    AS no_visit_reason_other,
    doc #>> '{fields,group_danger_signs,follow_up_date}'           AS follow_up_date,
    doc #>> '{fields,group_danger_signs,follow_up_method}'         AS follow_up_method,
    doc #>> '{fields,group_danger_signs,note_look_for_danger_signs}' AS note_look_for_danger_signs,
    doc #>> '{fields,group_danger_signs,any_danger_signs}'         AS any_danger_signs,
    doc #>> '{fields,group_danger_signs,note_refer_urgently}'      AS note_refer_urgently,
    doc #>> '{fields,group_danger_signs,child_referred}'           AS child_referred,
    doc #>> '{fields,group_follow_up,how_is_child}'                AS how_is_child,
    doc #>> '{fields,group_follow_up,note_if_better}'             AS note_if_better,
    doc #>> '{fields,group_follow_up,child_referred}'             AS child_referred,
    doc #>> '{fields,group_follow_up,note_refer_to_health_facility}' AS note_refer_to_health_facility,
    doc #>> '{fields,group_follow_up,note_cured}'                 AS note_cured,
    doc #>> '{fields,group_key_health_messages,note_feeding_advice}'       AS note_feeding_advice,
    doc #>> '{fields,group_key_health_messages,note_give_more_liquids}'    AS note_give_more_liquids,
    doc #>> '{fields,group_key_health_messages,note_give_soft_foods}'      AS note_give_soft_foods,
    doc #>> '{fields,group_key_health_messages,note_encourage_child2eat}'  AS note_encourage_child2eat,
    doc #>> '{fields,group_key_health_messages,note_varied_foods}'         AS note_varied_foods,
    doc #>> '{fields,group_discharge_messages,note_discharge_advice}'        AS note_discharge_advice,
    doc #>> '{fields,group_discharge_messages,note_check_treatment_complete}' AS note_check_treatment_complete,
    doc #>> '{fields,group_discharge_messages,note_remember_follow_ups}'      AS note_remember_follow_ups,
    doc #>> '{fields,group_discharge_messages,note_return_if_danger_signs}'   AS note_return_if_danger_signs,
    doc #>> '{fields,group_watch_danger_signs,note_danger_signs_advice}'       AS note_danger_signs_advice,
    doc #>> '{fields,group_watch_danger_signs,note_convulsions}'               AS note_convulsions,
    doc #>> '{fields,group_watch_danger_signs,note_vomits_everything}'         AS note_vomits_everything,
    doc #>> '{fields,group_watch_danger_signs,note_fast_breathing}'            AS note_fast_breathing,
    doc #>> '{fields,group_watch_danger_signs,note_very_sleepy}'               AS note_very_sleepy,
    doc #>> '{fields,group_watch_danger_signs,note_yellow_eyes_palms}'        AS note_yellow_eyes_palms,
    doc #>> '{fields,group_watch_danger_signs,note_chest_indrawing}'           AS note_chest_indrawing,
    doc #>> '{fields,group_watch_danger_signs,note_unable_to_drink_breastfeed}' AS note_unable_to_drink_breastfeed,
    doc #>> '{fields,group_watch_danger_signs,note_cough}'                     AS note_cough,
    doc #>> '{fields,group_watch_danger_signs,note_infected_umbilical_chord}'  AS note_infected_umbilical_chord,
    doc #>> '{fields,group_watch_danger_signs,note_low_temperature}'           AS note_low_temperature,
    doc #>> '{fields,group_watch_danger_signs,note_fever_more_than7days}'      AS note_fever_more_than7days,
    doc #>> '{fields,group_watch_danger_signs,note_muac_red_yellow}'           AS note_muac_red_yellow,

    doc #>> '{fields,group_patient_summary,s_note_before_submit}'          AS s_note_before_submit,
    doc #>> '{fields,group_patient_summary,s_note_patient_details}'        AS s_note_patient_details,
    doc #>> '{fields,group_patient_summary,s_note_patient_details_values}' AS s_note_patient_details_values,
    doc #>> '{fields,group_patient_summary,s_condition_of_child}'           AS s_condition_of_child,
    doc #>> '{fields,group_patient_summary,s_note_has_danger_signs}'       AS s_note_has_danger_signs,
    doc #>> '{fields,group_patient_summary,s_note_danger_sign0}'           AS s_note_danger_sign0,
    doc #>> '{fields,group_patient_summary,s_note_danger_sign1}'           AS s_note_danger_sign1,
    doc #>> '{fields,group_patient_summary,s_note_danger_sign2}'           AS s_note_danger_sign2,
    doc #>> '{fields,group_patient_summary,s_note_danger_sign3}'           AS s_note_danger_sign3,
    doc #>> '{fields,group_patient_summary,s_note_danger_sign4}'           AS s_note_danger_sign4,
    doc #>> '{fields,group_patient_summary,s_note_danger_sign5}'           AS s_note_danger_sign5,
    doc #>> '{fields,group_patient_summary,s_note_danger_sign6}'           AS s_note_danger_sign6,
    doc #>> '{fields,group_patient_summary,s_note_danger_sign7}'           AS s_note_danger_sign7,
    doc #>> '{fields,group_patient_summary,s_note_danger_sign8}'           AS s_note_danger_sign8,
    doc #>> '{fields,group_patient_summary,s_note_danger_sign9}'           AS s_note_danger_sign9,
    doc #>> '{fields,group_patient_summary,s_note_danger_sign10}'          AS s_note_danger_sign10,
    doc #>> '{fields,group_patient_summary,s_note_danger_sign11}'          AS s_note_danger_sign11,
    doc #>> '{fields,group_patient_summary,s_note_how_is_child0}'          AS s_note_how_is_child0,
    doc #>> '{fields,group_patient_summary,s_note_how_is_child1}'          AS s_note_how_is_child1,
    doc #>> '{fields,group_patient_summary,s_note_how_is_child2}'          AS s_note_how_is_child2,
    doc #>> '{fields,group_patient_summary,s_note_referral}'               AS s_note_referral,
    doc #>> '{fields,group_patient_summary,s_note_followup}'               AS s_note_followup,
    doc #>> '{fields,group_patient_summary,s_note_followup_task}'          AS s_note_followup_task,

     doc #>> '{fields,additional_doc,patient_id}'                        AS additional_doc_patient_id,
     doc #>> '{fields,additional_doc,type}'                              AS type,
     doc #>> '{fields,additional_doc,created_by_doc}'                    AS created_by_doc,
     doc #>> '{fields,additional_doc,content_type}'                      AS content_type,
     doc #>> '{fields,additional_doc,form}'                              AS form_field,
     doc #>> '{fields,additional_doc,contact,_id}'                       AS contact__id,
     doc #>> '{fields,additional_doc,contact,parent,_id}'                AS contact_parent__id,
     doc #>> '{fields,additional_doc,fields,inputs,contact,_id}'         AS inputs_contact__id,
     doc #>> '{fields,additional_doc,fields,inputs,child_id}'            AS child_id,
     doc #>> '{fields,additional_doc,fields,inputs,child_name}'          AS child_name,


        --- reporting hierarchy
    doc #>> '{contact,_id}'                         AS chw_id,                   
    doc #>> '{contact,parent,_id}'                  AS chw_area_id,  
    doc #>> '{contact,parent,parent,_id}'           AS facility_id,                                    
    doc #>> '{contact,parent,parent,parent,_id}'    AS parish_id,              
    doc #>> '{contact,parent,parent,parent,parent,_id}'           AS district,                 
    doc #>> '{contact,parent,parent,parent,parent,parent,_id}'    AS region    

FROM dwh.cht_data AS couchdb
WHERE (doc ->> 'form') = 'sdx_follow_up'
  AND is_current
WITH DATA;

CREATE UNIQUE INDEX sdx_follow_up_uuid_idx
    ON report.mv_sdx_follow_up USING btree (uuid);

CREATE INDEX sdx_follow_up_reported_idx
    ON report.mv_sdx_follow_up USING btree (reported);
