-- cht.mv_screening source
DROP MATERIALIZED VIEW cht.mv_screening;
CREATE MATERIALIZED VIEW cht.mv_screening
TABLESPACE ts_report
AS SELECT doc ->> '_id'::text AS uuid,
    doc ->> 'form'::text AS form,
    doc ->> 'from'::text AS submitter,
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    to_char(to_timestamp((((doc ->>'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS monthname,
    ((doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    (NULLIF((doc -> 'geolocation'::text) ->> 'latitude'::text, ''::text))::double precision AS geolocation_latitude,
    (NULLIF((doc -> 'geolocation'::text) ->> 'longitude'::text, ''::text))::double precision AS geolocation_longitude,
    (NULLIF((doc -> 'geolocation'::text) ->> 'accuracy'::text, ''::text))::double precision AS geolocation_accuracy,
    (NULLIF((doc -> 'geolocation'::text) ->> 'altitude'::text, ''::text))::double precision AS geolocation_altitude,
    (NULLIF((doc -> 'geolocation'::text) ->> 'altitudeAccuracy'::text, ''::text))::double precision AS geolocation_altitude_accuracy,
    (NULLIF((doc -> 'geolocation'::text) ->> 'speed'::text, ''::text))::double precision AS geolocation_speed,
    (NULLIF((doc -> 'geolocation'::text) ->> 'heading'::text, ''::text))::double precision AS geolocation_heading,
    doc #>> '{fields,inputs,source}'::text[] AS inputs_source,
    doc #>> '{fields,inputs,source_id}'::text[] AS inputs_source_id,
    doc #>> '{fields,inputs,contact,_id}'::text[] AS inputs_contact_id,
    doc #>> '{fields,inputs,contact,name}'::text[] AS inputs_contact_name,
    doc #>> '{fields,inputs,contact,date_of_birth}'::text[] AS inputs_contact_date_of_birth,
    doc #>> '{fields,inputs,contact,sex}'::text[] AS inputs_contact_sex,
    doc #>> '{fields,inputs,contact,parent,_id}'::text[] AS inputs_contact_parent_id,
    doc #>> '{fields,visited_contact_uuid}'::text[] AS visited_contact_uuid,
    doc #>> '{fields,patient_age_in_years}'::text[] AS patient_age_in_years,
    doc #>> '{fields,patient_age_in_months}'::text[] AS patient_age_in_months,
    doc #>> '{fields,patient_age_in_days}'::text[] AS patient_age_in_days,
    doc #>> '{fields,patient_age_display}'::text[] AS patient_age_display,
    doc #>> '{fields,patient_id}'::text[] AS patient_id,
    doc #>> '{fields,patient_name}'::text[] AS patient_name,
    doc #>> '{fields,patient_gender}'::text[] AS patient_gender,
    doc #>> '{fields,patient_name_with_s}'::text[] AS patient_name_with_s,
    doc #>> '{fields,today_date}'::text[] AS today_date,
    doc #>> '{fields,is_of_child_bearing_age}'::text[] AS is_of_child_bearing_age,
    doc #>> '{fields,fp_registration_method}'::text[] AS fp_registration_method,
    doc #>> '{fields,group_pregnancy_screening,is_pregnant}'::text[] AS p_is_pregnant,
    doc #>> '{fields,group_pregnancy_screening,has_started_anc}'::text[] AS p_has_started_anc,
    doc #>> '{fields,group_pregnancy_screening,note_refer_to_health_facility_anc}'::text[] AS p_note_refer_to_health_facility_anc,
    doc #>> '{fields,group_pregnancy_screening,referred_to_health_facility_anc}'::text[] AS p_referred_to_health_facility_anc,
    doc #>> '{fields,group_pregnancy_screening,note_register_pregnancy}'::text[] AS p_note_register_pregnancy,
    doc #>> '{fields,group_family_planning_screening,note_fp_registration}'::text[] AS note_fp_registration,
    doc #>> '{fields,group_family_planning_screening,on_fp_method}'::text[] AS on_fp_method,
    doc #>> '{fields,group_family_planning_screening,fp_method}'::text[] AS fp_method,
    doc #>> '{fields,group_family_planning_screening,fp_method_label}'::text[] AS fp_method_label,
    doc #>> '{fields,group_family_planning_screening,experiencing_fp_side_effects}'::text[] AS experiencing_fp_side_effects,
    doc #>> '{fields,group_family_planning_screening,note_refer_counsel_and_refer}'::text[] AS note_refer_counsel_and_refer,
    doc #>> '{fields,group_family_planning_screening,change_fp_method}'::text[] AS change_fp_method,
    doc #>> '{fields,group_family_planning_screening,note_counsel_on_all_fp_methods}'::text[] AS note_counsel_on_all_fp_methods,
    doc #>> '{fields,group_family_planning_screening,counseled_on_fp_methods}'::text[] AS counseled_on_fp_methods,
    doc #>> '{fields,group_family_planning_screening,referred_for_fp_services}'::text[] AS referred_for_fp_services,
    doc #>> '{fields,group_family_planning_screening,follow_up_date_fp_services}'::text[] AS follow_up_date_fp_services,
    doc #>> '{fields,group_family_planning_screening,note_register_using_fp_registration_form}'::text[] AS note_register_using_fp_registration_form,
    doc #>> '{fields,group_family_planning_screening,knows_lmp}'::text[] AS knows_lmp,
    doc #>> '{fields,group_family_planning_screening,lmp_start_date}'::text[] AS lmp_start_date,
    doc #>> '{fields,group_family_planning_screening,days_elapsed_since_lmp}'::text[] AS days_elapsed_since_lmp,
    doc #>> '{fields,group_family_planning_screening,lmp_approximate_date}'::text[] AS lmp_approximate_date,
    doc #>> '{fields,group_family_planning_screening,note_refer_for_pregnancy_test}'::text[] AS note_refer_for_pregnancy_test,
    doc #>> '{fields,group_family_planning_screening,note_educate_on_available_fp_services}'::text[] AS note_educate_on_available_fp_services,
    doc #>> '{fields,group_family_planning_screening,referred_for_pregnancy_test}'::text[] AS referred_for_pregnancy_test,
    doc #>> '{fields,group_family_planning_screening,follow_up_date_pregnancy_test}'::text[] AS follow_up_date_pregnancy_test,
    doc #>> '{fields,group_hiv_screening,test_for_hiv_last3months}'::text[] AS hiv_test_for_hiv_last3months,
    doc #>> '{fields,group_hiv_screening,hiv_test_result}'::text[] AS hiv_hiv_test_result,
    doc #>> '{fields,group_hiv_screening,tested_hiv}'::text[] AS hiv_tested_hiv,
    doc #>> '{fields,group_hiv_screening,not_tested_hiv}'::text[] AS hiv_not_tested_hiv,
    doc #>> '{fields,group_hiv_screening,on_art_treatment}'::text[] AS hiv_on_art_treatment,
    doc #>> '{fields,group_hiv_screening,note_attend_art_clinic}'::text[] AS hiv_note_attend_art_clinic,
    doc #>> '{fields,group_hiv_screening,taking_medication}'::text[] AS hiv_taking_medication,
    doc #>> '{fields,group_hiv_screening,note_explain_importance_taking_med}'::text[] AS hiv_note_explain_importance_taking_med,
    doc #>> '{fields,group_hiv_screening,note_encourage_to_continue_taking_med}'::text[] AS hiv_note_encourage_to_continue_taking_med,
    doc #>> '{fields,group_hiv_screening,note_encourage_client}'::text[] AS hiv_note_encourage_client,
    doc #>> '{fields,group_hiv_screening,note_advise_client_check_status}'::text[] AS hiv_note_advise_client_check_status,
    doc #>> '{fields,group_hiv_screening,note_advise_client_check_status2}'::text[] AS hiv_note_advise_client_check_status2,
    doc #>> '{fields,group_tb_screening,has_tb}'::text[] AS has_tb,
    doc #>> '{fields,group_tb_screening,on_tb_treatment}'::text[] AS on_tb_treatment,
    doc #>> '{fields,group_tb_screening,note_refer_not_on_tb_treatment}'::text[] AS note_refer_not_on_tb_treatment,
    doc #>> '{fields,group_other_screening,hpv_card}'::text[] AS other_hpv_card,
    doc #>> '{fields,group_other_screening,received_hpv}'::text[] AS other_received_hpv,
    doc #>> '{fields,group_other_screening,check_hpv_note}'::text[] AS other_check_hpv_note,
    doc #>> '{fields,group_other_screening,educate_hpv_note}'::text[] AS other_educate_hpv_note,
    doc #>> '{fields,group_other_screening,afp_vpd}'::text[] AS other_afp_vpd,
    doc #>> '{fields,group_other_screening,refer_afp}'::text[] AS other_refer_afp,
    doc #>> '{fields,group_other_screening,received_tt_vaccine}'::text[] AS other_received_tt_vaccine,
    doc #>> '{fields,group_other_screening,has_hypertension}'::text[] AS other_has_hypertension,
    doc #>> '{fields,group_other_screening,has_sickle_cell}'::text[] AS other_has_sickle_cell,
    doc #>> '{fields,group_other_screening,uses_tobacco}'::text[] AS other_uses_tobacco,
    doc #>> '{fields,group_other_screening,sleep_under_llin}'::text[] AS other_sleep_under_llin,
    doc #>> '{fields,group_other_screening,why_not_using_llin}'::text[] AS other_why_not_using_llin,
    doc #>> '{fields,group_other_screening,why_not_using_llin_other}'::text[] AS other_why_not_using_llin_other,
    doc #>> '{fields,group_other_screening,note_vht_assist_how_to_get_llin}'::text[] AS other_note_vht_assist_how_to_get_llin,
    doc #>> '{fields,group_other_screening,note_vht_demonstrate_on_llin_use}'::text[] AS other_note_vht_demonstrate_on_llin_use,
    doc #>> '{contact,_id}'                         AS chw_id,
      h.facility,
      h.dhis2_facility_id,
      h.village,
      h.parish,
      h.district,
      h.region,
      CURRENT_TIMESTAMP                                 AS last_refresh_date  
FROM dwh.cht_data d
LEFT JOIN cht.mv_chw_hierarchy h ON (d.doc #>> '{contact,_id}') = h.chw_id
  WHERE (doc ->> 'form'::text) = 'screening'::text AND is_current
WITH NO DATA;

-- View indexes:
CREATE INDEX mv_screening_chw_id ON cht.mv_screening USING btree (chw_id) tablespace ts_indexes;
CREATE INDEX mv_screening_reported ON cht.mv_screening USING btree (reported) tablespace ts_indexes;
CREATE INDEX mv_screening_date ON cht.mv_screening USING btree (date) tablespace ts_indexes;
CREATE INDEX mv_screening_year_month_district ON cht.mv_screening USING btree (year, month, district) TABLESPACE ts_indexes;
CREATE INDEX mv_screening_monthname ON cht.mv_screening USING btree (monthname) tablespace ts_indexes;
CREATE INDEX mv_screening_district ON cht.mv_screening USING btree (district) tablespace ts_indexes;
CREATE INDEX mv_screening_region ON cht.mv_screening USING btree (region) tablespace ts_indexes;
CREATE INDEX mv_screening_facility ON cht.mv_screening USING btree (facility) tablespace ts_indexes;
CREATE INDEX mv_screening_dhis2_facility_id ON cht.mv_screening USING btree (dhis2_facility_id) tablespace ts_indexes;
