REATE MATERIALIZED VIEW cht.mv_tb_screening
TABLESPACE ts_report
AS
SELECT
    doc ->> '_id'::text                              AS doc_id,
    doc ->> '_rev'::text                             AS rev,                                 -- [NEW FIELD]
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS month,
    doc ->'fields'->'meta'->>'instanceID' AS instanceID,
    doc ->'fields'->'inputs'->'meta'->>'deprecatedID' AS deprecatedID,
    doc ->'fields'->'inputs'->'meta'->'location'->>'lat' AS location_lat,
    doc ->'fields'->'inputs'->'meta'->'location'->>'long' AS location_long,
    doc ->'fields'->'inputs'->'meta'->'location'->>'error' AS location_error,
    doc ->'fields'->'inputs'->'meta'->'location'->>'message' AS location_message,
    doc ->'geolocation'->>'code' AS geolocation_code,
    doc ->'geolocation'->>'message' AS geolocation_message,
    doc ->> 'from'::text                             AS  from,
    doc #>> '{fields,inputs,source}'                                    AS source,
    doc #>> '{fields,inputs,source_id}'                                 AS source_id,
     doc #>> '{fields,inputs,user,contact_id}'                           AS user_contact_id,
     doc #>> '{fields,inputs,user,facility_id}'                          AS user_facility_id,
     doc #>> '{fields,inputs,contact,_id}'                               AS contact_id,
     doc #>> '{fields,inputs,contact,name}'                              AS contact_name,
     doc #>> '{fields,inputs,contact,date_of_birth}'                     AS contact_date_of_birth,
     doc #>> '{fields,inputs,contact,sex}'                               AS contact_sex,
     doc #>> '{fields,inputs,contact,phone}'                             AS phone,
     doc #>> '{fields,inputs,contact,parent,_id}'                        AS parent_id,
     doc #>> '{fields,inputs,contact,parent,name}'                       AS parent_name,
     doc #>> '{fields,inputs,contact,parent,parent,supervisor}'          AS supervisor,
     doc #>> '{fields,inputs,contact,parent,parent,phone}'               AS parent_phone,
     doc #>> '{fields,inputs,contact,parent,parent,village}'             AS village,

    doc #>> '{fields,patient_age_in_years}'             AS patient_age_in_years,
    doc #>> '{fields,patient_age_in_months}'            AS patient_age_in_months,
    doc #>> '{fields,patient_age_in_days}'              AS patient_age_in_days,
    doc #>> '{fields,patient_age_display}'              AS patient_age_display,
    doc #>> '{fields,patient_id}'                        AS patient_id,
    doc #>> '{fields,patient_name}'                      AS patient_name,
    doc #>> '{fields,patient_gender}'                    AS patient_gender,
    doc #>> '{fields,patient_pronoun}'                   AS patient_pronoun,
    doc #>> '{fields,patient_adjective}'                 AS patient_adjective,
    doc #>> '{fields,patient_gender_pronoun}'           AS patient_gender_pronoun,
    doc #>> '{fields,patient_phone}'                     AS patient_phone,
    doc #>> '{fields,still_on_tb_treatment}'             AS still_on_tb_treatment,
    doc #>> '{fields,has_diabetes_on_screening}'         AS has_diabetes_on_screening,
    doc #>> '{fields,is_a_miner_on_screening}'           AS is_a_miner_on_screening,
    doc #>> '{fields,is_hiv_positive}'                   AS is_hiv_positive,
    doc #>> '{fields,patient_category}'                  AS patient_category,
    doc #>> '{fields,barcode_scanner_result}'            AS barcode_scanner_result,
    doc #>> '{fields,is_presumptive_case}'               AS is_presumptive_case,
    doc #>> '{fields,national_identification_number}'    AS national_identification_number,
    doc #>> '{fields,client_category}'                   AS client_category,
    doc #>> '{fields,is_on_tb_treatment}'                AS is_on_tb_treatment,
    doc #>> '{fields,cough}'                              AS cough,
    doc #>> '{fields,fever}'                              AS fever,
    doc #>> '{fields,excessive_night_sweat}'             AS excessive_night_sweat,
    doc #>> '{fields,weight_loss}'                        AS weight_loss,
    doc #>> '{fields,poor_weight_gain}'                   AS poor_weight_gain,
    doc #>> '{fields,group_tb_screening,is_currently_on_tb_treatment}'        AS is_currently_on_tb_treatment,
    doc #>> '{fields,group_tb_screening,is_still_on_tb_treatment}'           AS is_still_on_tb_treatment,
    doc #>> '{fields,group_tb_screening,have_all_members_been_screened}'     AS have_all_members_been_screened,
    doc #>> '{fields,group_tb_screening,refer_household_members}'            AS refer_household_members,

    doc #>> '{fields,group_tb_health_education,health_education}'            AS health_education,
    doc #>> '{fields,group_tb_health_education,benefits_of_tb_treatment}'    AS benefits_of_tb_treatment,
    doc #>> '{fields,group_tb_health_education,drug_resistance}'              AS drug_resistance,
    doc #>> '{fields,group_tb_health_education,explain_drug_resistance}'      AS explain_drug_resistance,
    doc #>> '{fields,group_tb_health_education,health_education_basics}'      AS health_education_basics,
    doc #>> '{fields,group_tb_health_education,what_is_tb}'                   AS what_is_tb,
    doc #>> '{fields,group_tb_health_education,tb_explanation}'               AS tb_explanation,
    doc #>> '{fields,group_tb_health_education,tb_explanation_type}'          AS tb_explanation_type,
    doc #>> '{fields,group_tb_health_education,who_risk_contracting_tb}'      AS who_risk_contracting_tb,

    doc #>> '{fields,group_tb_signs_and_symptoms_of_tb,cough_2_weeks_or_more}'           AS cough_2_weeks_or_more,
    doc #>> '{fields,group_tb_signs_and_symptoms_of_tb,excessive_night_sweats}'         AS excessive_night_sweats,
    doc #>> '{fields,group_tb_signs_and_symptoms_of_tb,unexplained_weight_loss}'        AS unexplained_weight_loss,
    doc #>> '{fields,group_tb_signs_and_symptoms_of_tb,loss_of_appetite_image}'         AS loss_of_appetite_image,
    doc #>> '{fields,group_tb_signs_and_symptoms_of_tb,chest_pain_image}'               AS chest_pain_image,
    doc #>> '{fields,group_tb_signs_and_symptoms_of_tb,poor_weight_gain_among_children}' AS poor_weight_gain_among_children,
    
    doc #>> '{fields,group_tb_health_and_status_check,select_tb_risk_factors}'       AS select_tb_risk_factors,
    doc #>> '{fields,group_tb_signs_and_symptoms,currently_have_tb_signs}'     AS currently_have_tb_signs,
    doc #>> '{fields,group_tb_signs_and_symptoms,cough_sign}'                  AS cough_sign,
    doc #>> '{fields,group_tb_signs_and_symptoms,cough_duration}'              AS cough_duration,
    doc #>> '{fields,group_tb_signs_and_symptoms,blood_in_cough}'              AS blood_in_cough,
    doc #>> '{fields,group_tb_signs_and_symptoms,fever_symptom}'               AS fever_symptom,
    doc #>> '{fields,group_tb_signs_and_symptoms,fever_duration}'              AS fever_duration,
    doc #>> '{fields,group_tb_signs_and_symptoms,weight_loss_sign}'            AS weight_loss_sign,
    doc #>> '{fields,group_tb_signs_and_symptoms,excessive_night_sweat_sign}'  AS excessive_night_sweat_sign,
    doc #>> '{fields,group_tb_signs_and_symptoms,loss_of_appetite}'            AS loss_of_appetite,
    doc #>> '{fields,group_tb_signs_and_symptoms,chest_pain}'                  AS chest_pain,
    doc #>> '{fields,group_tb_signs_and_symptoms,poor_weight_gain_sign}'       AS poor_weight_gain_sign,
    doc #>> '{fields,group_tb_signs_and_symptoms,had_contact_with_tb_person}'  AS had_contact_with_tb_person,
    doc #>> '{fields,group_tb_signs_and_symptoms,suspected_tb_signs}'          AS suspected_tb_signs,
   
    doc #>> '{fields,group_tb_prevention_measures,note_educate_patient}'    AS note_educate_patient,
    doc #>> '{fields,group_tb_prevention_measures,refer_to_health_facility}'    AS refer_to_health_facility,
    doc #>> '{fields,group_tb_prevention_measures,confirms_referral}'    AS confirms_referral,
    doc #>> '{fields,sputum_collection_consent,consented_sputum_sample}'        AS consented_sputum_sample,
    doc #>> '{fields,sputum_collection_consent,registered_phone_number}'        AS registered_phone_number,
    doc #>> '{fields,sputum_collection_consent,receive_results_on_same_phonenumber}' AS receive_results_on_same_phonenumber,
    doc #>> '{fields,sputum_collection_consent,enter_new_phone_number}'         AS enter_new_phone_number,
    doc #>> '{fields,sputum_collection_consent,no_registered_phone_number}'     AS no_registered_phone_number,
    doc #>> '{fields,sputum_collection_consent,phonenumber_to_receive_results}' AS phonenumber_to_receive_results,
    doc #>> '{fields,sputum_collection_consent,results_phone_number}'           AS results_phone_number,

    doc #>> '{fields,sputum_collection,sputum_collection}'            AS sputum_collection,
    doc #>> '{fields,sputum_collection,has_patient_produced_sputum}'  AS has_patient_produced_sputum,
    doc #>> '{fields,sputum_collection,confirm_container_tightly_closed}' AS confirm_container_tightly_closed,
    doc #>> '{fields,sputum_collection,confirm_send_sample_for_testing}'  AS confirm_send_sample_for_testing,
    doc #>> '{fields,sputum_collection,leave_sputum_bottle_with_client}'  AS leave_sputum_bottle_with_client,
    doc #>> '{fields,sputum_collection,keep_container_closed}'        AS keep_container_closed,
    doc #>> '{fields,sputum_collection,has_left_sputum_bottle_with_client}' AS has_left_sputum_bottle_with_client,

    doc #>> '{fields,group_summary,s_note_danger_sign}'             AS s_note_danger_sign,
    doc #>> '{fields,group_summary,s_summary_submit}'               AS s_summary_submit,
    doc #>> '{fields,group_summary,s_note_person_details}'          AS s_note_person_details,
    doc #>> '{fields,group_summary,s_note_person_details_values}'   AS s_note_person_details_values,
    doc #>> '{fields,group_summary,s_note_findings}'                AS s_note_findings,
    doc #>> '{fields,group_summary,s_note_currently_on_treatment}'  AS s_note_currently_on_treatment,
    doc #>> '{fields,group_summary,s_note_suspected_symptoms}'      AS s_note_suspected_symptoms,
    doc #>> '{fields,group_summary,s_note_cough}'                   AS s_note_cough,
    doc #>> '{fields,group_summary,s_note_fever}'                   AS s_note_fever,
    doc #>> '{fields,group_summary,s_note_weight_loss}'             AS s_note_weight_loss,
    doc #>> '{fields,group_summary,s_note_excessive_night_sweats}'  AS s_note_excessive_night_sweats,
    doc #>> '{fields,group_summary,s_note_loss_of_appetite}'        AS s_note_loss_of_appetite,
    doc #>> '{fields,group_summary,s_note_chest_pain}'              AS s_note_chest_pain,
    doc #>> '{fields,group_summary,s_note_poor_weight_gain}'        AS s_note_poor_weight_gain,
    doc #>> '{fields,group_summary,s_note_no_symptom}'              AS s_note_no_symptom,
    doc #>> '{fields,group_summary,s_note_sputum_collection}'       AS s_note_sputum_collection,
    doc #>> '{fields,group_summary,s_note_declined_to_give_sputum}' AS s_note_declined_to_give_sputum,
    doc #>> '{fields,group_summary,s_note_sputum_collected}'        AS s_note_sputum_collected,
    doc #>> '{fields,group_summary,s_note_sputum_not_available}'    AS s_note_sputum_not_available,
    doc #>> '{fields,group_summary,s_note_instructions}'            AS s_note_instructions,
    doc #>> '{fields,group_summary,s_note_please_sync}'             AS s_note_please_sync,
    doc #>> '{fields,group_summary,s_note_sync_ha_notification}'    AS s_note_sync_ha_notification,

    --- reporting hierarchy
    doc #>> '{contact,_id}'                         AS chw_id,                   
    doc #>> '{contact,parent,_id}'                  AS chw_area_id,  
    doc #>> '{contact,parent,parent,_id}'           AS facility_id,                                    
    doc #>> '{contact,parent,parent,parent,_id}'    AS parish_id,              
    doc #>> '{contact,parent,parent,parent,parent,_id}'           AS district,                 
    doc #>> '{contact,parent,parent,parent,parent,parent,_id}'    AS region,
    CURRENT_TIMESTAMP                                 AS last_refresh_date  

FROM dwh.cht_data
WHERE (doc ->> 'form') = 'tb_screening'
  AND is_current
WITH DATA;

CREATE INDEX tb_screening_reported_idx
    ON cht.mv_tb_screening USING btree (reported);
