-- cht.mv_tb_screening source
DROP MATERIALIZED VIEW cht.mv_tb_screening;
CREATE MATERIALIZED VIEW cht.mv_tb_screening
TABLESPACE ts_report
AS SELECT doc ->> '_id'::text AS doc_id,
    doc ->> '_rev'::text AS rev,
    to_timestamp((NULLIF(doc ->> 'reported_date'::text, ''::text)::bigint / 1000)::double precision) AS reported,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY-MM-DD'))::date AS date,
    (TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'YYYY'))::INT AS year,
    to_char(to_timestamp((((doc ->>'reported_date'::text)::bigint) / 1000)::double precision), 'MM'::text)::integer AS month,
    TO_CHAR(TO_TIMESTAMP((doc->>'reported_date')::BIGINT / 1000), 'FMMonth') AS monthname,
    ((doc -> 'fields'::text) -> 'meta'::text) ->> 'instanceID'::text AS instanceid,
    (((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) ->> 'deprecatedID'::text AS deprecatedid,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'lat'::text AS location_lat,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'long'::text AS location_long,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'error'::text AS location_error,
    ((((doc -> 'fields'::text) -> 'inputs'::text) -> 'meta'::text) -> 'location'::text) ->> 'message'::text AS location_message,
    (doc -> 'geolocation'::text) ->> 'code'::text AS geolocation_code,
    (doc -> 'geolocation'::text) ->> 'message'::text AS geolocation_message,
    doc ->> 'from'::text AS "from",
    doc #>> '{fields,inputs,source}'::text[] AS source,
    doc #>> '{fields,inputs,source_id}'::text[] AS source_id,
    doc #>> '{fields,inputs,user,contact_id}'::text[] AS user_contact_id,
    doc #>> '{fields,inputs,user,facility_id}'::text[] AS user_facility_id,
    doc #>> '{fields,inputs,contact,_id}'::text[] AS inputs_contact_id,
    doc #>> '{fields,inputs,contact,name}'::text[] AS inputs_contact_name,
    doc #>> '{fields,inputs,contact,date_of_birth}'::text[] AS inputs_contact_date_of_birth,
    doc #>> '{fields,inputs,contact,sex}'::text[] AS inputs_contact_sex,
    doc #>> '{fields,inputs,contact,phone}'::text[] AS inputs_contact_phone,
    doc #>> '{fields,inputs,contact,parent,_id}'::text[] AS inputs_parent_id,
    doc #>> '{fields,inputs,contact,parent,name}'::text[] AS inputs_parent_name,
    doc #>> '{fields,inputs,contact,parent,parent,supervisor}'::text[] AS inputs_supervisor,
    doc #>> '{fields,inputs,contact,parent,parent,phone}'::text[] AS inputs_parent_phone,
    doc #>> '{fields,inputs,contact,parent,parent,village}'::text[] AS inputs_village,
    doc #>> '{fields,patient_age_in_years}'::text[] AS patient_age_in_years,
    doc #>> '{fields,patient_age_in_months}'::text[] AS patient_age_in_months,
    doc #>> '{fields,patient_age_in_days}'::text[] AS patient_age_in_days,
    doc #>> '{fields,patient_age_display}'::text[] AS patient_age_display,
    doc #>> '{fields,patient_id}'::text[] AS patient_id,
    doc #>> '{fields,patient_name}'::text[] AS patient_name,
    doc #>> '{fields,patient_gender}'::text[] AS patient_gender,
    doc #>> '{fields,patient_pronoun}'::text[] AS patient_pronoun,
    doc #>> '{fields,patient_adjective}'::text[] AS patient_adjective,
    doc #>> '{fields,patient_gender_pronoun}'::text[] AS patient_gender_pronoun,
    doc #>> '{fields,patient_phone}'::text[] AS patient_phone,
    doc #>> '{fields,still_on_tb_treatment}'::text[] AS still_on_tb_treatment,
    doc #>> '{fields,has_diabetes_on_screening}'::text[] AS has_diabetes_on_screening,
    doc #>> '{fields,is_a_miner_on_screening}'::text[] AS is_a_miner_on_screening,
    doc #>> '{fields,is_hiv_positive}'::text[] AS is_hiv_positive,
    doc #>> '{fields,patient_category}'::text[] AS patient_category,
    doc #>> '{fields,barcode_scanner_result}'::text[] AS barcode_scanner_result,
    doc #>> '{fields,is_presumptive_case}'::text[] AS is_presumptive_case,
    doc #>> '{fields,national_identification_number}'::text[] AS national_identification_number,
    doc #>> '{fields,client_category}'::text[] AS client_category,
    doc #>> '{fields,is_on_tb_treatment}'::text[] AS is_on_tb_treatment,
    doc #>> '{fields,cough}'::text[] AS cough,
    doc #>> '{fields,fever}'::text[] AS fever,
    doc #>> '{fields,excessive_night_sweat}'::text[] AS excessive_night_sweat,
    doc #>> '{fields,weight_loss}'::text[] AS weight_loss,
    doc #>> '{fields,poor_weight_gain}'::text[] AS poor_weight_gain,
    doc #>> '{fields,group_tb_screening,is_currently_on_tb_treatment}'::text[] AS is_currently_on_tb_treatment,
    doc #>> '{fields,group_tb_screening,is_still_on_tb_treatment}'::text[] AS is_still_on_tb_treatment,
    doc #>> '{fields,group_tb_screening,have_all_members_been_screened}'::text[] AS have_all_members_been_screened,
    doc #>> '{fields,group_tb_screening,refer_household_members}'::text[] AS refer_household_members,
    doc #>> '{fields,group_tb_health_education,health_education}'::text[] AS health_education,
    doc #>> '{fields,group_tb_health_education,benefits_of_tb_treatment}'::text[] AS benefits_of_tb_treatment,
    doc #>> '{fields,group_tb_health_education,drug_resistance}'::text[] AS drug_resistance,
    doc #>> '{fields,group_tb_health_education,explain_drug_resistance}'::text[] AS explain_drug_resistance,
    doc #>> '{fields,group_tb_health_education,health_education_basics}'::text[] AS health_education_basics,
    doc #>> '{fields,group_tb_health_education,what_is_tb}'::text[] AS what_is_tb,
    doc #>> '{fields,group_tb_health_education,tb_explanation}'::text[] AS tb_explanation,
    doc #>> '{fields,group_tb_health_education,tb_explanation_type}'::text[] AS tb_explanation_type,
    doc #>> '{fields,group_tb_health_education,who_risk_contracting_tb}'::text[] AS who_risk_contracting_tb,
    doc #>> '{fields,group_tb_signs_and_symptoms_of_tb,cough_2_weeks_or_more}'::text[] AS cough_2_weeks_or_more,
    doc #>> '{fields,group_tb_signs_and_symptoms_of_tb,excessive_night_sweats}'::text[] AS excessive_night_sweats,
    doc #>> '{fields,group_tb_signs_and_symptoms_of_tb,unexplained_weight_loss}'::text[] AS unexplained_weight_loss,
    doc #>> '{fields,group_tb_signs_and_symptoms_of_tb,loss_of_appetite_image}'::text[] AS loss_of_appetite_image,
    doc #>> '{fields,group_tb_signs_and_symptoms_of_tb,chest_pain_image}'::text[] AS chest_pain_image,
    doc #>> '{fields,group_tb_signs_and_symptoms_of_tb,poor_weight_gain_among_children}'::text[] AS poor_weight_gain_among_children,
    doc #>> '{fields,group_tb_health_and_status_check,select_tb_risk_factors}'::text[] AS select_tb_risk_factors,
    doc #>> '{fields,group_tb_signs_and_symptoms,currently_have_tb_signs}'::text[] AS currently_have_tb_signs,
    doc #>> '{fields,group_tb_signs_and_symptoms,cough_sign}'::text[] AS cough_sign,
    doc #>> '{fields,group_tb_signs_and_symptoms,cough_duration}'::text[] AS cough_duration,
    doc #>> '{fields,group_tb_signs_and_symptoms,blood_in_cough}'::text[] AS blood_in_cough,
    doc #>> '{fields,group_tb_signs_and_symptoms,fever_symptom}'::text[] AS fever_symptom,
    doc #>> '{fields,group_tb_signs_and_symptoms,fever_duration}'::text[] AS fever_duration,
    doc #>> '{fields,group_tb_signs_and_symptoms,weight_loss_sign}'::text[] AS weight_loss_sign,
    doc #>> '{fields,group_tb_signs_and_symptoms,excessive_night_sweat_sign}'::text[] AS excessive_night_sweat_sign,
    doc #>> '{fields,group_tb_signs_and_symptoms,loss_of_appetite}'::text[] AS loss_of_appetite,
    doc #>> '{fields,group_tb_signs_and_symptoms,chest_pain}'::text[] AS chest_pain,
    doc #>> '{fields,group_tb_signs_and_symptoms,poor_weight_gain_sign}'::text[] AS poor_weight_gain_sign,
    doc #>> '{fields,group_tb_signs_and_symptoms,had_contact_with_tb_person}'::text[] AS had_contact_with_tb_person,
    doc #>> '{fields,group_tb_signs_and_symptoms,suspected_tb_signs}'::text[] AS suspected_tb_signs,
    doc #>> '{fields,group_tb_prevention_measures,note_educate_patient}'::text[] AS note_educate_patient,
    doc #>> '{fields,group_tb_prevention_measures,refer_to_health_facility}'::text[] AS refer_to_health_facility,
    doc #>> '{fields,group_tb_prevention_measures,confirms_referral}'::text[] AS confirms_referral,
    doc #>> '{fields,sputum_collection_consent,consented_sputum_sample}'::text[] AS consented_sputum_sample,
    doc #>> '{fields,sputum_collection_consent,registered_phone_number}'::text[] AS registered_phone_number,
    doc #>> '{fields,sputum_collection_consent,receive_results_on_same_phonenumber}'::text[] AS receive_results_on_same_phonenumber,
    doc #>> '{fields,sputum_collection_consent,enter_new_phone_number}'::text[] AS enter_new_phone_number,
    doc #>> '{fields,sputum_collection_consent,no_registered_phone_number}'::text[] AS no_registered_phone_number,
    doc #>> '{fields,sputum_collection_consent,phonenumber_to_receive_results}'::text[] AS phonenumber_to_receive_results,
    doc #>> '{fields,sputum_collection_consent,results_phone_number}'::text[] AS results_phone_number,
    doc #>> '{fields,sputum_collection,sputum_collection}'::text[] AS sputum_collection,
    doc #>> '{fields,sputum_collection,has_patient_produced_sputum}'::text[] AS has_patient_produced_sputum,
    doc #>> '{fields,sputum_collection,confirm_container_tightly_closed}'::text[] AS confirm_container_tightly_closed,
    doc #>> '{fields,sputum_collection,confirm_send_sample_for_testing}'::text[] AS confirm_send_sample_for_testing,
    doc #>> '{fields,sputum_collection,leave_sputum_bottle_with_client}'::text[] AS leave_sputum_bottle_with_client,
    doc #>> '{fields,sputum_collection,keep_container_closed}'::text[] AS keep_container_closed,
    doc #>> '{fields,sputum_collection,has_left_sputum_bottle_with_client}'::text[] AS has_left_sputum_bottle_with_client,
    doc #>> '{contact,_id}'                         AS chw_id,
      h.facility,
      h.dhis2_facility_id,
      h.village,
      h.district,
      h.region,
      CURRENT_TIMESTAMP                                 AS last_refresh_date  
FROM dwh.cht_data d LEFT JOIN cht.mv_chw_hierarchy h ON (d.doc #>> '{contact,_id}') = h.chw_id
  WHERE (doc ->> 'form'::text) = 'tb_screening'::text AND is_current
WITH DATA;

-- View indexes:
CREATE INDEX tb_screening_reported_idx ON cht.mv_tb_screening USING btree (reported);
CREATE INDEX tb_screening_date_idx ON cht.mv_tb_screening USING btree (date);
CREATE INDEX tb_screening_year_idx ON cht.mv_tb_screening USING btree (year);
CREATE INDEX tb_screening_month_idx ON cht.mv_tb_screening USING btree (month);
CREATE INDEX tb_screening_monthname_idx ON cht.mv_tb_screening USING btree (monthname);
CREATE INDEX tb_screening_chw_id_idx ON cht.mv_tb_screening USING btree (chw_id);
CREATE INDEX tb_screening_facility_idx ON cht.mv_tb_screening USING btree (facility);
CREATE INDEX tb_screening_dhis2_facility_id_idx ON cht.mv_tb_screening USING btree (dhis2_facility_id);
CREATE INDEX tb_screening_village_idx ON cht.mv_tb_screening USING btree (village);
CREATE INDEX tb_screening_district_idx ON cht.mv_tb_screening USING btree (district);
CREATE INDEX tb_screening_region_idx ON cht.mv_tb_screening USING btree (region);