CREATE MATERIALIZED VIEW report.useview_support_supervision
TABLESPACE ts_report
AS
SELECT
      doc ->> '_id'                                                AS uuid,
      doc ->> '_rev'                                               AS rev,
      doc ->> 'form'                                               AS form,
      to_timestamp(NULLIF(doc ->> 'reported_date','')::bigint / 1000.0) AS reported,
      doc ->> 'from'                                               AS submitter,
      doc ->> 'content_type'                                       AS top_content_type,
      to_timestamp(NULLIF(doc #>> '{form_version,time}','')::bigint / 1000.0) AS form_version_time,
      doc #>> '{form_version,sha256}'                              AS form_version_sha256,
      (doc -> 'hidden_fields')::text                               AS hidden_fields_json,
    , doc #>> '{fields,inputs}'                                           AS inputs,
    , doc #>> '{fields,source}'                                           AS source,
    , doc #>> '{fields,source_id}'                                        AS source_id,
    , doc #>> '{fields,task_id}'                                          AS task_id,
    , doc #>> '{fields,contact}'                                          AS contact,
    , doc #>> '{fields,_id}'                                              AS _id,
    , doc #>> '{fields,patient_id}'                                       AS patient_id,
    , doc #>> '{fields,name}'                                             AS name,
    , doc #>> '{fields,contact}'                                          AS fields_contact,
    , doc #>> '{fields,name}'                                             AS fields_name,
    , doc #>> '{fields,reported_date}'                                    AS reported_date,
    , doc #>> '{fields}'                                                  AS col,
    , doc #>> '{fields,parent}'                                           AS parent,
    , doc #>> '{fields,_id}'                                              AS fields__id,
    , doc #>> '{fields,parent}'                                           AS fields_parent,
    , doc #>> '{fields,_id}'                                              AS fields__id_1,
    , doc #>> '{fields,name}'                                             AS fields_name_1,
    , doc #>> '{fields,phone}'                                            AS phone,
    , doc #>> '{fields,parent}'                                           AS fields_parent_1,
    , doc #>> '{fields,_id}'                                              AS fields__id_2,
    , doc #>> '{fields}'                                                  AS fields_,
    , doc #>> '{fields}'                                                  AS fields__1,
    , doc #>> '{fields}'                                                  AS fields__2,
    , doc #>> '{fields}'                                                  AS fields__3,
    , doc #>> '{fields}'                                                  AS fields__4,
    , doc #>> '{fields,patient_id}'                                       AS fields_patient_id,
    , doc #>> '{fields,vht_name}'                                         AS vht_name,
    , doc #>> '{fields,last_supervised}'                                  AS last_supervised,
    , doc #>> '{fields,supervisions_last_quarter}'                        AS supervisions_last_quarter,
    , doc #>> '{fields,months_active}'                                    AS months_active,
    , doc #>> '{fields,commodity_gloves}'                                 AS commodity_gloves,
    , doc #>> '{fields,commodity_malaria}'                                AS commodity_malaria,
    , doc #>> '{fields,commodity_muac}'                                   AS commodity_muac,
    , doc #>> '{fields,commodity_act}'                                    AS commodity_act,
    , doc #>> '{fields,commodity_amox}'                                   AS commodity_amox,
    , doc #>> '{fields,commodity_ors}'                                    AS commodity_ors,
    , doc #>> '{fields,commodity_rectal}'                                 AS commodity_rectal,
    , doc #>> '{fields,commodity_pops}'                                   AS commodity_pops,
    , doc #>> '{fields,commodity_cocs}'                                   AS commodity_cocs,
    , doc #>> '{fields,commodity_ec}'                                     AS commodity_ec,
    , doc #>> '{fields,details}'                                          AS details,
    , doc #>> '{fields,vht_education}'                                    AS vht_education,
    , doc #>> '{fields}'                                                  AS fields__5,
    , doc #>> '{fields,support_supervision}'                              AS support_supervision,
    , doc #>> '{fields,supervision_type}'                                 AS supervision_type,
    , doc #>> '{fields,facility}'                                         AS facility,
    , doc #>> '{fields,last_supervision}'                                 AS last_supervision,
    , doc #>> '{fields,feedback}'                                         AS feedback,
    , doc #>> '{fields,actions}'                                          AS actions,
    , doc #>> '{fields}'                                                  AS fields__6,
    , doc #>> '{fields,training}'                                         AS training,
    , doc #>> '{fields,services_offered}'                                 AS services_offered,
    , doc #>> '{fields,specify}'                                          AS specify,
    , doc #>> '{fields,vht_training}'                                     AS vht_training,
    , doc #>> '{fields,echis_training}'                                   AS echis_training,
    , doc #>> '{fields,actions}'                                          AS fields_actions,
    , doc #>> '{fields}'                                                  AS fields__7,
    , doc #>> '{fields,tools_guidelines}'                                 AS tools_guidelines,
    , doc #>> '{fields,tools}'                                            AS tools,
    , doc #>> '{fields,specify_tools}'                                    AS specify_tools,
    , doc #>> '{fields,iccm_tools}'                                       AS iccm_tools,
    , doc #>> '{fields,specify_icmm_tools}'                               AS specify_icmm_tools,
    , doc #>> '{fields,paper}'                                            AS paper,
    , doc #>> '{fields,actions}'                                          AS fields_actions_1,
    , doc #>> '{fields}'                                                  AS fields__8,
    , doc #>> '{fields,medicines}'                                        AS medicines,
    , doc #>> '{fields,vht_challenges}'                                   AS vht_challenges,
    , doc #>> '{fields,vht_store}'                                        AS vht_store,
    , doc #>> '{fields,dispose}'                                          AS dispose,
    , doc #>> '{fields,actions}'                                          AS fields_actions_2,
    , doc #>> '{fields}'                                                  AS fields__9,
    , doc #>> '{fields,referral}'                                         AS referral,
    , doc #>> '{fields,illness}'                                          AS illness,
    , doc #>> '{fields,vht_guidelines}'                                   AS vht_guidelines,
    , doc #>> '{fields,job_aids}'                                         AS job_aids,
    , doc #>> '{fields,alerts}'                                           AS alerts,
    , doc #>> '{fields,actions}'                                          AS fields_actions_3,
    , doc #>> '{fields}'                                                  AS fields__10,
    , doc #>> '{fields,reporting}'                                        AS reporting,
    , doc #>> '{fields,bundles}'                                          AS bundles,
    , doc #>> '{fields,bundles_received}'                                 AS bundles_received,
    , doc #>> '{fields,last_sync}'                                        AS last_sync,
    , doc #>> '{fields,facilitation}'                                     AS facilitation,
    , doc #>> '{fields,actions}'                                          AS fields_actions_4,
    , doc #>> '{fields}'                                                  AS fields__11,
    , doc #>> '{fields,behavior}'                                         AS behavior,
    , doc #>> '{fields,education_messages}'                               AS education_messages,
    , doc #>> '{fields,dialogues}'                                        AS dialogues,
    , doc #>> '{fields,actions}'                                          AS fields_actions_5,
    , doc #>> '{fields}'                                                  AS fields__12,
    , doc #>> '{fields,challenges}'                                       AS challenges,
    , doc #>> '{fields,issues}'                                           AS issues,
    , doc #>> '{fields,describe_issues}'                                  AS describe_issues,
    , doc #>> '{fields,other_challenges}'                                 AS other_challenges,
    , doc #>> '{fields,actions}'                                          AS fields_actions_6,
    , doc #>> '{fields}'                                                  AS fields__13,
    , doc #>> '{fields,group_patient_summary,ss_action}'                  AS ss_action,
    , doc #>> '{fields,group_patient_summary,ss_solution}'                AS ss_solution,
    , doc #>> '{fields,group_patient_summary,ss_timeline}'                AS ss_timeline,
    , doc #>> '{fields,group_patient_summary,ss_person}'                  AS ss_person,
    , doc #>> '{fields,group_patient_summary,tr_action}'                  AS tr_action,
    , doc #>> '{fields,group_patient_summary,tr_solution}'                AS tr_solution,
    , doc #>> '{fields,group_patient_summary,tr_timeline}'                AS tr_timeline,
    , doc #>> '{fields,group_patient_summary,tr_person}'                  AS tr_person,
    , doc #>> '{fields,group_patient_summary,tools_action}'               AS tools_action,
    , doc #>> '{fields,group_patient_summary,tools_solution}'             AS tools_solution,
    , doc #>> '{fields,group_patient_summary,tools_timeline}'             AS tools_timeline,
    , doc #>> '{fields,group_patient_summary,tools_person}'               AS tools_person,
    , doc #>> '{fields,group_patient_summary,med_action}'                 AS med_action,
    , doc #>> '{fields,group_patient_summary,med_solution}'               AS med_solution,
    , doc #>> '{fields,group_patient_summary,med_timeline}'               AS med_timeline,
    , doc #>> '{fields,group_patient_summary,med_person}'                 AS med_person,
    , doc #>> '{fields,group_patient_summary,ref_action}'                 AS ref_action,
    , doc #>> '{fields,group_patient_summary,ref_solution}'               AS ref_solution,
    , doc #>> '{fields,group_patient_summary,ref_timeline}'               AS ref_timeline,
    , doc #>> '{fields,group_patient_summary,ref_person}'                 AS ref_person,
    , doc #>> '{fields,group_patient_summary,rep_action}'                 AS rep_action,
    , doc #>> '{fields,group_patient_summary,rep_solution}'               AS rep_solution,
    , doc #>> '{fields,group_patient_summary,rep_timeline}'               AS rep_timeline,
    , doc #>> '{fields,group_patient_summary,rep_person}'                 AS rep_person,
    , doc #>> '{fields,group_patient_summary,beh_action}'                 AS beh_action,
    , doc #>> '{fields,group_patient_summary,beh_solution}'               AS beh_solution,
    , doc #>> '{fields,group_patient_summary,beh_timeline}'               AS beh_timeline,
    , doc #>> '{fields,group_patient_summary,beh_person}'                 AS beh_person,
    , doc #>> '{fields,group_patient_summary,ch_action}'                  AS ch_action,
    , doc #>> '{fields,group_patient_summary,ch_solution}'                AS ch_solution,
    , doc #>> '{fields,group_patient_summary,ch_timeline}'                AS ch_timeline,
    , doc #>> '{fields,group_patient_summary,ch_person}'                  AS ch_person,
    , doc #>> '{fields,group_patient_summary}'                            AS group_patient_summary_
FROM dwh.cht_data AS couchdb
WHERE (doc ->> 'form') = 'support_supervision'
  AND is_current
WITH DATA;

CREATE UNIQUE INDEX support_supervision_uuid_idx
    ON report.useview_support_supervision USING btree (uuid);

CREATE INDEX support_supervision_reported_idx
    ON report.useview_support_supervision USING btree (reported);
