SELECT doc_id as id,
    rev,
    instanceid,
    geo_latitude,
    geo_longitude,
    geo_accuracy,
    geo_altitude,
    geo_speed,
    user_contact_id as contact_id,
    user_facility_id as vht_area_id,
    user_facility_id as facility_id,
    district,
    region,
    form,
    "from",
    type,
    lmp,
    edd_std,
    edd_local,
    chw_name,
    chw_phone,
    chw_village,
    chw_area_name,
    patient_id,
    patient_name,
    patient_gender,
    patient_age_in_days,
    patient_age_in_years,
    patient_age_in_months,
    patient_age_display,
    visited_contact_uuid,
    is_of_child_bearing_age,
    needs_signoff,
    ds_fever,
    ds_swelling,
    ds_very_pale,
    ds_blurred_vision,
    ds_breathlessness,
    ds_severe_headache,
    ds_vaginal_bleeding,
    ds_lower_abdomen_pain,
    ds_has_no_danger_signs,
    ds_reduced_or_no_feotal_movements as ds_reduced_feotal_movements,
    ds_note_danger_signs,
    ds_note_has_no_danger_signs,
    taken_muac as nutrition_taken_muac,
    muac_measurement as nutrition_muac_measurement,
    on_nutrition_follow_up as nutrition_on_follow_up,
    schedule_follow_up_visit as nutrition_schedule_follow_up,
    micro_nutrient_supplementation_received as nutrition_micro_nutrient_received,
    anc_visits,
    hiv_test_done as anc_hiv_test_done,
    hiv_test_result as anc_hiv_test_result,
    number_of_anc_visits,
    anc_appointment_date,
    has_upcoming_anc_visits,
    using_llin,
    has_tt_card,
    tt_immunizations,
    received_tt_immunizations
   FROM cht.mv_pregnancy p
  WHERE (district) = ANY (ARRAY['Bushenyi District'::text, 'Masaka city'::text, 'Jinja city'::text, 'Mbale city'::text, 'Sheema District'::text, 'Wakiso District'::text]);
