CREATE OR REPLACE VIEW report.v_active_case_search_alerts
AS SELECT fact_odk_submission_key,
    dim_odk_project_key,
    dim_odk_form_key,
    submission_instance_id,
    project_id,
    form_xml_id,
    submission_date,
    data ->> '__id'::text AS odk_id,
    data #>> '{meta,instanceID}'::text[] AS meta_instance_id,
    (data ->> 'start'::text)::timestamp with time zone AS start_time,
    (data ->> 'end'::text)::timestamp with time zone AS end_time,
    (data ->> 'Date'::text)::date AS report_date,
    (data #>> '{__system,submissionDate}'::text[])::timestamp with time zone AS system_submission_date,
    data #>> '{__system,submitterId}'::text[] AS submitter_id,
    data #>> '{__system,submitterName}'::text[] AS submitter_name,
    NULLIF(data #>> '{__system,edits}'::text[], ''::text) AS edits,
    NULLIF(data #>> '{__system,attachmentsPresent}'::text[], ''::text) AS attachments_present,
    NULLIF(data #>> '{__system,attachmentsExpected}'::text[], ''::text) AS attachments_expected,
    NULLIF(data ->> 'Age'::text, ''::text) AS age,
    data ->> 'Sex'::text AS sex,
    data ->> 'Nationality'::text AS nationality,
    data ->> 'Patient_Name'::text AS patient_name,
    data ->> 'Phone_number'::text AS phone_number,
    data ->> 'region'::text AS region,
    data ->> 'district'::text AS district,
    data ->> 'subcounty'::text AS subcounty,
    data ->> 'Parish_or_Ward'::text AS parish_or_ward,
    data ->> 'Village_or_Cell'::text AS village_or_cell,
    data ->> 'facility'::text AS facility,
    data ->> 'Team_Lead'::text AS team_lead,
    data ->> 'Team_Submiting'::text AS team_submitting,
    data ->> 'If_other_specify'::text AS if_other_specify,
    (data #>> '{GPS_of_facility,coordinates,0}'::text[])::numeric AS gps_longitude,
    (data #>> '{GPS_of_facility,coordinates,1}'::text[])::numeric AS gps_latitude,
    (data #>> '{GPS_of_facility,coordinates,2}'::text[])::numeric AS gps_altitude,
    NULLIF(data #>> '{GPS_of_facility,properties,accuracy}'::text[], ''::text)::numeric AS gps_accuracy,
    (data ->> 'Date_of_admission'::text)::date AS date_of_admission,
    data ->> 'Signs_and_Symptoms'::text AS signs_and_symptoms,
    data ->> 'If_other_symptoms_specify'::text AS if_other_symptoms_specify,
    data ->> 'Verification_outcome'::text AS verification_outcome,
    data ->> 'Comments_from_verification'::text AS comments_from_verification,
    data ->> 'Is_the_alert_a_suspected_case'::text AS is_the_alert_a_suspected_case,
    data ->> 'Patient_diagnosis_or_diagnoses'::text AS patient_diagnosis_or_diagnoses,
    data ->> 'Was_the_patient_a_re_attendance'::text AS was_the_patient_a_re_attendance,
    data ->> 'Does_the_patient_hav_he_onset_of_symptoms'::text AS does_the_patient_have_onset_of_symptoms,
    data ->> 'Any_additional_information'::text AS any_additional_information
   FROM dwh.fact_odk_submissions f
  WHERE is_current AND (form_xml_id = ANY (ARRAY['active_case_search_alerts'::text, 'Active_case_search_alerts'::text]))
  ORDER BY submission_date DESC;